package zone

import (
	"bufio"
	"fmt"
	"math"
	"os"
	"strconv"
	"strings"
	"testing"

	"github.com/fatal10110/acis_golang/internal/gameserver/model/location"
	"github.com/fatal10110/acis_golang/internal/gameserver/world"
)

// ---- from form_test.go ----
// TestFormOracle replays testdata/form_oracle.txt, a fixture generated by
// running the reference Java zone form implementations (ZoneCuboid,
// ZoneCylinder, ZoneNPoly from the aCis gameserver) over ~12k containment
// and rectangle-intersection probes.
func TestFormOracle(t *testing.T) {
	f, err := os.Open("testdata/form_oracle.txt")
	if err != nil {
		t.Fatalf("open oracle fixture: %v", err)
	}
	defer f.Close()

	forms := make(map[string]Form)
	var inCases, rectCases int
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 1<<20), 1<<20)
	line := 0
	for sc.Scan() {
		line++
		fields := strings.Fields(sc.Text())
		if len(fields) == 0 {
			continue
		}
		switch fields[0] {
		case "form":
			form, err := parseOracleForm(fields)
			if err != nil {
				t.Fatalf("line %d: %v", line, err)
			}
			forms[fields[1]] = form
		case "in":
			form, ok := forms[fields[1]]
			if !ok {
				t.Fatalf("line %d: unknown form %q", line, fields[1])
			}
			x, y, z := atoiT(t, fields[2]), atoiT(t, fields[3]), atoiT(t, fields[4])
			want := fields[5] == "1"
			if got := form.Contains(x, y, z); got != want {
				t.Errorf("line %d: %s.Contains(%d, %d, %d) = %v, oracle says %v", line, fields[1], x, y, z, got, want)
			}
			inCases++
		case "rect":
			form, ok := forms[fields[1]]
			if !ok {
				t.Fatalf("line %d: unknown form %q", line, fields[1])
			}
			x1, x2, y1, y2 := atoiT(t, fields[2]), atoiT(t, fields[3]), atoiT(t, fields[4]), atoiT(t, fields[5])
			want := fields[6] == "1"
			if got := form.IntersectsRect(x1, x2, y1, y2); got != want {
				t.Errorf("line %d: %s.IntersectsRect(%d, %d, %d, %d) = %v, oracle says %v", line, fields[1], x1, x2, y1, y2, got, want)
			}
			rectCases++
		default:
			t.Fatalf("line %d: unknown record %q", line, fields[0])
		}
	}
	if err := sc.Err(); err != nil {
		t.Fatalf("read oracle fixture: %v", err)
	}
	if len(forms) < 12 || inCases < 5000 || rectCases < 3000 {
		t.Fatalf("suspiciously small fixture: %d forms, %d containment cases, %d rectangle cases", len(forms), inCases, rectCases)
	}
}

func parseOracleForm(fields []string) (Form, error) {
	switch fields[2] {
	case "cuboid":
		if len(fields) != 9 {
			return nil, fmt.Errorf("cuboid wants 6 coordinates, got %d fields", len(fields))
		}
		v := make([]int, 6)
		for i := range v {
			n, err := strconv.Atoi(fields[3+i])
			if err != nil {
				return nil, err
			}
			v[i] = n
		}
		return NewCuboid(v[0], v[1], v[2], v[3], v[4], v[5])
	case "cylinder":
		if len(fields) != 8 {
			return nil, fmt.Errorf("cylinder wants 5 values, got %d fields", len(fields))
		}
		v := make([]int, 5)
		for i := range v {
			n, err := strconv.Atoi(fields[3+i])
			if err != nil {
				return nil, err
			}
			v[i] = n
		}
		return NewCylinder(v[0], v[1], v[2], v[3], v[4])
	case "npoly":
		z1, err := strconv.Atoi(fields[3])
		if err != nil {
			return nil, err
		}
		z2, err := strconv.Atoi(fields[4])
		if err != nil {
			return nil, err
		}
		nodes := make([]location.Point, 0, len(fields)-5)
		for _, pair := range fields[5:] {
			xy := strings.SplitN(pair, ",", 2)
			x, err := strconv.Atoi(xy[0])
			if err != nil {
				return nil, err
			}
			y, err := strconv.Atoi(xy[1])
			if err != nil {
				return nil, err
			}
			nodes = append(nodes, location.Point{X: x, Y: y})
		}
		return NewPolygon(nodes, z1, z2)
	default:
		return nil, fmt.Errorf("unknown form kind %q", fields[2])
	}
}

func atoiT(t *testing.T, s string) int {
	t.Helper()
	n, err := strconv.Atoi(s)
	if err != nil {
		t.Fatalf("parse %q: %v", s, err)
	}
	return n
}

func TestNewCylinderRejectsNonPositiveRadius(t *testing.T) {
	for _, rad := range []int{0, -5} {
		if _, err := NewCylinder(0, 0, 0, 10, rad); err == nil {
			t.Errorf("NewCylinder(rad=%d) succeeded, want error", rad)
		}
	}
}

func TestNewCylinderRejectsOutOfInt32Range(t *testing.T) {
	for _, v := range [][3]int{{math.MaxInt32 + 1, 0, 10}, {0, math.MinInt32 - 1, 10}, {0, 0, math.MaxInt32 + 1}} {
		if _, err := NewCylinder(v[0], v[1], 0, 10, v[2]); err == nil {
			t.Errorf("NewCylinder(%d, %d, rad=%d) succeeded, want error", v[0], v[1], v[2])
		}
	}
	// At the limit the cylinder is accepted but lies far off the grid, so
	// the index attaches it to no region.
	far, err := NewCylinder(math.MaxInt32, math.MaxInt32, 0, 10, math.MaxInt32)
	if err != nil {
		t.Fatalf("NewCylinder at the limit: %v", err)
	}
	ix := NewIndex()
	ix.Add(NewFishing(1, far))
	for rx := range world.RegionsX {
		for ry := range world.RegionsY {
			if len(ix.byRegion[rx][ry]) != 0 {
				t.Fatalf("far cylinder attached to region %d,%d", rx, ry)
			}
		}
	}
}

func TestNewPolygonRejectsTooFewVertices(t *testing.T) {
	nodes := []location.Point{{X: 0, Y: 0}, {X: 1, Y: 1}}
	if _, err := NewPolygon(nodes, 0, 10); err == nil {
		t.Error("NewPolygon with 2 vertices succeeded, want error")
	}
}

func TestInvertedZPolygonIntersectsRectNeverFullyContains(t *testing.T) {
	// Some datapack zones declare an inverted z range (maxZ < minZ), e.g.
	// ScriptZone.xml's archaic_laboratory_gate zones. The historical
	// containment probe is dead for any inverted or zero-height range, not
	// just zero-height, so a query rect sitting entirely inside the
	// polygon's footprint must still report no overlap.
	nodes := []location.Point{{X: 0, Y: 0}, {X: 100, Y: 0}, {X: 100, Y: 100}, {X: 0, Y: 100}}
	form, err := NewPolygon(nodes, -3300, -3400)
	if err != nil {
		t.Fatalf("NewPolygon: %v", err)
	}
	if form.IntersectsRect(10, 20, 10, 20) {
		t.Error("inverted-z polygon reported a fully-interior rect as intersecting, want false")
	}
	// A rect crossing the boundary must still count.
	if !form.IntersectsRect(-10, 10, -10, 10) {
		t.Error("inverted-z polygon failed to detect a boundary-crossing rect")
	}
}

func TestCuboidNormalizesCorners(t *testing.T) {
	a, err := NewCuboid(0, 100, 0, 200, -50, 50)
	if err != nil {
		t.Fatalf("NewCuboid: %v", err)
	}
	b, err := NewCuboid(100, 0, 200, 0, 50, -50)
	if err != nil {
		t.Fatalf("NewCuboid: %v", err)
	}
	if a.LowZ() != -50 || a.HighZ() != 50 {
		t.Errorf("a z bounds = %d..%d, want -50..50", a.LowZ(), a.HighZ())
	}
	if b.LowZ() != -50 || b.HighZ() != 50 {
		t.Errorf("b z bounds = %d..%d, want -50..50", b.LowZ(), b.HighZ())
	}
	probes := [][3]int{{0, 0, 0}, {100, 200, 0}, {50, 100, 0}, {-1, 0, 0}, {0, -1, 0}, {50, 100, 60}}
	for _, p := range probes {
		if a.Contains(p[0], p[1], p[2]) != b.Contains(p[0], p[1], p[2]) {
			t.Errorf("reversed corners disagree at (%d, %d, %d)", p[0], p[1], p[2])
		}
		if a.IntersectsRect(p[0]-1, p[0]+1, p[1]-1, p[1]+1) != b.IntersectsRect(p[0]-1, p[0]+1, p[1]-1, p[1]+1) {
			t.Errorf("reversed corners disagree on IntersectsRect near (%d, %d)", p[0], p[1])
		}
	}
}

// TestIndexAttachesEveryRegionIntersectsRectReports checks that Add, which
// skips the rows away from a footprint, attaches a zone to exactly the
// regions a scan of the whole grid would. The wide ring's corner probe
// wraps in 32-bit arithmetic and claims regions far outside it on the x
// axis; they must stay attached.
func TestIndexAttachesEveryRegionIntersectsRectReports(t *testing.T) {
	mustForm := func(f Form, err error) Form {
		t.Helper()
		if err != nil {
			t.Fatal(err)
		}
		return f
	}
	wide := mustForm(NewPolygon([]location.Point{{X: -76016, Y: 98}, {X: 50773, Y: 81087}, {X: -76016, Y: 81087}}, -4848, -3760))
	forms := map[string]Form{
		"wide ring":         wide,
		"inverted-z ring":   mustForm(NewPolygon([]location.Point{{X: 1000, Y: 1000}, {X: 9000, Y: 1500}, {X: 5000, Y: 7000}}, 100, -100)),
		"cuboid on a seam":  mustForm(NewCuboid(-2048, 2048, -4096, 0, -100, 100)),
		"cylinder":          mustForm(NewCylinder(81000, -120000, -100, 100, 3000)),
		"off the grid edge": mustForm(NewCuboid(world.MinX-5000, world.MinX+10, world.MaxY-10, world.MaxY+5000, 0, 1)),
	}
	for name, form := range forms {
		ix := NewIndex()
		ix.Add(NewFishing(1, form))
		minX, maxX, _, _ := form.Bounds()
		farColumns := 0
		for rx := range world.RegionsX {
			x1 := world.MinX + rx*regionEdge
			for ry := range world.RegionsY {
				y1 := world.MinY + ry*regionEdge
				want := form.IntersectsRect(x1, x1+regionEdge, y1, y1+regionEdge)
				if got := len(ix.byRegion[rx][ry]) == 1; got != want {
					t.Fatalf("%s: region %d,%d attached = %v, IntersectsRect = %v", name, rx, ry, got, want)
				}
				if want && (x1+regionEdge < minX || x1 > maxX) {
					farColumns++
				}
			}
		}
		if name == "wide ring" && farColumns == 0 {
			t.Fatal("wide ring: no region outside its x extent reported, want the wrapped corner probe to claim some")
		}
	}
}
