// Command configkeygen regenerates internal/config/supported_keys_generated.go
// from the keys actually read by config.Properties/config.Fields accessors,
// intersected against the shipped .properties files vendored under
// internal/config/testdata/reference (a snapshot of aCis_gameserver/config,
// kept self-contained here since CI checks out only this repository).
//
// Invoked via internal/config's //go:generate directive, which runs it with
// the working directory set to internal/config.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"

	"github.com/fatal10110/acis_golang/internal/config"
	"github.com/fatal10110/acis_golang/internal/config/keyscan"
)

const outFile = "supported_keys_generated.go"

func main() {
	cwd, err := os.Getwd()
	must(err)

	goRoot := filepath.Join(cwd, "..", "..") // internal/config -> <go-root>
	refConfigDir := filepath.Join(cwd, "testdata", "reference")

	readKeys, err := scanReadKeys(goRoot)
	must(err)

	registry := make(map[string][]string, len(config.ShippedFiles))
	for _, name := range config.ShippedFiles {
		props, err := config.LoadFile(filepath.Join(refConfigDir, name))
		must(err)
		for _, key := range props.Keys() {
			if readKeys[key] {
				registry[name] = append(registry[name], key)
			}
		}
	}

	must(writeRegistry(outFile, registry))
}

func scanReadKeys(goRoot string) (map[string]bool, error) {
	set := map[string]bool{}
	for _, dir := range []string{"cmd", "internal"} {
		keys, err := keyscan.Scan(filepath.Join(goRoot, dir))
		if err != nil {
			return nil, err
		}
		for _, k := range keys {
			set[k] = true
		}
	}
	return set, nil
}

func writeRegistry(out string, registry map[string][]string) error {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by internal/config/gen. DO NOT EDIT.\n")
	buf.WriteString("// Run `go generate ./internal/config/...` to refresh.\n\n")
	buf.WriteString("package config\n\n")
	buf.WriteString("// SupportedKeys lists, per shipped .properties file, every key read by an\n")
	buf.WriteString("// existing Go accessor call. It backs the UnknownKeys drift check.\n")
	buf.WriteString("var SupportedKeys = map[string][]string{\n")
	for _, name := range config.ShippedFiles {
		keys := registry[name]
		fmt.Fprintf(&buf, "\t%q: {\n", name)
		for _, k := range keys {
			fmt.Fprintf(&buf, "\t\t%q,\n", k)
		}
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return err
	}
	return os.WriteFile(out, formatted, 0o644)
}

func must(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
