package player

import "testing"

// realPlayerLevelExp holds the requiredExpToLevelUp value for every level
// 1-81 of the shipped player level table (level 81 is the sentinel entry
// that closes level 80's experience band). Values generated by running the
// reference level-progression logic against the shipped data file.
var realPlayerLevelExp = []int64{
	0, 68, 363, 1168, 2884, 6038, 11287, 19423, 31378, 48229,
	71201, 101676, 141192, 191452, 254327, 331864, 426284, 539995, 675590, 835854,
	1023775, 1242536, 1495531, 1786365, 2118860, 2497059, 2925229, 3407873, 3949727, 4555766,
	5231213, 5981539, 6812472, 7729999, 8740372, 9850111, 11066012, 12395149, 13844879, 15422851,
	17137002, 18995573, 21007103, 23180442, 25524751, 28049509, 30764519, 33679907, 36806133, 40153995,
	45524865, 51262204, 57383682, 63907585, 70852742, 80700339, 91162131, 102265326, 114038008, 126509030,
	146307211, 167243291, 189363788, 212716741, 237351413, 271973532, 308441375, 346825235, 387197529, 429632402,
	474205751, 532692055, 606319094, 696376867, 804219972, 931275828, 1151275834, 1511275834, 2099275834, 4200000000,
	6299994999,
}

func realLevelTable(t *testing.T) *LevelTable {
	t.Helper()
	levels := make(map[int]Level, len(realPlayerLevelExp))
	for i, exp := range realPlayerLevelExp {
		levels[i+1] = Level{RequiredExpToLevelUp: exp}
	}
	table, err := NewLevelTable(levels)
	if err != nil {
		t.Fatalf("realLevelTable: %v", err)
	}
	return table
}

// levelStepTemplate returns a template whose HP/MP/CP tables carry a
// distinct, easily recognizable value per level, so a test can assert
// which table row a level-up resync picked up.
func levelStepTemplate(levels int) *Template {
	hp := make([]float64, levels)
	mp := make([]float64, levels)
	cp := make([]float64, levels)
	for i := 0; i < levels; i++ {
		hp[i] = 100 + float64(i)*10
		mp[i] = 50 + float64(i)*5
		cp[i] = 20 + float64(i)*2
	}
	return &Template{HPTable: hp, MPTable: mp, CPTable: cp}
}

func newProgressionCharacter() *Character {
	tmpl := levelStepTemplate(81)
	return &Character{
		Level: 1,
		MaxHP: tmpl.HPTable[0], CurHP: tmpl.HPTable[0],
		MaxMP: tmpl.MPTable[0], CurMP: tmpl.MPTable[0],
		MaxCP: tmpl.CPTable[0], CurCP: tmpl.CPTable[0],
	}
}

// TestCharacter_AddExpAndSp compares Go's exp/sp/level accumulation
// against expected values generated by running the reference
// exp/sp/level-progression logic (PlayableStatus/PlayerStatus's addExp,
// addLevel, addSp) against the shipped player level table.
func TestCharacter_AddExpAndSp(t *testing.T) {
	table := realLevelTable(t)
	tmpl := levelStepTemplate(81)

	tests := []struct {
		name        string
		exp         int64
		sp          int
		wantLevel   int
		wantExp     int64
		wantSP      int
		wantLeveled bool
		wantMaxHP   float64
		wantMaxMP   float64
		wantMaxCP   float64
	}{
		{
			name: "small exp below next threshold stays at level 1", exp: 50, sp: 0,
			wantLevel: 1, wantExp: 50, wantSP: 0, wantLeveled: false,
			wantMaxHP: 100, wantMaxMP: 50, wantMaxCP: 20,
		},
		{
			name: "exp exactly at level 2 threshold levels up", exp: 68, sp: 0,
			wantLevel: 2, wantExp: 68, wantSP: 0, wantLeveled: true,
			wantMaxHP: 110, wantMaxMP: 55, wantMaxCP: 22,
		},
		{
			name: "multi-level jump from 1 to 5", exp: 2884, sp: 0,
			wantLevel: 5, wantExp: 2884, wantSP: 0, wantLeveled: true,
			wantMaxHP: 140, wantMaxMP: 70, wantMaxCP: 28,
		},
		{
			name: "sp only, no exp added", exp: 0, sp: 500,
			wantLevel: 1, wantExp: 0, wantSP: 500, wantLeveled: false,
			wantMaxHP: 100, wantMaxMP: 50, wantMaxCP: 20,
		},
		{
			name: "exp and sp together crossing into level 3", exp: 363, sp: 1200,
			wantLevel: 3, wantExp: 363, wantSP: 1200, wantLeveled: true,
			wantMaxHP: 120, wantMaxMP: 60, wantMaxCP: 24,
		},
		{
			name: "huge exp caps just below the highest level's band", exp: 4611686018427387903, sp: 0,
			wantLevel: 80, wantExp: 6299994998, wantSP: 0, wantLeveled: true,
			wantMaxHP: 890, wantMaxMP: 445, wantMaxCP: 178,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			c := newProgressionCharacter()
			leveled := c.AddExpAndSp(table, tmpl, tt.exp, tt.sp)

			if leveled != tt.wantLeveled {
				t.Errorf("AddExpAndSp() leveled = %v, want %v", leveled, tt.wantLeveled)
			}
			if c.Level != tt.wantLevel {
				t.Errorf("Level = %d, want %d", c.Level, tt.wantLevel)
			}
			if c.Exp != tt.wantExp {
				t.Errorf("Exp = %d, want %d", c.Exp, tt.wantExp)
			}
			if c.SP != tt.wantSP {
				t.Errorf("SP = %d, want %d", c.SP, tt.wantSP)
			}
			if c.MaxHP != tt.wantMaxHP || c.CurHP != tt.wantMaxHP {
				t.Errorf("MaxHP/CurHP = %v/%v, want %v", c.MaxHP, c.CurHP, tt.wantMaxHP)
			}
			if c.MaxMP != tt.wantMaxMP || c.CurMP != tt.wantMaxMP {
				t.Errorf("MaxMP/CurMP = %v/%v, want %v", c.MaxMP, c.CurMP, tt.wantMaxMP)
			}
			if c.MaxCP != tt.wantMaxCP || c.CurCP != tt.wantMaxCP {
				t.Errorf("MaxCP/CurCP = %v/%v, want %v", c.MaxCP, c.CurCP, tt.wantMaxCP)
			}
		})
	}
}

// TestCharacter_AddSp_Saturates matches the reference SP accumulator's
// 32-bit signed integer ceiling.
func TestCharacter_AddSp_Saturates(t *testing.T) {
	c := newProgressionCharacter()
	c.SP = maxSP - 5

	c.AddSp(100)

	if c.SP != maxSP {
		t.Errorf("SP = %d, want %d", c.SP, maxSP)
	}
}

// TestCharacter_AddExp_OverflowGuard matches the reference accumulator's
// no-op behavior when an addition would overflow experience negative.
func TestCharacter_AddExp_OverflowGuard(t *testing.T) {
	table := realLevelTable(t)
	tmpl := levelStepTemplate(81)

	c := newProgressionCharacter()
	c.Level = 80
	c.Exp = 6000000000

	leveled := c.AddExp(table, tmpl, 1<<63-1)

	if leveled {
		t.Errorf("AddExp() leveled = true, want false (overflow no-op)")
	}
	if c.Exp != 6000000000 {
		t.Errorf("Exp = %d, want unchanged 6000000000", c.Exp)
	}
	if c.Level != 80 {
		t.Errorf("Level = %d, want unchanged 80", c.Level)
	}
}

// TestCharacter_RemoveExpAndSp compares Go's exp/sp/level removal against
// values generated by running the reference removeExp/removeSp/addLevel
// logic against the shipped player level table.
func TestCharacter_RemoveExpAndSp(t *testing.T) {
	table := realLevelTable(t)
	tmpl := levelStepTemplate(81)

	t.Run("removing exp delevels and does not refill HP/MP/CP", func(t *testing.T) {
		c := newProgressionCharacter()
		c.AddExpAndSp(table, tmpl, 363, 0) // level 3, exp 363, HP/MP/CP at level 3's row

		c.RemoveExpAndSp(table, tmpl, 300, 0) // exp -> 63, under level 2's 68 threshold

		if c.Level != 1 {
			t.Errorf("Level = %d, want 1", c.Level)
		}
		if c.Exp != 63 {
			t.Errorf("Exp = %d, want 63", c.Exp)
		}
		// A delevel never refills HP/MP/CP: the level-3 row values persist.
		if c.MaxHP != 120 || c.MaxMP != 60 || c.MaxCP != 24 {
			t.Errorf("MaxHP/MP/CP = %v/%v/%v, want 120/60/24 (unrefilled)", c.MaxHP, c.MaxMP, c.MaxCP)
		}
	})

	t.Run("removing more exp than held floors at 1, not 0", func(t *testing.T) {
		c := newProgressionCharacter()
		c.AddExpAndSp(table, tmpl, 50, 0)

		c.RemoveExpAndSp(table, tmpl, 1000, 0)

		if c.Exp != 1 {
			t.Errorf("Exp = %d, want 1", c.Exp)
		}
		if c.Level != 1 {
			t.Errorf("Level = %d, want 1", c.Level)
		}
	})

	t.Run("removing more sp than held floors at 0", func(t *testing.T) {
		c := newProgressionCharacter()
		c.AddExpAndSp(table, tmpl, 0, 30)

		c.RemoveExpAndSp(table, tmpl, 0, 100)

		if c.SP != 0 {
			t.Errorf("SP = %d, want 0", c.SP)
		}
	})
}

// TestCharacter_AddLevel_RefusesPastRealMax matches the reference
// behavior: attempting to add a level past the level table's real max
// leaves the character entirely untouched instead of clamping.
func TestCharacter_AddLevel_RefusesPastRealMax(t *testing.T) {
	table := realLevelTable(t)
	tmpl := levelStepTemplate(81)

	c := newProgressionCharacter()
	c.Level = table.RealMaxLevel()
	c.Exp = table.RequiredExpForLevel(table.RealMaxLevel())

	leveled := c.AddLevel(table, tmpl, 1)

	if leveled {
		t.Errorf("AddLevel() = true, want false at the real max level")
	}
	if c.Level != table.RealMaxLevel() {
		t.Errorf("Level = %d, want unchanged %d", c.Level, table.RealMaxLevel())
	}
}

// TestCharacter_AddLevel_Direct exercises AddLevel outside the
// exp-accumulation path (e.g. a level granted directly rather than earned
// through experience).
func TestCharacter_AddLevel_Direct(t *testing.T) {
	table := realLevelTable(t)
	tmpl := levelStepTemplate(81)

	c := newProgressionCharacter()
	leveled := c.AddLevel(table, tmpl, 1)

	if !leveled {
		t.Fatal("AddLevel(+1) from level 1: want leveled up")
	}
	if c.Level != 2 {
		t.Errorf("Level = %d, want 2", c.Level)
	}
	if c.Exp != 68 {
		t.Errorf("Exp = %d, want 68 (resynced to level 2's threshold)", c.Exp)
	}
	if c.MaxHP != 110 || c.MaxMP != 55 || c.MaxCP != 22 {
		t.Errorf("MaxHP/MP/CP = %v/%v/%v, want 110/55/22", c.MaxHP, c.MaxMP, c.MaxCP)
	}
}

// TestCharacter_AddLevel_NilTemplateSkipsRefill covers the case where a
// caller doesn't have (or need) the profession template on hand: the level
// and experience still update, but HP/MP/CP are left alone.
func TestCharacter_AddLevel_NilTemplateSkipsRefill(t *testing.T) {
	table := realLevelTable(t)

	c := newProgressionCharacter()
	leveled := c.AddLevel(table, nil, 1)

	if !leveled {
		t.Fatal("AddLevel(+1) with nil template: want leveled up")
	}
	if c.Level != 2 {
		t.Errorf("Level = %d, want 2", c.Level)
	}
	if c.MaxHP != 100 {
		t.Errorf("MaxHP = %v, want unchanged 100 (no template to resync from)", c.MaxHP)
	}
}

func TestLevelTable_RequiredExpForLevel(t *testing.T) {
	table := realLevelTable(t)

	if got := table.RequiredExpForLevel(3); got != 363 {
		t.Errorf("RequiredExpForLevel(3) = %d, want 363", got)
	}
	if got := table.RequiredExpForLevel(9999); got != 0 {
		t.Errorf("RequiredExpForLevel(9999) = %d, want 0 (absent entry)", got)
	}
}

func TestLevelTable_ExpSpanAtLevel(t *testing.T) {
	table := realLevelTable(t)

	if got, want := table.ExpSpanAtLevel(1), int64(68); got != want {
		t.Errorf("ExpSpanAtLevel(1) = %d, want %d", got, want)
	}
	// At/above the level cap, the span falls back to the top band's width
	// (level 80 to level 81's threshold).
	wantTopSpan := realPlayerLevelExp[80] - realPlayerLevelExp[79]
	if got := table.ExpSpanAtLevel(table.RealMaxLevel()); got != wantTopSpan {
		t.Errorf("ExpSpanAtLevel(realMaxLevel) = %d, want %d", got, wantTopSpan)
	}
	if got := table.ExpSpanAtLevel(table.MaxLevel()); got != wantTopSpan {
		t.Errorf("ExpSpanAtLevel(maxLevel) = %d, want %d", got, wantTopSpan)
	}
}
