package player

import "testing"

// realPlayerLevelExp holds the requiredExpToLevelUp value for every level
// 1-81 of the shipped player level table (level 81 is the sentinel entry
// that closes level 80's experience band). Values generated by running the
// reference level-progression logic against the shipped data file.
var realPlayerLevelExp = []int64{
	0, 68, 363, 1168, 2884, 6038, 11287, 19423, 31378, 48229,
	71201, 101676, 141192, 191452, 254327, 331864, 426284, 539995, 675590, 835854,
	1023775, 1242536, 1495531, 1786365, 2118860, 2497059, 2925229, 3407873, 3949727, 4555766,
	5231213, 5981539, 6812472, 7729999, 8740372, 9850111, 11066012, 12395149, 13844879, 15422851,
	17137002, 18995573, 21007103, 23180442, 25524751, 28049509, 30764519, 33679907, 36806133, 40153995,
	45524865, 51262204, 57383682, 63907585, 70852742, 80700339, 91162131, 102265326, 114038008, 126509030,
	146307211, 167243291, 189363788, 212716741, 237351413, 271973532, 308441375, 346825235, 387197529, 429632402,
	474205751, 532692055, 606319094, 696376867, 804219972, 931275828, 1151275834, 1511275834, 2099275834, 4200000000,
	6299994999,
}

func realLevelTable(t *testing.T) *LevelTable {
	t.Helper()
	levels := make(map[int]Level, len(realPlayerLevelExp))
	for i, exp := range realPlayerLevelExp {
		levels[i+1] = Level{RequiredExpToLevelUp: exp}
	}
	table, err := NewLevelTable(levels)
	if err != nil {
		t.Fatalf("realLevelTable: %v", err)
	}
	return table
}

// levelStepTemplate returns a template whose HP/MP/CP tables carry a
// distinct, easily recognizable value per level, so a test can assert
// which table row a level-up resync picked up.
func levelStepTemplate(levels int) *Template {
	hp := make([]float64, levels)
	mp := make([]float64, levels)
	cp := make([]float64, levels)
	for i := 0; i < levels; i++ {
		hp[i] = 100 + float64(i)*10
		mp[i] = 50 + float64(i)*5
		cp[i] = 20 + float64(i)*2
	}
	return &Template{HPTable: hp, MPTable: mp, CPTable: cp}
}

func newProgressionCharacter() *Character {
	tmpl := levelStepTemplate(81)
	c := &Character{
		CharLevel: 1,
	}
	c.SetResourceValues(Resources{
		MaxHP: tmpl.HPTable[0], CurrentHP: tmpl.HPTable[0],
		MaxMP: tmpl.MPTable[0], CurrentMP: tmpl.MPTable[0],
		MaxCP: tmpl.CPTable[0], CurrentCP: tmpl.CPTable[0],
	})
	return c
}

// TestCharacter_AddExpAndSp compares Go's exp/sp/level accumulation
// against expected values generated by running the reference
// exp/sp/level-progression logic (PlayableStatus/PlayerStatus's addExp,
// addLevel, addSp) against the shipped player level table.
func TestCharacter_AddExpAndSp(t *testing.T) {
	table := realLevelTable(t)
	tmpl := levelStepTemplate(81)

	tests := []struct {
		name        string
		exp         int64
		sp          int
		wantLevel   int
		wantExp     int64
		wantSP      int
		wantLeveled bool
		wantMaxHP   float64
		wantMaxMP   float64
		wantMaxCP   float64
	}{
		{
			name: "small exp below next threshold stays at level 1", exp: 50, sp: 0,
			wantLevel: 1, wantExp: 50, wantSP: 0, wantLeveled: false,
			wantMaxHP: 100, wantMaxMP: 50, wantMaxCP: 20,
		},
		{
			name: "exp exactly at level 2 threshold levels up", exp: 68, sp: 0,
			wantLevel: 2, wantExp: 68, wantSP: 0, wantLeveled: true,
			wantMaxHP: 110, wantMaxMP: 55, wantMaxCP: 22,
		},
		{
			name: "multi-level jump from 1 to 5", exp: 2884, sp: 0,
			wantLevel: 5, wantExp: 2884, wantSP: 0, wantLeveled: true,
			wantMaxHP: 140, wantMaxMP: 70, wantMaxCP: 28,
		},
		{
			name: "sp only, no exp added", exp: 0, sp: 500,
			wantLevel: 1, wantExp: 0, wantSP: 500, wantLeveled: false,
			wantMaxHP: 100, wantMaxMP: 50, wantMaxCP: 20,
		},
		{
			name: "exp and sp together crossing into level 3", exp: 363, sp: 1200,
			wantLevel: 3, wantExp: 363, wantSP: 1200, wantLeveled: true,
			wantMaxHP: 120, wantMaxMP: 60, wantMaxCP: 24,
		},
		{
			name: "huge exp caps just below the highest level's band", exp: 4611686018427387903, sp: 0,
			wantLevel: 80, wantExp: 6299994998, wantSP: 0, wantLeveled: true,
			wantMaxHP: 890, wantMaxMP: 445, wantMaxCP: 178,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			c := newProgressionCharacter()
			leveled := c.AddExpAndSp(table, tmpl, tt.exp, tt.sp)

			if leveled != tt.wantLeveled {
				t.Errorf("AddExpAndSp() leveled = %v, want %v", leveled, tt.wantLeveled)
			}
			if c.CharLevel != tt.wantLevel {
				t.Errorf("Level = %d, want %d", c.CharLevel, tt.wantLevel)
			}
			if c.Exp != tt.wantExp {
				t.Errorf("Exp = %d, want %d", c.Exp, tt.wantExp)
			}
			if c.SP != tt.wantSP {
				t.Errorf("SP = %d, want %d", c.SP, tt.wantSP)
			}
			res := c.ResourceValues()
			if res.MaxHP != tt.wantMaxHP || res.CurrentHP != tt.wantMaxHP {
				t.Errorf("MaxHP/CurHP = %v/%v, want %v", res.MaxHP, res.CurrentHP, tt.wantMaxHP)
			}
			if res.MaxMP != tt.wantMaxMP || res.CurrentMP != tt.wantMaxMP {
				t.Errorf("MaxMP/CurMP = %v/%v, want %v", res.MaxMP, res.CurrentMP, tt.wantMaxMP)
			}
			if res.MaxCP != tt.wantMaxCP || res.CurrentCP != tt.wantMaxCP {
				t.Errorf("MaxCP/CurCP = %v/%v, want %v", res.MaxCP, res.CurrentCP, tt.wantMaxCP)
			}
		})
	}
}

// TestCharacter_AddSp_Saturates matches the reference SP accumulator's
// 32-bit signed integer ceiling.
func TestCharacter_AddSp_Saturates(t *testing.T) {
	c := newProgressionCharacter()
	c.SP = maxSP - 5

	c.AddSp(100)

	if c.SP != maxSP {
		t.Errorf("SP = %d, want %d", c.SP, maxSP)
	}
}

// TestCharacter_AddExp_OverflowGuard matches the reference accumulator's
// no-op behavior when an addition would overflow experience negative.
func TestCharacter_AddExp_OverflowGuard(t *testing.T) {
	table := realLevelTable(t)
	tmpl := levelStepTemplate(81)

	c := newProgressionCharacter()
	c.CharLevel = 80
	c.Exp = 6000000000

	leveled := c.AddExp(table, tmpl, 1<<63-1)

	if leveled {
		t.Errorf("AddExp() leveled = true, want false (overflow no-op)")
	}
	if c.Exp != 6000000000 {
		t.Errorf("Exp = %d, want unchanged 6000000000", c.Exp)
	}
	if c.CharLevel != 80 {
		t.Errorf("Level = %d, want unchanged 80", c.CharLevel)
	}
}

// TestCharacter_RemoveExpAndSp compares Go's exp/sp/level removal against
// values generated by running the reference removeExp/removeSp/addLevel
// logic against the shipped player level table.
func TestCharacter_RemoveExpAndSp(t *testing.T) {
	table := realLevelTable(t)
	tmpl := levelStepTemplate(81)

	t.Run("removing exp delevels and does not refill HP/MP/CP", func(t *testing.T) {
		c := newProgressionCharacter()
		c.AddExpAndSp(table, tmpl, 363, 0) // level 3, exp 363, HP/MP/CP at level 3's row

		c.RemoveExpAndSp(table, tmpl, 300, 0) // exp -> 63, under level 2's 68 threshold

		if c.CharLevel != 1 {
			t.Errorf("Level = %d, want 1", c.CharLevel)
		}
		if c.Exp != 63 {
			t.Errorf("Exp = %d, want 63", c.Exp)
		}
		// A delevel never refills HP/MP/CP: the level-3 row values persist.
		res := c.ResourceValues()
		if res.MaxHP != 120 || res.MaxMP != 60 || res.MaxCP != 24 {
			t.Errorf("MaxHP/MP/CP = %v/%v/%v, want 120/60/24 (unrefilled)", res.MaxHP, res.MaxMP, res.MaxCP)
		}
	})

	t.Run("removing more exp than held floors at 1, not 0", func(t *testing.T) {
		c := newProgressionCharacter()
		c.AddExpAndSp(table, tmpl, 50, 0)

		c.RemoveExpAndSp(table, tmpl, 1000, 0)

		if c.Exp != 1 {
			t.Errorf("Exp = %d, want 1", c.Exp)
		}
		if c.CharLevel != 1 {
			t.Errorf("Level = %d, want 1", c.CharLevel)
		}
	})

	t.Run("removing more sp than held floors at 0", func(t *testing.T) {
		c := newProgressionCharacter()
		c.AddExpAndSp(table, tmpl, 0, 30)

		c.RemoveExpAndSp(table, tmpl, 0, 100)

		if c.SP != 0 {
			t.Errorf("SP = %d, want 0", c.SP)
		}
	})
}

// TestCharacter_AddLevel_RefusesPastRealMax matches the reference
// behavior: attempting to add a level past the level table's real max
// leaves the character entirely untouched instead of clamping.
func TestCharacter_AddLevel_RefusesPastRealMax(t *testing.T) {
	table := realLevelTable(t)
	tmpl := levelStepTemplate(81)

	c := newProgressionCharacter()
	c.CharLevel = table.RealMaxLevel()
	c.Exp = table.RequiredExpForLevel(table.RealMaxLevel())

	leveled := c.AddLevel(table, tmpl, 1)

	if leveled {
		t.Errorf("AddLevel() = true, want false at the real max level")
	}
	if c.CharLevel != table.RealMaxLevel() {
		t.Errorf("Level = %d, want unchanged %d", c.CharLevel, table.RealMaxLevel())
	}
}

// TestCharacter_AddLevel_Direct exercises AddLevel outside the
// exp-accumulation path (e.g. a level granted directly rather than earned
// through experience).
func TestCharacter_AddLevel_Direct(t *testing.T) {
	table := realLevelTable(t)
	tmpl := levelStepTemplate(81)

	c := newProgressionCharacter()
	leveled := c.AddLevel(table, tmpl, 1)

	if !leveled {
		t.Fatal("AddLevel(+1) from level 1: want leveled up")
	}
	if c.CharLevel != 2 {
		t.Errorf("Level = %d, want 2", c.CharLevel)
	}
	if c.Exp != 68 {
		t.Errorf("Exp = %d, want 68 (resynced to level 2's threshold)", c.Exp)
	}
	res := c.ResourceValues()
	if res.MaxHP != 110 || res.MaxMP != 55 || res.MaxCP != 22 {
		t.Errorf("MaxHP/MP/CP = %v/%v/%v, want 110/55/22", res.MaxHP, res.MaxMP, res.MaxCP)
	}
}

// TestCharacter_AddLevel_NilTemplateSkipsRefill covers the case where a
// caller doesn't have (or need) the profession template on hand: the level
// and experience still update, but HP/MP/CP are left alone.
func TestCharacter_AddLevel_NilTemplateSkipsRefill(t *testing.T) {
	table := realLevelTable(t)

	c := newProgressionCharacter()
	leveled := c.AddLevel(table, nil, 1)

	if !leveled {
		t.Fatal("AddLevel(+1) with nil template: want leveled up")
	}
	if c.CharLevel != 2 {
		t.Errorf("Level = %d, want 2", c.CharLevel)
	}
	if res := c.ResourceValues(); res.MaxHP != 100 {
		t.Errorf("MaxHP = %v, want unchanged 100 (no template to resync from)", res.MaxHP)
	}
}

func TestLevelTable_RequiredExpForLevel(t *testing.T) {
	table := realLevelTable(t)

	if got := table.RequiredExpForLevel(3); got != 363 {
		t.Errorf("RequiredExpForLevel(3) = %d, want 363", got)
	}
	if got := table.RequiredExpForLevel(9999); got != 0 {
		t.Errorf("RequiredExpForLevel(9999) = %d, want 0 (absent entry)", got)
	}
}

func TestLevelTable_ExpSpanAtLevel(t *testing.T) {
	table := realLevelTable(t)

	if got, want := table.ExpSpanAtLevel(1), int64(68); got != want {
		t.Errorf("ExpSpanAtLevel(1) = %d, want %d", got, want)
	}
	// At/above the level cap, the span falls back to the top band's width
	// (level 80 to level 81's threshold).
	wantTopSpan := realPlayerLevelExp[80] - realPlayerLevelExp[79]
	if got := table.ExpSpanAtLevel(table.RealMaxLevel()); got != wantTopSpan {
		t.Errorf("ExpSpanAtLevel(realMaxLevel) = %d, want %d", got, wantTopSpan)
	}
	if got := table.ExpSpanAtLevel(table.MaxLevel()); got != wantTopSpan {
		t.Errorf("ExpSpanAtLevel(maxLevel) = %d, want %d", got, wantTopSpan)
	}
}

// TestAddExpAndSpNotifiesGain pins the reward message an addition owes the
// player. The hook fires once per attempt that was not fully rejected —
// including one adding nothing — and carries the raw requested amounts, which
// are what the message reports.
func TestAddExpAndSpNotifiesGain(t *testing.T) {
	table := realLevelTable(t)
	tmpl := levelStepTemplate(81)

	type gain struct {
		exp int64
		sp  int
	}
	tests := []struct {
		name string
		exp  int64
		sp   int
		want []gain
	}{
		{name: "experience only", exp: 100, sp: 0, want: []gain{{100, 0}}},
		{name: "sp only", exp: 0, sp: 25, want: []gain{{0, 25}}},
		{name: "both", exp: 100, sp: 25, want: []gain{{100, 25}}},
		{name: "neither", exp: 0, sp: 0, want: []gain{{0, 0}}},
		{name: "both rejected", exp: -1, sp: -1, want: nil},
		{name: "experience rejected", exp: -1, sp: 25, want: []gain{{-1, 25}}},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			c := newProgressionCharacter()
			var got []gain
			c.SetExpSpGainNotifier(func(exp int64, sp int) {
				got = append(got, gain{exp, sp})
			})
			c.AddExpAndSp(table, tmpl, tc.exp, tc.sp)
			if len(got) != len(tc.want) {
				t.Fatalf("gain notifications = %v, want %v", got, tc.want)
			}
			for i, want := range tc.want {
				if got[i] != want {
					t.Errorf("gain notification %d = %v, want %v", i, got[i], want)
				}
			}
		})
	}
}

// TestAddExpAndSpNotifiesGainAtSPCeiling pins the one case where an addition
// stays silent despite a non-negative SP amount: SP already at the ceiling
// with no experience added leaves nothing to report.
func TestAddExpAndSpNotifiesGainAtSPCeiling(t *testing.T) {
	table := realLevelTable(t)
	tmpl := levelStepTemplate(81)

	c := newProgressionCharacter()
	c.SP = maxSP
	notifications := 0
	c.SetExpSpGainNotifier(func(int64, int) { notifications++ })
	c.AddExpAndSp(table, tmpl, -1, 25)
	if notifications != 0 {
		t.Errorf("gain notifications = %d, want 0", notifications)
	}
}

// TestRewardExpAndSpNotifiesGain covers the table-less reward fallback, which
// applies SP only and must still report it.
func TestRewardExpAndSpNotifiesGain(t *testing.T) {
	c := newProgressionCharacter()
	var got []int
	c.SetExpSpGainNotifier(func(exp int64, sp int) {
		if exp != 0 {
			t.Errorf("gain notification exp = %d, want 0", exp)
		}
		got = append(got, sp)
	})
	c.RewardExpAndSp(nil, 100, 25)
	if len(got) != 1 || got[0] != 25 {
		t.Errorf("gain notifications = %v, want [25]", got)
	}
}

// TestAddLevelBroadcastsLevelUp pins the level-up animation and message: they
// belong to an actual increase, never to a level drop.
func TestAddLevelBroadcastsLevelUp(t *testing.T) {
	table := realLevelTable(t)
	tmpl := levelStepTemplate(81)

	t.Run("increase", func(t *testing.T) {
		c := newProgressionCharacter()
		broadcasts := 0
		c.SetLevelUpBroadcaster(func() { broadcasts++ })
		if !c.AddLevel(table, tmpl, 1) {
			t.Fatal("AddLevel(1) = false, want true")
		}
		if broadcasts != 1 {
			t.Errorf("level-up broadcasts = %d, want 1", broadcasts)
		}
	})

	t.Run("decrease", func(t *testing.T) {
		c := newProgressionCharacter()
		c.AddLevel(table, tmpl, 5)
		broadcasts := 0
		c.SetLevelUpBroadcaster(func() { broadcasts++ })
		if c.AddLevel(table, tmpl, -1) {
			t.Fatal("AddLevel(-1) = true, want false")
		}
		if broadcasts != 0 {
			t.Errorf("level-up broadcasts = %d, want 0", broadcasts)
		}
	})
}

// TestRemoveExpAndSpNotifiesLoss pins the decrease messages and the status
// broadcast a level-dropping removal owes nearby clients.
func TestRemoveExpAndSpNotifiesLoss(t *testing.T) {
	table := realLevelTable(t)
	tmpl := levelStepTemplate(81)

	t.Run("without level drop", func(t *testing.T) {
		c := newProgressionCharacter()
		c.AddExpAndSp(table, tmpl, table.RequiredExpForLevel(10)+1000, 1000)
		var lost [][2]int64
		broadcasts := 0
		c.SetExpSpLossNotifier(func(exp int64, sp int) {
			lost = append(lost, [2]int64{exp, int64(sp)})
		})
		c.SetStatusBroadcaster(func() { broadcasts++ })
		c.RemoveExpAndSp(table, tmpl, 10, 25)
		if len(lost) != 1 || lost[0] != [2]int64{10, 25} {
			t.Errorf("loss notifications = %v, want [[10 25]]", lost)
		}
		if broadcasts != 0 {
			t.Errorf("status broadcasts = %d, want 0", broadcasts)
		}
	})

	t.Run("with level drop", func(t *testing.T) {
		c := newProgressionCharacter()
		c.AddExpAndSp(table, tmpl, table.RequiredExpForLevel(10), 1000)
		before := c.CharLevel
		notifications, broadcasts := 0, 0
		c.SetExpSpLossNotifier(func(int64, int) { notifications++ })
		c.SetStatusBroadcaster(func() { broadcasts++ })
		c.RemoveExpAndSp(table, tmpl, c.Exp, 0)
		if c.CharLevel >= before {
			t.Fatalf("CharLevel = %d, want below %d", c.CharLevel, before)
		}
		if notifications != 1 {
			t.Errorf("loss notifications = %d, want 1", notifications)
		}
		if broadcasts != 1 {
			t.Errorf("status broadcasts = %d, want 1", broadcasts)
		}
	})

	t.Run("nothing removed", func(t *testing.T) {
		c := newProgressionCharacter()
		notifications := 0
		c.SetExpSpLossNotifier(func(int64, int) { notifications++ })
		c.RemoveExpAndSp(table, tmpl, 0, 0)
		if notifications != 0 {
			t.Errorf("loss notifications = %d, want 0", notifications)
		}
	})
}

// TestRewardExpAndSpUpdatesUserInfo pins the client notification a kill
// reward owes the player: without it the client keeps showing the
// experience, SP and level it was last told about.
func TestRewardExpAndSpUpdatesUserInfo(t *testing.T) {
	table := realLevelTable(t)

	t.Run("with level table", func(t *testing.T) {
		c := newProgressionCharacter()
		updates := 0
		c.SetUserInfoUpdater(func() { updates++ })
		c.RewardExpAndSp(table, 100, 10)
		if updates != 1 {
			t.Errorf("UserInfo updates = %d, want 1", updates)
		}
	})

	t.Run("without level table", func(t *testing.T) {
		c := newProgressionCharacter()
		updates := 0
		c.SetUserInfoUpdater(func() { updates++ })
		c.RewardExpAndSp(nil, 100, 10)
		if updates != 1 {
			t.Errorf("UserInfo updates = %d, want 1", updates)
		}
	})
}
