package player

import (
	"fmt"
	"slices"
	"sort"
	"testing"

	"github.com/fatal10110/acis_golang/internal/gameserver/model/actor/event"
	"github.com/fatal10110/acis_golang/internal/gameserver/skill/effect"
	"github.com/fatal10110/acis_golang/internal/gameserver/skill/stat"
)

// ---- from level_test.go ----
func TestLevelTable_Levels(t *testing.T) {
	table, err := NewLevelTable(map[int]Level{
		3: {RequiredExpToLevelUp: 300},
		1: {RequiredExpToLevelUp: 100},
		2: {RequiredExpToLevelUp: 200},
	})
	if err != nil {
		t.Fatalf("NewLevelTable() error: %v", err)
	}

	levels := table.Levels()
	if len(levels) != table.Count() {
		t.Fatalf("Levels() returned %d entries, Count() = %d", len(levels), table.Count())
	}
	if !sort.IntsAreSorted(levels) {
		t.Fatalf("Levels() not sorted ascending: %v", levels)
	}
	if want := []int{1, 2, 3}; !equalInts(levels, want) {
		t.Fatalf("Levels() = %v, want %v", levels, want)
	}
}

// levelStepTemplate returns a template whose HP/MP/CP tables carry a
// distinct, easily recognizable value per level, so a test can assert
// which table row a level-up resync picked up.
func levelStepTemplate(levels int) *Template {
	hp := make([]float64, levels)
	mp := make([]float64, levels)
	cp := make([]float64, levels)
	for i := 0; i < levels; i++ {
		hp[i] = 100 + float64(i)*10
		mp[i] = 50 + float64(i)*5
		cp[i] = 20 + float64(i)*2
	}
	return &Template{HPTable: hp, MPTable: mp, CPTable: cp}
}

func newProgressionCharacter() *Character {
	tmpl := levelStepTemplate(81)
	c := &Character{
		CharLevel: 1,
	}
	c.SetResourceValues(Resources{
		MaxHP: tmpl.HPTable[0], CurrentHP: tmpl.HPTable[0],
		MaxMP: tmpl.MPTable[0], CurrentMP: tmpl.MPTable[0],
		MaxCP: tmpl.CPTable[0], CurrentCP: tmpl.CPTable[0],
	})
	return c
}

// TestCharacter_AddExpAndSp compares Go's exp/sp/level accumulation
// against expected values generated by running the reference
// exp/sp/level-progression logic (PlayableStatus/PlayerStatus's addExp,
// addLevel, addSp) against the shipped player level table.
func TestCharacter_AddExpAndSp(t *testing.T) {
	table := realLevelTable(t)
	tmpl := levelStepTemplate(81)

	tests := []struct {
		name        string
		exp         int64
		sp          int
		wantLevel   int
		wantExp     int64
		wantSP      int
		wantLeveled bool
		wantMaxHP   float64
		wantMaxMP   float64
		wantMaxCP   float64
	}{
		{
			name: "small exp below next threshold stays at level 1", exp: 50, sp: 0,
			wantLevel: 1, wantExp: 50, wantSP: 0, wantLeveled: false,
			wantMaxHP: 100, wantMaxMP: 50, wantMaxCP: 20,
		},
		{
			name: "exp exactly at level 2 threshold levels up", exp: 68, sp: 0,
			wantLevel: 2, wantExp: 68, wantSP: 0, wantLeveled: true,
			wantMaxHP: 110, wantMaxMP: 55, wantMaxCP: 22,
		},
		{
			name: "multi-level jump from 1 to 5", exp: 2884, sp: 0,
			wantLevel: 5, wantExp: 2884, wantSP: 0, wantLeveled: true,
			wantMaxHP: 140, wantMaxMP: 70, wantMaxCP: 28,
		},
		{
			name: "sp only, no exp added", exp: 0, sp: 500,
			wantLevel: 1, wantExp: 0, wantSP: 500, wantLeveled: false,
			wantMaxHP: 100, wantMaxMP: 50, wantMaxCP: 20,
		},
		{
			name: "exp and sp together crossing into level 3", exp: 363, sp: 1200,
			wantLevel: 3, wantExp: 363, wantSP: 1200, wantLeveled: true,
			wantMaxHP: 120, wantMaxMP: 60, wantMaxCP: 24,
		},
		{
			name: "huge exp caps just below the highest level's band", exp: 4611686018427387903, sp: 0,
			wantLevel: 80, wantExp: 6299994998, wantSP: 0, wantLeveled: true,
			wantMaxHP: 890, wantMaxMP: 445, wantMaxCP: 178,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			c := newProgressionCharacter()
			leveled := c.AddExpAndSpWith(table, tmpl, tt.exp, tt.sp)

			if leveled != tt.wantLeveled {
				t.Errorf("AddExpAndSpWith() leveled = %v, want %v", leveled, tt.wantLeveled)
			}
			if c.CharLevel != tt.wantLevel {
				t.Errorf("Level = %d, want %d", c.CharLevel, tt.wantLevel)
			}
			if c.Exp != tt.wantExp {
				t.Errorf("Exp = %d, want %d", c.Exp, tt.wantExp)
			}
			if c.SP != tt.wantSP {
				t.Errorf("SP = %d, want %d", c.SP, tt.wantSP)
			}
			res := c.ResourceValues()
			if res.MaxHP != tt.wantMaxHP || res.CurrentHP != tt.wantMaxHP {
				t.Errorf("MaxHP/CurHP = %v/%v, want %v", res.MaxHP, res.CurrentHP, tt.wantMaxHP)
			}
			if res.MaxMP != tt.wantMaxMP || res.CurrentMP != tt.wantMaxMP {
				t.Errorf("MaxMP/CurMP = %v/%v, want %v", res.MaxMP, res.CurrentMP, tt.wantMaxMP)
			}
			if res.MaxCP != tt.wantMaxCP || res.CurrentCP != tt.wantMaxCP {
				t.Errorf("MaxCP/CurCP = %v/%v, want %v", res.MaxCP, res.CurrentCP, tt.wantMaxCP)
			}
		})
	}
}

// TestCharacter_AddSp_Saturates matches the reference SP accumulator's
// 32-bit signed integer ceiling.
func TestCharacter_AddSp_Saturates(t *testing.T) {
	c := newProgressionCharacter()
	c.SP = maxSP - 5

	c.AddSp(100)

	if c.SP != maxSP {
		t.Errorf("SP = %d, want %d", c.SP, maxSP)
	}
}

// TestCharacter_AddExp_OverflowGuard matches the reference accumulator's
// no-op behavior when an addition would overflow experience negative.
func TestCharacter_AddExp_OverflowGuard(t *testing.T) {
	table := realLevelTable(t)
	tmpl := levelStepTemplate(81)

	c := newProgressionCharacter()
	c.CharLevel = 80
	c.Exp = 6000000000

	leveled := c.AddExp(table, tmpl, 1<<63-1)

	if leveled {
		t.Errorf("AddExp() leveled = true, want false (overflow no-op)")
	}
	if c.Exp != 6000000000 {
		t.Errorf("Exp = %d, want unchanged 6000000000", c.Exp)
	}
	if c.CharLevel != 80 {
		t.Errorf("Level = %d, want unchanged 80", c.CharLevel)
	}
}

// TestCharacter_RemoveExpAndSp compares Go's exp/sp/level removal against
// values generated by running the reference removeExp/removeSp/addLevel
// logic against the shipped player level table.
func TestCharacter_RemoveExpAndSp(t *testing.T) {
	table := realLevelTable(t)
	tmpl := levelStepTemplate(81)

	t.Run("removing exp delevels and does not refill HP/MP/CP", func(t *testing.T) {
		c := newProgressionCharacter()
		c.AddExpAndSpWith(table, tmpl, 363, 0) // level 3, exp 363, HP/MP/CP at level 3's row

		c.RemoveExpAndSp(table, tmpl, 300, 0) // exp -> 63, under level 2's 68 threshold

		if c.CharLevel != 1 {
			t.Errorf("Level = %d, want 1", c.CharLevel)
		}
		if c.Exp != 63 {
			t.Errorf("Exp = %d, want 63", c.Exp)
		}
		// A delevel never refills HP/MP/CP: the level-3 row values persist.
		res := c.ResourceValues()
		if res.MaxHP != 120 || res.MaxMP != 60 || res.MaxCP != 24 {
			t.Errorf("MaxHP/MP/CP = %v/%v/%v, want 120/60/24 (unrefilled)", res.MaxHP, res.MaxMP, res.MaxCP)
		}
	})

	t.Run("removing more exp than held floors at 1, not 0", func(t *testing.T) {
		c := newProgressionCharacter()
		c.AddExpAndSpWith(table, tmpl, 50, 0)

		c.RemoveExpAndSp(table, tmpl, 1000, 0)

		if c.Exp != 1 {
			t.Errorf("Exp = %d, want 1", c.Exp)
		}
		if c.CharLevel != 1 {
			t.Errorf("Level = %d, want 1", c.CharLevel)
		}
	})

	t.Run("removing more sp than held floors at 0", func(t *testing.T) {
		c := newProgressionCharacter()
		c.AddExpAndSpWith(table, tmpl, 0, 30)

		c.RemoveExpAndSp(table, tmpl, 0, 100)

		if c.SP != 0 {
			t.Errorf("SP = %d, want 0", c.SP)
		}
	})
}

// TestCharacter_AddLevel_RefusesPastRealMax matches the reference
// behavior: attempting to add a level past the level table's real max
// leaves the character entirely untouched instead of clamping.
func TestCharacter_AddLevel_RefusesPastRealMax(t *testing.T) {
	table := realLevelTable(t)
	tmpl := levelStepTemplate(81)

	c := newProgressionCharacter()
	c.CharLevel = table.RealMaxLevel()
	c.Exp = table.RequiredExpForLevel(table.RealMaxLevel())

	leveled := c.AddLevel(table, tmpl, 1)

	if leveled {
		t.Errorf("AddLevel() = true, want false at the real max level")
	}
	if c.CharLevel != table.RealMaxLevel() {
		t.Errorf("Level = %d, want unchanged %d", c.CharLevel, table.RealMaxLevel())
	}
}

// TestCharacter_AddLevel_Direct exercises AddLevel outside the
// exp-accumulation path (e.g. a level granted directly rather than earned
// through experience).
func TestCharacter_AddLevel_Direct(t *testing.T) {
	table := realLevelTable(t)
	tmpl := levelStepTemplate(81)

	c := newProgressionCharacter()
	leveled := c.AddLevel(table, tmpl, 1)

	if !leveled {
		t.Fatal("AddLevel(+1) from level 1: want leveled up")
	}
	if c.CharLevel != 2 {
		t.Errorf("Level = %d, want 2", c.CharLevel)
	}
	if c.Exp != 68 {
		t.Errorf("Exp = %d, want 68 (resynced to level 2's threshold)", c.Exp)
	}
	res := c.ResourceValues()
	if res.MaxHP != 110 || res.MaxMP != 55 || res.MaxCP != 22 {
		t.Errorf("MaxHP/MP/CP = %v/%v/%v, want 110/55/22", res.MaxHP, res.MaxMP, res.MaxCP)
	}
}

func TestCharacter_AddLevel_RefillsStatCalculatedVitals(t *testing.T) {
	table := realLevelTable(t)
	tmpl := levelStepTemplate(81)
	c := newProgressionCharacter()
	c.AttachRuntime(tmpl, nil)
	c.AddStatFuncs([]effect.Mod{
		{Stat: stat.MaxHP, Op: effect.OpMul, Value: 2, Owner: testModOwner()},
		{Stat: stat.MaxMP, Op: effect.OpMul, Value: 2, Owner: testModOwner()},
		{Stat: stat.MaxCP, Op: effect.OpMul, Value: 2, Owner: testModOwner()},
	})

	c.AddLevel(table, tmpl, 1)

	if got := c.ResourceValues(); got.CurrentHP != got.MaxHP || got.CurrentMP != got.MaxMP || got.CurrentCP != got.MaxCP {
		t.Fatalf("ResourceValues() after stat-modified level-up = %+v, want every current value at its stat-calculated max", got)
	}
}

// TestCharacter_AddLevel_NilTemplateSkipsRefill covers the case where a
// caller doesn't have (or need) the profession template on hand: the level
// and experience still update, but HP/MP/CP are left alone.
func TestCharacter_AddLevel_NilTemplateSkipsRefill(t *testing.T) {
	table := realLevelTable(t)

	c := newProgressionCharacter()
	leveled := c.AddLevel(table, nil, 1)

	if !leveled {
		t.Fatal("AddLevel(+1) with nil template: want leveled up")
	}
	if c.CharLevel != 2 {
		t.Errorf("Level = %d, want 2", c.CharLevel)
	}
	if res := c.ResourceValues(); res.MaxHP != 100 {
		t.Errorf("MaxHP = %v, want unchanged 100 (no template to resync from)", res.MaxHP)
	}
}

func TestLevelTable_RequiredExpForLevel(t *testing.T) {
	table := realLevelTable(t)

	if got := table.RequiredExpForLevel(3); got != 363 {
		t.Errorf("RequiredExpForLevel(3) = %d, want 363", got)
	}
	if got := table.RequiredExpForLevel(9999); got != 0 {
		t.Errorf("RequiredExpForLevel(9999) = %d, want 0 (absent entry)", got)
	}
}

func TestLevelTable_ExpSpanAtLevel(t *testing.T) {
	table := realLevelTable(t)

	if got, want := table.ExpSpanAtLevel(1), int64(68); got != want {
		t.Errorf("ExpSpanAtLevel(1) = %d, want %d", got, want)
	}
	// At/above the level cap, the span falls back to the top band's width
	// (level 80 to level 81's threshold).
	wantTopSpan := realPlayerLevelExp[80] - realPlayerLevelExp[79]
	if got := table.ExpSpanAtLevel(table.RealMaxLevel()); got != wantTopSpan {
		t.Errorf("ExpSpanAtLevel(realMaxLevel) = %d, want %d", got, wantTopSpan)
	}
	if got := table.ExpSpanAtLevel(table.MaxLevel()); got != wantTopSpan {
		t.Errorf("ExpSpanAtLevel(maxLevel) = %d, want %d", got, wantTopSpan)
	}
}

// TestAddExpAndSpNotifiesGain pins the reward message an addition owes the
// player. The hook fires once per attempt that was not fully rejected —
// including one adding nothing — and carries the raw requested amounts, which
// are what the message reports.
func TestAddExpAndSpNotifiesGain(t *testing.T) {
	table := realLevelTable(t)
	tmpl := levelStepTemplate(81)

	type gain struct {
		exp int64
		sp  int
	}
	tests := []struct {
		name string
		exp  int64
		sp   int
		want []gain
	}{
		{name: "experience only", exp: 100, sp: 0, want: []gain{{100, 0}}},
		{name: "sp only", exp: 0, sp: 25, want: []gain{{0, 25}}},
		{name: "both", exp: 100, sp: 25, want: []gain{{100, 25}}},
		{name: "neither", exp: 0, sp: 0, want: []gain{{0, 0}}},
		{name: "both rejected", exp: -1, sp: -1, want: nil},
		{name: "experience rejected", exp: -1, sp: 25, want: []gain{{-1, 25}}},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			c := newProgressionCharacter()
			rec := recordEvents(c)
			c.AddExpAndSpWith(table, tmpl, tc.exp, tc.sp)
			var got []gain
			for _, e := range event.Of[event.ExpSPGained](rec) {
				got = append(got, gain{e.Exp, e.SP})
			}
			if len(got) != len(tc.want) {
				t.Fatalf("gain notifications = %v, want %v", got, tc.want)
			}
			for i, want := range tc.want {
				if got[i] != want {
					t.Errorf("gain notification %d = %v, want %v", i, got[i], want)
				}
			}
		})
	}
}

// TestAddExpAndSpNotifiesGainAtSPCeiling pins the one case where an addition
// stays silent despite a non-negative SP amount: SP already at the ceiling
// with no experience added leaves nothing to report.
func TestAddExpAndSpNotifiesGainAtSPCeiling(t *testing.T) {
	table := realLevelTable(t)
	tmpl := levelStepTemplate(81)

	c := newProgressionCharacter()
	c.SP = maxSP
	rec := recordEvents(c)
	c.AddExpAndSpWith(table, tmpl, -1, 25)
	if notifications := event.Count[event.ExpSPGained](rec); notifications != 0 {
		t.Errorf("gain notifications = %d, want 0", notifications)
	}
}

// TestRewardExpAndSpNotifiesGain covers the table-less reward fallback, which
// applies SP only and must still report it.
func TestRewardExpAndSpNotifiesGain(t *testing.T) {
	c := newProgressionCharacter()
	rec := recordEvents(c)
	c.RewardExpAndSp(nil, 100, 25)
	var got []int
	for _, e := range event.Of[event.ExpSPGained](rec) {
		if e.Exp != 0 {
			t.Errorf("gain notification exp = %d, want 0", e.Exp)
		}
		got = append(got, e.SP)
	}
	if len(got) != 1 || got[0] != 25 {
		t.Errorf("gain notifications = %v, want [25]", got)
	}
}

// TestAddLevelBroadcastsLevelUp pins the level-up animation and message: they
// belong to an actual increase, never to a level drop.
func TestAddLevelBroadcastsLevelUp(t *testing.T) {
	table := realLevelTable(t)
	tmpl := levelStepTemplate(81)

	t.Run("increase", func(t *testing.T) {
		c := newProgressionCharacter()
		rec := recordEvents(c)
		if !c.AddLevel(table, tmpl, 1) {
			t.Fatal("AddLevel(1) = false, want true")
		}
		if broadcasts := event.Count[event.LeveledUp](rec); broadcasts != 1 {
			t.Errorf("level-up broadcasts = %d, want 1", broadcasts)
		}
	})

	t.Run("decrease", func(t *testing.T) {
		c := newProgressionCharacter()
		c.AddLevel(table, tmpl, 5)
		rec := recordEvents(c)
		if c.AddLevel(table, tmpl, -1) {
			t.Fatal("AddLevel(-1) = true, want false")
		}
		if broadcasts := event.Count[event.LeveledUp](rec); broadcasts != 0 {
			t.Errorf("level-up broadcasts = %d, want 0", broadcasts)
		}
	})
}

// TestAddLevelRefreshesLevelEntitlements pins the refresh a level change
// owes: what a level entitles a character to is re-derived, so a drop has to
// run the same refresh a gain does, and the UserInfo that follows has to
// describe the already-refreshed character.
func TestAddLevelRefreshesLevelEntitlements(t *testing.T) {
	table := realLevelTable(t)
	tmpl := levelStepTemplate(81)

	for _, tc := range []struct {
		name  string
		delta int
	}{
		{"increase", 1},
		{"decrease", -1},
	} {
		t.Run(tc.name, func(t *testing.T) {
			c := newProgressionCharacter()
			c.AddLevel(table, tmpl, 20)

			rec := recordEvents(c)

			c.AddLevel(table, tmpl, tc.delta)
			var order []string
			for _, e := range rec.Events() {
				switch e.(type) {
				case event.LevelChanged:
					order = append(order, "refresh")
				case event.UserInfoChanged:
					order = append(order, "userinfo")
				}
			}
			if want := []string{"refresh", "userinfo"}; !slices.Equal(order, want) {
				t.Errorf("hook calls = %v, want %v", order, want)
			}
		})
	}

	// A refused change — one that would push past the real max level —
	// leaves the character alone, so it owes neither hook.
	t.Run("refused", func(t *testing.T) {
		c := newProgressionCharacter()
		rec := recordEvents(c)
		if c.AddLevel(table, tmpl, table.RealMaxLevel()+1) {
			t.Fatal("AddLevel past the real max reported an increase")
		}
		if refreshes, updates := event.Count[event.LevelChanged](rec), event.Count[event.UserInfoChanged](rec); refreshes != 0 || updates != 0 {
			t.Errorf("refreshes = %d, UserInfo updates = %d, want 0 and 0", refreshes, updates)
		}
	})
}

// TestRemoveExpAndSpNotifiesLoss pins the decrease messages and the status
// broadcast a level-dropping removal owes nearby clients.
func TestRemoveExpAndSpNotifiesLoss(t *testing.T) {
	table := realLevelTable(t)
	tmpl := levelStepTemplate(81)

	t.Run("without level drop", func(t *testing.T) {
		c := newProgressionCharacter()
		c.AddExpAndSpWith(table, tmpl, table.RequiredExpForLevel(10)+1000, 1000)
		rec := recordEvents(c)
		c.RemoveExpAndSp(table, tmpl, 10, 25)
		if lost := event.Of[event.ExpSPLost](rec); len(lost) != 1 || lost[0] != (event.ExpSPLost{Exp: 10, SP: 25, SPLeft: 975}) {
			t.Errorf("loss notifications = %v, want [[10 25 975]]", lost)
		}
		if broadcasts := countVitals(rec); broadcasts != 0 {
			t.Errorf("status broadcasts = %d, want 0", broadcasts)
		}
	})

	t.Run("with level drop", func(t *testing.T) {
		c := newProgressionCharacter()
		c.AddExpAndSpWith(table, tmpl, table.RequiredExpForLevel(10), 1000)
		before := c.CharLevel
		rec := recordEvents(c)
		c.RemoveExpAndSp(table, tmpl, c.Exp, 0)
		notifications, broadcasts := event.Count[event.ExpSPLost](rec), countVitals(rec)
		if c.CharLevel >= before {
			t.Fatalf("CharLevel = %d, want below %d", c.CharLevel, before)
		}
		if notifications != 1 {
			t.Errorf("loss notifications = %d, want 1", notifications)
		}
		if broadcasts != 1 {
			t.Errorf("status broadcasts = %d, want 1", broadcasts)
		}
	})

	t.Run("nothing removed", func(t *testing.T) {
		c := newProgressionCharacter()
		rec := recordEvents(c)
		c.RemoveExpAndSp(table, tmpl, 0, 0)
		if notifications := event.Count[event.ExpSPLost](rec); notifications != 0 {
			t.Errorf("loss notifications = %d, want 0", notifications)
		}
	})
}

// TestRewardExpAndSpUpdatesUserInfo pins what an experience/SP add sends and
// in which order, including the adds that change nothing. The expected
// traces follow the reference path step by step:
//   - PlayableStatus.addExpAndSp (PlayableStatus.java:118-130) runs
//     addExp for exp >= 0, then addSp for sp >= 0;
//   - PlayerStatus.addExp (PlayerStatus.java:478-485) sends UserInfo whenever
//     PlayableStatus.addExp returns true, which it always does — a zero add
//     applies nothing, and one that would overflow returns true unapplied
//     (PlayableStatus.java:70-93); a level change inside it sends its own
//     UserInfo first (PlayerStatus.java:606-661);
//   - PlayableStatus.addSp (PlayableStatus.java:173-187) fails only with SP
//     at Integer.MAX_VALUE; otherwise it calls PlayerStatus.setSp
//     (PlayerStatus.java:881-891), which sends StatusUpdate(SP) with the new
//     total, even for a zero add;
//   - PlayerStatus.addExpAndSp (PlayerStatus.java:501-520) sends the reward
//     message when either add returned true.
func TestRewardExpAndSpUpdatesUserInfo(t *testing.T) {
	table := realLevelTable(t)
	atLevel10 := table.RequiredExpForLevel(10)
	capExp := table.RequiredExpForHighestLevel()

	tests := []struct {
		name     string
		table    *LevelTable
		startExp int64
		startSP  int
		addExp   int64
		addSP    int
		want     []string
	}{
		{
			name: "normal reward", table: table, startExp: atLevel10, startSP: 1000, addExp: 1, addSP: 10,
			want: []string{"userinfo", "sp 1010", "gain 1/10"},
		},
		{
			name: "zero reward", table: table, startExp: atLevel10, startSP: 1000,
			want: []string{"userinfo", "sp 1000", "gain 0/0"},
		},
		{
			name: "sp at ceiling", table: table, startExp: atLevel10, startSP: maxSP, addSP: 5,
			want: []string{"userinfo", "gain 0/5"},
		},
		{
			name: "exp clamped to nothing at the cap", table: table, startExp: capExp - 1, startSP: 1000, addExp: 100,
			want: []string{"userinfo", "sp 1000", "gain 100/0"},
		},
		{
			name: "exp rejected", table: table, startExp: atLevel10, startSP: 1000, addExp: -1, addSP: 10,
			want: []string{"sp 1010", "gain -1/10"},
		},
		{name: "both rejected", table: table, startExp: atLevel10, startSP: 1000, addExp: -1, addSP: -1},
		{
			name: "level gained", table: table, startExp: atLevel10, startSP: 1000, addExp: table.RequiredExpForLevel(11) - atLevel10, addSP: 10,
			want: []string{"leveledup", "userinfo", "userinfo", "sp 1010", fmt.Sprintf("gain %d/10", table.RequiredExpForLevel(11)-atLevel10)},
		},
		{
			name: "without level table", startSP: 1000, addExp: 100, addSP: 10,
			want: []string{"userinfo", "sp 1010", "gain 0/10"},
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			c := newProgressionCharacter()
			c.Exp, c.SP = tc.startExp, tc.startSP
			if tc.table != nil {
				c.CharLevel = tc.table.levelForExp(tc.startExp)
			}
			rec := recordEvents(c)
			c.RewardExpAndSp(tc.table, tc.addExp, tc.addSP)
			if got := progressionTrace(rec); !slices.Equal(got, tc.want) {
				t.Fatalf("progression events = %v, want %v", got, tc.want)
			}
		})
	}
}

// userInfoSPSink records the SP a UserInfo built at each UserInfoChanged
// would carry.
type userInfoSPSink struct {
	c  *Character
	sp []int
}

func (s *userInfoSPSink) Emit(e event.Event) {
	if _, ok := e.(event.UserInfoChanged); ok {
		s.sp = append(s.sp, s.c.ProgressionValues().SP)
	}
}

// TestLevelUpUserInfoPrecedesSPGain pins the SP both UserInfos of a
// level-up reward carry: the level change's and the experience add's own are
// sent while the experience lands, before the SP add (PlayerStatus.addExp,
// then PlayableStatus.addSp), so both still show the old SP; the new total
// reaches the client in the StatusUpdate(SP) that follows.
func TestLevelUpUserInfoPrecedesSPGain(t *testing.T) {
	table := realLevelTable(t)
	c := newProgressionCharacter()
	sink := &userInfoSPSink{c: c}
	c.sink = sink

	c.AddExpAndSpWith(table, levelStepTemplate(81), table.RequiredExpForLevel(2), 40)

	if len(sink.sp) != 2 || sink.sp[0] != 0 || sink.sp[1] != 0 {
		t.Fatalf("UserInfo SP values = %v, want [0 0]", sink.sp)
	}
}
