package player

import "testing"

// Expected values were generated by running the reference server's kill
// reward formula (damage-share split, then the level-difference falloff)
// against these same inputs in a standalone probe, not derived by hand from
// the Go implementation under test.
func TestKillRewardExpAndSp(t *testing.T) {
	tests := []struct {
		name                string
		expReward, spReward float64
		levelDiff           int
		damage, totalDamage float64
		wantExp             int64
		wantSp              int
	}{
		{"level match, sole attacker", 1000, 100, 0, 100, 100, 1000, 100},
		{"attacker under-leveled, no bonus", 1000, 100, -3, 100, 100, 1000, 100},
		{"exactly at threshold, no falloff", 1000, 100, 5, 100, 100, 1000, 100},
		{"one level past threshold", 1000, 100, 6, 100, 100, 833, 83},
		{"two levels past threshold", 1000, 100, 7, 100, 100, 694, 69},
		{"five levels past threshold", 1000, 100, 10, 100, 100, 401, 40},
		{"fifteen levels past threshold", 1000, 100, 20, 100, 100, 64, 6},
		{"far past threshold, falls to zero", 1000, 100, 50, 100, 100, 0, 0},
		{"30% damage share", 5000, 500, 0, 30, 100, 1500, 150},
		{"25% damage share", 5000, 500, 0, 25, 100, 1250, 125},
		{"60% damage share with falloff", 5000, 500, 8, 60, 100, 1736, 173},
		{"uneven share and reward values", 12345, 6789, 3, 40, 137, 3604, 1982},
		{"zero reward template", 0, 0, 0, 100, 100, 0, 0},
		{"sp-only reward is zero, exp untouched", 1000, 0, 0, 100, 100, 1000, 0},
		{"exp-only reward is zero, sp zeroed with it", 0, 100, 0, 100, 100, 0, 0},
		{"tiny share far past threshold", 1000, 100, 100, 1, 1, 0, 0},
		{"large reward one level past threshold", 123456, 7654, 6, 999, 1000, 102777, 6371},
		{"exp just below int32 ceiling", 2147483646, 100, 0, 100, 100, 2147483646, 100},
		{"exp just above int32 ceiling saturates", 2147483648, 100, 0, 100, 100, 2147483647, 100},
		{"sp just above int32 ceiling saturates", 1000, 2147483648, 0, 100, 100, 1000, 2147483647},
		{"zero total damage yields no reward", 1000, 100, 0, 0, 0, 0, 0},
		{"negative total damage yields no reward", 1000, 100, 0, 0, -1, 0, 0},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			gotExp, gotSp := KillRewardExpAndSp(tt.expReward, tt.spReward, tt.damage, tt.totalDamage, tt.levelDiff)
			if gotExp != tt.wantExp || gotSp != tt.wantSp {
				t.Errorf("KillRewardExpAndSp(%v, %v, %v, %v, %v) = (%d, %d), want (%d, %d)",
					tt.expReward, tt.spReward, tt.damage, tt.totalDamage, tt.levelDiff,
					gotExp, gotSp, tt.wantExp, tt.wantSp)
			}
		})
	}
}

// TestKillRewardExpAndSp_FullShareMatchesTemplate documents the acceptance
// criterion that a sole attacker dealing all the damage, at or below the
// falloff threshold, receives the template's full reward.
func TestKillRewardExpAndSp_FullShareMatchesTemplate(t *testing.T) {
	exp, sp := KillRewardExpAndSp(4000, 250, 77, 77, 0)
	if exp != 4000 || sp != 250 {
		t.Errorf("got (%d, %d), want (4000, 250)", exp, sp)
	}
}
