package player

import (
	"sort"
	"testing"
)

// ---- from class_test.go ----
func TestClassLevel(t *testing.T) {
	tests := []struct {
		id        int
		wantLevel int
		wantOK    bool
	}{
		{id: 0, wantLevel: 0, wantOK: true},   // base
		{id: 1, wantLevel: 1, wantOK: true},   // first occupation change
		{id: 2, wantLevel: 2, wantOK: true},   // second occupation change
		{id: 88, wantLevel: 3, wantOK: true},  // third class
		{id: 118, wantLevel: 3, wantOK: true}, // third class, last id
		{id: 999, wantLevel: 0, wantOK: false},
		{id: 58, wantLevel: 0, wantOK: false}, // reserved gap
	}
	for _, tt := range tests {
		level, ok := ClassLevel(tt.id)
		if level != tt.wantLevel || ok != tt.wantOK {
			t.Errorf("ClassLevel(%d) = (%d, %v), want (%d, %v)", tt.id, level, ok, tt.wantLevel, tt.wantOK)
		}
	}
}

// ---- from race_test.go ----
func TestClassRace(t *testing.T) {
	tests := []struct {
		classID int
		want    Race
	}{
		{0, RaceHuman},    // Human Fighter (root)
		{9, RaceHuman},    // human fighter line, 2nd tier
		{93, RaceHuman},   // human fighter line, 3rd tier, multiple parent hops to root
		{10, RaceHuman},   // Human Mystic (root)
		{18, RaceElf},     // Elven Fighter (root)
		{25, RaceElf},     // Elven Mystic (root)
		{31, RaceDarkElf}, // Dark Fighter (root)
		{38, RaceDarkElf}, // Dark Mystic (root)
		{44, RaceOrc},     // Orc Fighter (root)
		{49, RaceOrc},     // Orc Mystic (root)
		{53, RaceDwarf},   // Dwarven Fighter (root)
		{57, RaceDwarf},   // Warsmith, dwarf line, 2nd tier
		{118, RaceDwarf},  // 3rd tier id parented under the dwarf line
	}
	for _, tt := range tests {
		got, ok := ClassRace(tt.classID)
		if !ok {
			t.Errorf("ClassRace(%d) reported unknown, want %v", tt.classID, tt.want)
			continue
		}
		if got != tt.want {
			t.Errorf("ClassRace(%d) = %v, want %v", tt.classID, got, tt.want)
		}
	}
}

func TestRaceBreathMultiplier(t *testing.T) {
	tests := map[Race]float64{
		RaceHuman:   1,
		RaceElf:     1.5,
		RaceDarkElf: 1.5,
		RaceOrc:     0.9,
		RaceDwarf:   0.8,
	}
	for race, want := range tests {
		if got := race.BreathMultiplier(); got != want {
			t.Errorf("%v BreathMultiplier() = %v, want %v", race, got, want)
		}
	}
}

func TestClassMage(t *testing.T) {
	for _, classID := range []int{10, 25, 38, 49, 94} {
		if !ClassMage(classID) {
			t.Errorf("ClassMage(%d) = false, want true", classID)
		}
	}
	for _, classID := range []int{0, 18, 31, 44, 53, 93} {
		if ClassMage(classID) {
			t.Errorf("ClassMage(%d) = true, want false", classID)
		}
	}
}

func TestClassRace_UnknownID(t *testing.T) {
	if _, ok := ClassRace(9999); ok {
		t.Error("ClassRace(9999) reported known, want unknown")
	}
	// 58-87 are reserved dummy ids with no profession behind them.
	if _, ok := ClassRace(70); ok {
		t.Error("ClassRace(70) reported known, want unknown")
	}
}

// ---- from reward_test.go ----
// Expected values were generated by running the reference server's kill
// reward formula (damage-share split, then the level-difference falloff)
// against these same inputs in a standalone probe, not derived by hand from
// the Go implementation under test.
func TestKillRewardExpAndSp(t *testing.T) {
	tests := []struct {
		name                string
		expReward, spReward float64
		levelDiff           int
		damage, totalDamage float64
		wantExp             int64
		wantSp              int
	}{
		{"level match, sole attacker", 1000, 100, 0, 100, 100, 1000, 100},
		{"attacker under-leveled, no bonus", 1000, 100, -3, 100, 100, 1000, 100},
		{"exactly at threshold, no falloff", 1000, 100, 5, 100, 100, 1000, 100},
		{"one level past threshold", 1000, 100, 6, 100, 100, 833, 83},
		{"two levels past threshold", 1000, 100, 7, 100, 100, 694, 69},
		{"five levels past threshold", 1000, 100, 10, 100, 100, 401, 40},
		{"fifteen levels past threshold", 1000, 100, 20, 100, 100, 64, 6},
		{"far past threshold, falls to zero", 1000, 100, 50, 100, 100, 0, 0},
		{"30% damage share", 5000, 500, 0, 30, 100, 1500, 150},
		{"25% damage share", 5000, 500, 0, 25, 100, 1250, 125},
		{"60% damage share with falloff", 5000, 500, 8, 60, 100, 1736, 173},
		{"uneven share and reward values", 12345, 6789, 3, 40, 137, 3604, 1982},
		{"zero reward template", 0, 0, 0, 100, 100, 0, 0},
		{"sp-only reward is zero, exp untouched", 1000, 0, 0, 100, 100, 1000, 0},
		{"exp-only reward is zero, sp zeroed with it", 0, 100, 0, 100, 100, 0, 0},
		{"tiny share far past threshold", 1000, 100, 100, 1, 1, 0, 0},
		{"large reward one level past threshold", 123456, 7654, 6, 999, 1000, 102777, 6371},
		{"exp just below int32 ceiling", 2147483646, 100, 0, 100, 100, 2147483646, 100},
		{"exp just above int32 ceiling saturates", 2147483648, 100, 0, 100, 100, 2147483647, 100},
		{"sp just above int32 ceiling saturates", 1000, 2147483648, 0, 100, 100, 1000, 2147483647},
		{"zero total damage yields no reward", 1000, 100, 0, 0, 0, 0, 0},
		{"negative total damage yields no reward", 1000, 100, 0, 0, -1, 0, 0},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			gotExp, gotSp := KillRewardExpAndSp(tt.expReward, tt.spReward, tt.damage, tt.totalDamage, tt.levelDiff)
			if gotExp != tt.wantExp || gotSp != tt.wantSp {
				t.Errorf("KillRewardExpAndSp(%v, %v, %v, %v, %v) = (%d, %d), want (%d, %d)",
					tt.expReward, tt.spReward, tt.damage, tt.totalDamage, tt.levelDiff,
					gotExp, gotSp, tt.wantExp, tt.wantSp)
			}
		})
	}
}

// TestKillRewardExpAndSp_FullShareMatchesTemplate documents the acceptance
// criterion that a sole attacker dealing all the damage, at or below the
// falloff threshold, receives the template's full reward.
func TestKillRewardExpAndSp_FullShareMatchesTemplate(t *testing.T) {
	exp, sp := KillRewardExpAndSp(4000, 250, 77, 77, 0)
	if exp != 4000 || sp != 250 {
		t.Errorf("got (%d, %d), want (4000, 250)", exp, sp)
	}
}

// ---- from sex_test.go ----
func TestParseSex(t *testing.T) {
	tests := []struct {
		in      int32
		want    Sex
		wantErr bool
	}{
		{0, SexMale, false},
		{1, SexFemale, false},
		{2, 0, true},
		{-1, 0, true},
	}
	for _, tt := range tests {
		got, err := ParseSex(tt.in)
		if tt.wantErr {
			if err == nil {
				t.Errorf("ParseSex(%d) = %v, nil; want error", tt.in, got)
			}
			continue
		}
		if err != nil {
			t.Errorf("ParseSex(%d) unexpected error: %v", tt.in, err)
			continue
		}
		if got != tt.want {
			t.Errorf("ParseSex(%d) = %v, want %v", tt.in, got, tt.want)
		}
	}
}

// ---- from template_test.go ----
func TestTemplateTable_All(t *testing.T) {
	// 0, 10 and 18 are base professions (classParent maps them to -1), so
	// NewTemplateTable needs no other entries to resolve them.
	table, err := NewTemplateTable(map[int]*Template{
		18: {ID: 18},
		0:  {ID: 0},
		10: {ID: 10},
	})
	if err != nil {
		t.Fatalf("NewTemplateTable() error: %v", err)
	}

	all := table.All()
	if len(all) != table.Count() {
		t.Fatalf("All() returned %d templates, Count() = %d", len(all), table.Count())
	}

	var ids []int
	for _, tpl := range all {
		ids = append(ids, tpl.ID)
	}
	if !sort.IntsAreSorted(ids) {
		t.Fatalf("All() not sorted ascending by ID: %v", ids)
	}
	if want := []int{0, 10, 18}; !equalInts(ids, want) {
		t.Fatalf("All() ids = %v, want %v", ids, want)
	}
}

func TestSkillGrantCorrectedCost(t *testing.T) {
	if got := (SkillGrant{Cost: -1}).CorrectedCost(); got != 0 {
		t.Fatalf("CorrectedCost(-1) = %d, want 0", got)
	}
	if got := (SkillGrant{Cost: 50}).CorrectedCost(); got != 50 {
		t.Fatalf("CorrectedCost(50) = %d, want 50", got)
	}
}

func TestTemplateSkillLearning(t *testing.T) {
	tmpl := &Template{Skills: []SkillGrant{
		{SkillID: 3, Level: 1, MinLevel: 5, Cost: 50},
		{SkillID: 3, Level: 2, MinLevel: 5, Cost: 50},
		{SkillID: 3, Level: 3, MinLevel: 10, Cost: 370},
		{SkillID: 194, Level: 1, MinLevel: 1, Cost: 0},
		{SkillID: 1405, Level: 1, MinLevel: 5, Cost: -1},
	}}

	if got, ok := tmpl.FindSkillGrant(3, 2); !ok || got.Level != 2 {
		t.Fatalf("FindSkillGrant(3, 2) = %+v, %v; want level 2", got, ok)
	}
	if _, ok := tmpl.FindSkillGrant(3, 4); ok {
		t.Fatal("FindSkillGrant(3, 4) found a missing grant")
	}

	available := tmpl.AvailableSkillGrants(5, SkillLevels{3: 0})
	want := []SkillGrant{
		{SkillID: 3, Level: 1, MinLevel: 5, Cost: 50},
		{SkillID: 1405, Level: 1, MinLevel: 5, Cost: -1},
	}
	if !equalSkillGrants(available, want) {
		t.Fatalf("AvailableSkillGrants(level 5, known none) = %+v, want %+v", available, want)
	}

	available = tmpl.AvailableSkillGrants(5, SkillLevels{3: 1, 1405: 1})
	want = []SkillGrant{{SkillID: 3, Level: 2, MinLevel: 5, Cost: 50}}
	if !equalSkillGrants(available, want) {
		t.Fatalf("AvailableSkillGrants(level 5, known 3:1) = %+v, want %+v", available, want)
	}

	if got := tmpl.RequiredLevelForNextSkillGrant(5); got != 10 {
		t.Fatalf("RequiredLevelForNextSkillGrant(level 5) = %d, want 10", got)
	}
	if got := tmpl.RequiredLevelForNextSkillGrant(10); got != 0 {
		t.Fatalf("RequiredLevelForNextSkillGrant(level 10) = %d, want 0", got)
	}

	grant, status := tmpl.CheckSkillLearn(5, 49, SkillLevels{}, 3, 1)
	if status != LearnNeedsSP || grant.CorrectedCost() != 50 {
		t.Fatalf("CheckSkillLearn(not enough SP) = %+v, %v; want cost 50 and LearnNeedsSP", grant, status)
	}

	grant, status = tmpl.CheckSkillLearn(5, 50, SkillLevels{}, 3, 1)
	if status != LearnAllowed || grant.SkillID != 3 || grant.Level != 1 {
		t.Fatalf("CheckSkillLearn(enough SP) = %+v, %v; want skill 3 level 1 and LearnAllowed", grant, status)
	}

	grant, status = tmpl.CheckSkillLearn(5, 0, SkillLevels{}, 1405, 1)
	if status != LearnAllowed || grant.CorrectedCost() != 0 {
		t.Fatalf("CheckSkillLearn(corrected zero cost) = %+v, %v; want allowed zero-cost grant", grant, status)
	}

	if _, status = tmpl.CheckSkillLearn(5, 1000, SkillLevels{3: 0}, 3, 2); status != LearnUnavailable {
		t.Fatalf("CheckSkillLearn(skipped previous level) = %v, want LearnUnavailable", status)
	}
}

// TestTemplateSkillLearningIgnoresMinLevelAndZeroCost pins that CheckSkillLearn
// does not reject on MinLevel or a zero Cost: RequestAcquireSkill.java's
// general-learn case (lines 59-101) locates the node via
// PlayerTemplate.findSkill, which ignores minLvl (PlayerTemplate.java:193-196),
// and only rejects on known-level continuity and SP vs getCorrectedCost() — it
// has no level or cost==0 gate of its own.
func TestTemplateSkillLearningIgnoresMinLevelAndZeroCost(t *testing.T) {
	tmpl := &Template{Skills: []SkillGrant{
		{SkillID: 3, Level: 1, MinLevel: 20, Cost: 50},
		{SkillID: 249, Level: 1, MinLevel: 1, Cost: 0},
	}}

	if _, status := tmpl.CheckSkillLearn(1, 0, SkillLevels{}, 3, 1); status != LearnNeedsSP {
		t.Fatalf("CheckSkillLearn(character level 1 below grant MinLevel 20, 0 SP) = %v, want LearnNeedsSP (no MinLevel gate)", status)
	}
	grant, status := tmpl.CheckSkillLearn(1, 50, SkillLevels{}, 3, 1)
	if status != LearnAllowed || grant.SkillID != 3 {
		t.Fatalf("CheckSkillLearn(character level 1 below grant MinLevel 20, enough SP) = %+v, %v; want LearnAllowed", grant, status)
	}

	grant, status = tmpl.CheckSkillLearn(1, 0, SkillLevels{}, 249, 1)
	if status != LearnAllowed || grant.SkillID != 249 || grant.CorrectedCost() != 0 {
		t.Fatalf("CheckSkillLearn(cost-0 grant requested manually) = %+v, %v; want LearnAllowed (no cost==0 gate)", grant, status)
	}
}

// TestTemplateAutoGetSkillGrants pins which grants a level hands over for
// free: only an exact cost of 0, only the highest level unlocked per skill,
// and only where the character is not already at or above that level.
func TestTemplateAutoGetSkillGrants(t *testing.T) {
	tmpl := &Template{Skills: []SkillGrant{
		{SkillID: 194, Level: 1, MinLevel: 1, Cost: 0},
		{SkillID: 249, Level: 1, MinLevel: 5, Cost: 0},
		{SkillID: 249, Level: 2, MinLevel: 10, Cost: 0},
		{SkillID: 249, Level: 3, MinLevel: 20, Cost: 0},
		// Bought, and the -1 variant that merely displays a price of 0.
		{SkillID: 3, Level: 1, MinLevel: 5, Cost: 50},
		{SkillID: 1405, Level: 1, MinLevel: 5, Cost: -1},
	}}

	got := tmpl.AutoGetSkillGrants(10, SkillLevels{})
	want := []SkillGrant{
		{SkillID: 194, Level: 1, MinLevel: 1, Cost: 0},
		{SkillID: 249, Level: 2, MinLevel: 10, Cost: 0},
	}
	if !equalSkillGrants(got, want) {
		t.Fatalf("AutoGetSkillGrants(level 10, known none) = %+v, want %+v", got, want)
	}

	got = tmpl.AutoGetSkillGrants(10, SkillLevels{194: 1, 249: 2})
	if len(got) != 0 {
		t.Fatalf("AutoGetSkillGrants(level 10, already granted) = %+v, want none", got)
	}

	got = tmpl.AutoGetSkillGrants(10, SkillLevels{249: 1})
	want = []SkillGrant{
		{SkillID: 194, Level: 1, MinLevel: 1, Cost: 0},
		{SkillID: 249, Level: 2, MinLevel: 10, Cost: 0},
	}
	if !equalSkillGrants(got, want) {
		t.Fatalf("AutoGetSkillGrants(level 10, known 249:1) = %+v, want %+v", got, want)
	}
}

func TestTemplateAllAvailableSkillGrants(t *testing.T) {
	tmpl := &Template{Skills: []SkillGrant{
		{SkillID: 194, Level: 1, MinLevel: 1, Cost: 0},
		{SkillID: 3, Level: 1, MinLevel: 5, Cost: 50},
		{SkillID: 249, Level: 1, MinLevel: 5, Cost: 0},
		{SkillID: 249, Level: 2, MinLevel: 10, Cost: 0},
		{SkillID: 3, Level: 2, MinLevel: 10, Cost: -1},
		{SkillID: 249, Level: 3, MinLevel: 20, Cost: 0},
	}}

	got := tmpl.AllAvailableSkillGrants(10, SkillLevels{194: 1, 249: 1})
	want := []SkillGrant{
		{SkillID: 3, Level: 2, MinLevel: 10, Cost: -1},
		{SkillID: 249, Level: 2, MinLevel: 10, Cost: 0},
	}
	if !equalSkillGrants(got, want) {
		t.Fatalf("AllAvailableSkillGrants(level 10, known 194:1/249:1) = %+v, want %+v", got, want)
	}
}

// TestTemplateReachableSkillGrants pins the nine-level slack every skill but
// expertise keeps, so a small level loss does not strip skills the character
// legitimately learned.
func TestTemplateReachableSkillGrants(t *testing.T) {
	tmpl := &Template{Skills: []SkillGrant{
		{SkillID: 3, Level: 1, MinLevel: 5, Cost: 50},
		{SkillID: 3, Level: 2, MinLevel: 20, Cost: 50},
		{SkillID: 239, Level: 1, MinLevel: 20, Cost: 0},
		{SkillID: 239, Level: 2, MinLevel: 40, Cost: 0},
	}}

	// At level 15 the lookahead reaches skill 3's level-20 grant, but
	// expertise stays pinned to the level itself and so has no grant yet.
	reachable := tmpl.ReachableSkillGrants(15)
	if got, ok := reachable[3]; !ok || got.Level != 2 {
		t.Fatalf("ReachableSkillGrants(15)[3] = %+v, %v; want level 2", got, ok)
	}
	if got, ok := reachable[239]; ok {
		t.Fatalf("ReachableSkillGrants(15)[239] = %+v; want no expertise grant", got)
	}

	if got, ok := tmpl.ReachableSkillGrants(20)[239]; !ok || got.Level != 1 {
		t.Fatalf("ReachableSkillGrants(20)[239] = %+v, %v; want level 1", got, ok)
	}
	if got, ok := tmpl.ReachableSkillGrants(40)[239]; !ok || got.Level != 2 {
		t.Fatalf("ReachableSkillGrants(40)[239] = %+v, %v; want level 2", got, ok)
	}

	// One level short of the lookahead, skill 3 falls back to its lower
	// grant rather than dropping out entirely.
	if got, ok := tmpl.ReachableSkillGrants(10)[3]; !ok || got.Level != 1 {
		t.Fatalf("ReachableSkillGrants(10)[3] = %+v, %v; want level 1", got, ok)
	}
	// Far enough below every grant, nothing is reachable at all.
	if reachable := (&Template{Skills: []SkillGrant{
		{SkillID: 3, Level: 1, MinLevel: 20, Cost: 50},
	}}).ReachableSkillGrants(10); len(reachable) != 0 {
		t.Fatalf("ReachableSkillGrants(10) = %+v, want none", reachable)
	}

	if !tmpl.GrantsSkill(3) {
		t.Error("GrantsSkill(3) = false, want true")
	}
	if tmpl.GrantsSkill(4267) {
		t.Error("GrantsSkill(4267) = true, want false for a skill the line never grants")
	}
}

func equalSkillGrants(a, b []SkillGrant) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
