package serverpackets

import (
	"bytes"
	"testing"
)

func TestFrameAutoAttackStop(t *testing.T) {
	// Expected payloads generated by the reference Java implementation's
	// AutoAttackStop packet writer for each object id.
	tests := []struct {
		name     string
		objectID int32
		want     []byte
	}{
		{"player", 268476516, []byte{0x2c, 0x64, 0xa0, 0x00, 0x10}},
		{"zero", 0, []byte{0x2c, 0x00, 0x00, 0x00, 0x00}},
		{"max", 2147483647, []byte{0x2c, 0xff, 0xff, 0xff, 0x7f}},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := framePayload(t, FrameAutoAttackStop(tc.objectID))
			if !bytes.Equal(got, tc.want) {
				t.Errorf("FrameAutoAttackStop(%d) = %x, want %x", tc.objectID, got, tc.want)
			}
		})
	}
}
