package serverpackets

import (
	"bytes"
	"testing"
)

func TestFrameDeleteObject(t *testing.T) {
	// Expected payloads generated by the reference Java implementation's
	// DeleteObject packet writer for each (objectID, seated) pair.
	tests := []struct {
		name     string
		objectID int32
		seated   bool
		want     []byte
	}{
		{"standing", 268476516, false, []byte{0x12, 0x64, 0xa0, 0x00, 0x10, 0x01, 0x00, 0x00, 0x00}},
		{"seated", 268476516, true, []byte{0x12, 0x64, 0xa0, 0x00, 0x10, 0x00, 0x00, 0x00, 0x00}},
		{"small id", 1, false, []byte{0x12, 0x01, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00}},
		{"max id seated", 2147483647, true, []byte{0x12, 0xff, 0xff, 0xff, 0x7f, 0x00, 0x00, 0x00, 0x00}},
		{"zero id", 0, false, []byte{0x12, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00}},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := framePayload(t, FrameDeleteObject(tc.objectID, tc.seated))
			if !bytes.Equal(got, tc.want) {
				t.Errorf("FrameDeleteObject(%d, %v) = %x, want %x", tc.objectID, tc.seated, got, tc.want)
			}
		})
	}
}
