package serverpackets

import (
	"bytes"
	"encoding/binary"
	"testing"

	"github.com/fatal10110/acis_golang/internal/gameserver/geo/block"
	"github.com/fatal10110/acis_golang/internal/gameserver/model/actor/event"
	"github.com/fatal10110/acis_golang/internal/gameserver/model/door"
	"github.com/fatal10110/acis_golang/internal/gameserver/model/location"
	"github.com/fatal10110/acis_golang/internal/gameserver/model/skill"
	"github.com/fatal10110/acis_golang/internal/gameserver/model/staticobject"
)

// ---- from attack_test.go ----
func TestFrameAttack(t *testing.T) {
	got := framePayload(t, FrameAttack(AttackSnapshot{
		AttackerID: 268476516,
		X:          -71440,
		Y:          258000,
		Z:          -3104,
		Hits: []AttackHit{
			{TargetID: 268480061, Damage: 37, Flags: AttackHitSoulshot | AttackHitCritical | AttackHitShield},
			{TargetID: 7, Damage: 0, Flags: AttackHitMiss},
		},
	}))
	want := []byte{
		0x05,
		0x64, 0xa0, 0x00, 0x10,
		0x3d, 0xae, 0x00, 0x10,
		0x25, 0x00, 0x00, 0x00,
		0x70,
		0xf0, 0xe8, 0xfe, 0xff,
		0xd0, 0xef, 0x03, 0x00,
		0xe0, 0xf3, 0xff, 0xff,
		0x01, 0x00,
		0x07, 0x00, 0x00, 0x00,
		0x00, 0x00, 0x00, 0x00,
		0x80,
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("FrameAttack() = %x, want %x", got, want)
	}
}

// ---- from autoattack_test.go ----
func TestFrameAutoAttackStop(t *testing.T) {
	// Expected payloads generated by the reference Java implementation's
	// AutoAttackStop packet writer for each object id.
	tests := []struct {
		name     string
		objectID int32
		want     []byte
	}{
		{"player", 268476516, []byte{0x2c, 0x64, 0xa0, 0x00, 0x10}},
		{"zero", 0, []byte{0x2c, 0x00, 0x00, 0x00, 0x00}},
		{"max", 2147483647, []byte{0x2c, 0xff, 0xff, 0xff, 0x7f}},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := framePayload(t, FrameAutoAttackStop(tc.objectID))
			if !bytes.Equal(got, tc.want) {
				t.Errorf("FrameAutoAttackStop(%d) = %x, want %x", tc.objectID, got, tc.want)
			}
		})
	}
}

// ---- from deleteobject_test.go ----
func TestFrameDeleteObject(t *testing.T) {
	// Expected payloads generated by the reference Java implementation's
	// DeleteObject packet writer for each (objectID, seated) pair.
	tests := []struct {
		name     string
		objectID int32
		seated   bool
		want     []byte
	}{
		{"standing", 268476516, false, []byte{0x12, 0x64, 0xa0, 0x00, 0x10, 0x01, 0x00, 0x00, 0x00}},
		{"seated", 268476516, true, []byte{0x12, 0x64, 0xa0, 0x00, 0x10, 0x00, 0x00, 0x00, 0x00}},
		{"small id", 1, false, []byte{0x12, 0x01, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00}},
		{"max id seated", 2147483647, true, []byte{0x12, 0xff, 0xff, 0xff, 0x7f, 0x00, 0x00, 0x00, 0x00}},
		{"zero id", 0, false, []byte{0x12, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00}},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := framePayload(t, FrameDeleteObject(tc.objectID, tc.seated))
			if !bytes.Equal(got, tc.want) {
				t.Errorf("FrameDeleteObject(%d, %v) = %x, want %x", tc.objectID, tc.seated, got, tc.want)
			}
		})
	}
}

// ---- from flytolocation_test.go ----
func TestFrameFlyToLocation(t *testing.T) {
	got := framePayload(t, FrameFlyToLocation(
		268476516,
		location.Location{X: 46160, Y: 41237, Z: -3534},
		location.Location{X: 12345, Y: -6789, Z: 100},
		skill.FlightThrowUp,
	))
	want := []byte{
		OpcodeFlyToLocation,
		0x64, 0xa0, 0x00, 0x10,
		0x50, 0xb4, 0x00, 0x00,
		0x15, 0xa1, 0x00, 0x00,
		0x32, 0xf2, 0xff, 0xff,
		0x39, 0x30, 0x00, 0x00,
		0x7b, 0xe5, 0xff, 0xff,
		0x64, 0x00, 0x00, 0x00,
		0x00, 0x00, 0x00, 0x00,
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("FrameFlyToLocation() = %x, want %x", got, want)
	}
}

// ---- from move_test.go ----
func TestFrameMoveLocationEvent(t *testing.T) {
	ev := event.Move{
		Origin:      location.Location{X: 10, Y: 20, Z: 30},
		Destination: location.Location{X: 100, Y: 200, Z: 300},
	}
	got := framePayload(t, FrameMove(101, ev))
	want := []byte{
		0x01,
		0x65, 0x00, 0x00, 0x00,
		0x64, 0x00, 0x00, 0x00,
		0xc8, 0x00, 0x00, 0x00,
		0x2c, 0x01, 0x00, 0x00,
		0x0a, 0x00, 0x00, 0x00,
		0x14, 0x00, 0x00, 0x00,
		0x1e, 0x00, 0x00, 0x00,
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("FrameMove() = %x, want MoveToLocation %x", got, want)
	}
}

func TestFrameMoveFollowEvent(t *testing.T) {
	ev := event.Move{
		Origin:       location.Location{X: 10, Y: 20, Z: 30},
		FollowTarget: 202,
		FollowOffset: 40,
	}
	got := framePayload(t, FrameMove(101, ev))
	want := []byte{
		0x60,
		0x65, 0x00, 0x00, 0x00,
		0xca, 0x00, 0x00, 0x00,
		0x28, 0x00, 0x00, 0x00,
		0x0a, 0x00, 0x00, 0x00,
		0x14, 0x00, 0x00, 0x00,
		0x1e, 0x00, 0x00, 0x00,
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("FrameMove() = %x, want MoveToPawn %x", got, want)
	}
}

// ---- from movement_control_test.go ----
func TestFrameStopMove(t *testing.T) {
	got := framePayload(t, FrameStopMove(268476516, location.Location{X: 46160, Y: 41237, Z: -3534}, 32768))
	want := []byte{
		OpcodeStopMove,
		0x64, 0xa0, 0x00, 0x10,
		0x50, 0xb4, 0x00, 0x00,
		0x15, 0xa1, 0x00, 0x00,
		0x32, 0xf2, 0xff, 0xff,
		0x00, 0x80, 0x00, 0x00,
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("FrameStopMove() = %x, want %x", got, want)
	}
}

func TestFrameValidateLocation(t *testing.T) {
	got := framePayload(t, FrameValidateLocation(268476516, location.Location{X: 46160, Y: 41237, Z: -3534}, 32768))
	want := []byte{
		OpcodeValidateLocation,
		0x64, 0xa0, 0x00, 0x10,
		0x50, 0xb4, 0x00, 0x00,
		0x15, 0xa1, 0x00, 0x00,
		0x32, 0xf2, 0xff, 0xff,
		0x00, 0x80, 0x00, 0x00,
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("FrameValidateLocation() = %x, want %x", got, want)
	}
}

func TestFrameStartRotation(t *testing.T) {
	got := framePayload(t, FrameStartRotation(268476516, 32768, 1, 0))
	want := []byte{
		OpcodeStartRotation,
		0x64, 0xa0, 0x00, 0x10,
		0x00, 0x80, 0x00, 0x00,
		0x01, 0x00, 0x00, 0x00,
		0x00, 0x00, 0x00, 0x00,
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("FrameStartRotation() = %x, want %x", got, want)
	}
}

func TestFrameStopRotation(t *testing.T) {
	got := framePayload(t, FrameStopRotation(268476516, 0x1234, 0))
	want := []byte{
		OpcodeStopRotation,
		0x64, 0xa0, 0x00, 0x10,
		0x34, 0x12, 0x00, 0x00,
		0x00, 0x00, 0x00, 0x00,
		0x34,
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("FrameStopRotation() = %x, want %x", got, want)
	}
}

// ---- from movetolocation_test.go ----
func TestFrameMoveToLocation(t *testing.T) {
	got := framePayload(t, FrameMoveToLocation(
		268476516,
		location.Location{X: 46160, Y: 41237, Z: -3534},
		location.Location{X: 46117, Y: 41247, Z: -3532},
	))
	want := []byte{
		0x01,
		0x64, 0xa0, 0x00, 0x10,
		0x50, 0xb4, 0x00, 0x00,
		0x15, 0xa1, 0x00, 0x00,
		0x32, 0xf2, 0xff, 0xff,
		0x25, 0xb4, 0x00, 0x00,
		0x1f, 0xa1, 0x00, 0x00,
		0x34, 0xf2, 0xff, 0xff,
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("FrameMoveToLocation() = %x, want %x", got, want)
	}
}

// ---- from movetopawn_test.go ----
func TestFrameMoveToPawn(t *testing.T) {
	got := framePayload(t, FrameMoveToPawn(268476516, 268480061, 70, location.Location{X: -71440, Y: 258000, Z: -3104}))
	want := []byte{
		0x60,
		0x64, 0xa0, 0x00, 0x10,
		0x3d, 0xae, 0x00, 0x10,
		0x46, 0x00, 0x00, 0x00,
		0xf0, 0xe8, 0xfe, 0xff,
		0xd0, 0xef, 0x03, 0x00,
		0xe0, 0xf3, 0xff, 0xff,
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("FrameMoveToPawn() = %x, want %x", got, want)
	}
}

// ---- from stance_social_test.go ----
func TestFrameAutoAttackStart(t *testing.T) {
	got := framePayload(t, FrameAutoAttackStart(12345))
	want := []byte{OpcodeAutoAttackStart, 0x39, 0x30, 0x00, 0x00}
	if !bytes.Equal(got, want) {
		t.Fatalf("FrameAutoAttackStart() = %x, want %x", got, want)
	}
}

func TestFrameSocialAction(t *testing.T) {
	got := framePayload(t, FrameSocialAction(12345, 13))
	want := []byte{
		OpcodeSocialAction,
		0x39, 0x30, 0x00, 0x00,
		0x0d, 0x00, 0x00, 0x00,
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("FrameSocialAction() = %x, want %x", got, want)
	}
}

func TestFrameChangeMoveType(t *testing.T) {
	got := framePayload(t, FrameChangeMoveType(12345, false, false))
	want := []byte{
		OpcodeChangeMoveType,
		0x39, 0x30, 0x00, 0x00,
		0x00, 0x00, 0x00, 0x00,
		0x00, 0x00, 0x00, 0x00,
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("FrameChangeMoveType() = %x, want %x", got, want)
	}
}

func TestFrameChangeWaitType(t *testing.T) {
	got := framePayload(t, FrameChangeWaitType(12345, WaitSitting, location.Location{X: 46160, Y: 41237, Z: -3534}))
	want := []byte{
		OpcodeChangeWaitType,
		0x39, 0x30, 0x00, 0x00,
		0x00, 0x00, 0x00, 0x00,
		0x50, 0xb4, 0x00, 0x00,
		0x15, 0xa1, 0x00, 0x00,
		0x32, 0xf2, 0xff, 0xff,
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("FrameChangeWaitType() = %x, want %x", got, want)
	}
}

// ---- from targeting_test.go ----
func TestFrameMyTargetSelected(t *testing.T) {
	got := framePayload(t, FrameMyTargetSelected(12345, 0x0010))
	want := []byte{
		OpcodeMyTargetSelected,
		0x39, 0x30, 0x00, 0x00,
		0x10, 0x00,
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("FrameMyTargetSelected() = %x, want %x", got, want)
	}
}

func TestFrameTargetSelected(t *testing.T) {
	got := framePayload(t, FrameTargetSelected(100, 200, location.Location{X: 46160, Y: 41237, Z: -3534}))
	want := []byte{
		OpcodeTargetSelected,
		0x64, 0x00, 0x00, 0x00,
		0xc8, 0x00, 0x00, 0x00,
		0x50, 0xb4, 0x00, 0x00,
		0x15, 0xa1, 0x00, 0x00,
		0x32, 0xf2, 0xff, 0xff,
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("FrameTargetSelected() = %x, want %x", got, want)
	}
}

func TestFrameTargetUnselected(t *testing.T) {
	got := framePayload(t, FrameTargetUnselected(100, location.Location{X: 46160, Y: 41237, Z: -3534}))
	want := []byte{
		OpcodeTargetUnselected,
		0x64, 0x00, 0x00, 0x00,
		0x50, 0xb4, 0x00, 0x00,
		0x15, 0xa1, 0x00, 0x00,
		0x32, 0xf2, 0xff, 0xff,
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("FrameTargetUnselected() = %x, want %x", got, want)
	}
}

func TestFrameStatusUpdate(t *testing.T) {
	got := framePayload(t, FrameStatusUpdate(12345, []StatusAttribute{
		{Type: StatusCurrentHP, Value: 75},
		{Type: StatusMaxHP, Value: 100},
	}))
	want := []byte{
		OpcodeStatusUpdate,
		0x39, 0x30, 0x00, 0x00,
		0x02, 0x00, 0x00, 0x00,
		0x09, 0x00, 0x00, 0x00,
		0x4b, 0x00, 0x00, 0x00,
		0x0a, 0x00, 0x00, 0x00,
		0x64, 0x00, 0x00, 0x00,
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("FrameStatusUpdate() = %x, want %x", got, want)
	}
}

// ---- from teleporttolocation_test.go ----
func TestFrameTeleportToLocation(t *testing.T) {
	to := location.Location{X: -71440, Y: 258000, Z: -3104}

	tests := []struct {
		name         string
		fastTeleport bool
		want         []byte
	}{
		{
			name:         "black screen",
			fastTeleport: false,
			want: []byte{
				0x28,
				0x64, 0xa0, 0x00, 0x10,
				0xf0, 0xe8, 0xfe, 0xff,
				0xd0, 0xef, 0x03, 0x00,
				0xe0, 0xf3, 0xff, 0xff,
				0x00, 0x00, 0x00, 0x00,
			},
		},
		{
			name:         "fast teleport",
			fastTeleport: true,
			want: []byte{
				0x28,
				0x64, 0xa0, 0x00, 0x10,
				0xf0, 0xe8, 0xfe, 0xff,
				0xd0, 0xef, 0x03, 0x00,
				0xe0, 0xf3, 0xff, 0xff,
				0x01, 0x00, 0x00, 0x00,
			},
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := framePayload(t, FrameTeleportToLocation(268476516, to, tc.fastTeleport))
			if !bytes.Equal(got, tc.want) {
				t.Errorf("FrameTeleportToLocation(_, _, %v) = %x, want %x", tc.fastTeleport, got, tc.want)
			}
		})
	}
}

// ---- from worldobjects_test.go ----
type doorShape struct{}

func (doorShape) GeoX() int { return 0 }

func (doorShape) GeoY() int { return 0 }

func (doorShape) GeoZ() int { return 0 }

func (doorShape) Height() int { return 32 }

func (doorShape) GeoData() [][]block.NSWE { return [][]block.NSWE{{block.NoDirections}} }

func TestFrameDoorInfo(t *testing.T) {
	gate := testDoor(t)

	got := framePayload(t, FrameDoorInfo(gate, true))

	want := []byte{OpcodeDoorInfo}
	want = binary.LittleEndian.AppendUint32(want, uint32(1000))
	want = binary.LittleEndian.AppendUint32(want, uint32(19210001))
	want = binary.LittleEndian.AppendUint32(want, 1)
	want = binary.LittleEndian.AppendUint32(want, 1)
	want = binary.LittleEndian.AppendUint32(want, 1)
	want = binary.LittleEndian.AppendUint32(want, 253200)
	want = binary.LittleEndian.AppendUint32(want, 253200)
	want = binary.LittleEndian.AppendUint32(want, 0)
	want = binary.LittleEndian.AppendUint32(want, 0)
	if string(got) != string(want) {
		t.Fatalf("FrameDoorInfo() = % x, want % x", got, want)
	}
}

func TestFrameDoorStatusUpdate(t *testing.T) {
	gate := testDoor(t)

	got := framePayload(t, FrameDoorStatusUpdate(gate, false))

	want := []byte{OpcodeDoorStatusUpdate}
	want = binary.LittleEndian.AppendUint32(want, uint32(1000))
	want = binary.LittleEndian.AppendUint32(want, 1)
	want = binary.LittleEndian.AppendUint32(want, 0)
	want = binary.LittleEndian.AppendUint32(want, 0)
	want = binary.LittleEndian.AppendUint32(want, uint32(19210001))
	want = binary.LittleEndian.AppendUint32(want, 253200)
	want = binary.LittleEndian.AppendUint32(want, 253200)
	if string(got) != string(want) {
		t.Fatalf("FrameDoorStatusUpdate() = % x, want % x", got, want)
	}
}

func TestFrameStaticObjectInfo(t *testing.T) {
	sign, err := staticobject.NewObject(1001, &staticobject.Template{ID: 41001})
	if err != nil {
		t.Fatalf("NewObject: %v", err)
	}

	got := framePayload(t, FrameStaticObjectInfo(sign))

	want := []byte{OpcodeStaticObjectInfo}
	want = binary.LittleEndian.AppendUint32(want, 41001)
	want = binary.LittleEndian.AppendUint32(want, 1001)
	if string(got) != string(want) {
		t.Fatalf("FrameStaticObjectInfo() = % x, want % x", got, want)
	}
}

func TestFrameChairSit(t *testing.T) {
	got := framePayload(t, FrameChairSit(0x1000a064, 1234))

	want := []byte{OpcodeChairSit}
	want = binary.LittleEndian.AppendUint32(want, 0x1000a064)
	want = binary.LittleEndian.AppendUint32(want, 1234)
	if string(got) != string(want) {
		t.Fatalf("FrameChairSit() = % x, want % x", got, want)
	}
}

func testDoor(t *testing.T) *door.Object {
	t.Helper()
	gate, err := door.NewObject(1000, &door.Template{
		ID:       19210001,
		Name:     "gludio_castle_outter_001",
		Kind:     door.KindDoor,
		Level:    1,
		Position: location.Location{X: -18408, Y: 113064, Z: -2768},
		Coordinates: []location.Point{
			{X: -18481, Y: 113059},
			{X: -18351, Y: 113059},
			{X: -18351, Y: 113071},
			{X: -18481, Y: 113071},
		},
		HP: 253200, PDef: 644, MDef: 518, Height: 320,
	}, doorShape{})
	if err != nil {
		t.Fatalf("NewObject: %v", err)
	}
	return gate
}
