version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: mariadb-server
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 123321
      MARIADB_DATABASE: acis # Optional: creates this DB on startup
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
