package block

import "testing"

// newTestMultilayer builds a Multilayer block where cell (0,0) has the
// given ascending heights as its layers (NSWE set to a distinguishable,
// non-zero value per layer) and every other cell has a single dummy
// layer, satisfying NewMultilayer's 1..MaxLayers-per-cell requirement.
func newTestMultilayer(t *testing.T, heights []int16) *Multilayer {
	t.Helper()
	var cells [CellCount][]Cell
	for i := range cells {
		cells[i] = []Cell{{Height: 0, NSWE: AllDirections}}
	}
	layers := make([]Cell, len(heights))
	for i, h := range heights {
		layers[i] = Cell{Height: h, NSWE: NSWE((i % 15) + 1)}
	}
	cells[cellIndex(0, 0)] = layers

	b, err := NewMultilayer(cells)
	if err != nil {
		t.Fatalf("NewMultilayer: %v", err)
	}
	return b
}

// TestMultilayerNearest checks the tie-break behavior of Nearest against
// vectors generated by running the reference implementation's exact
// scan-and-track-limit algorithm standalone: on a tie, the higher (later
// in ascending order) layer wins.
func TestMultilayerNearest(t *testing.T) {
	cases := []struct {
		heights []int16
		worldZ  int32
		want    int // index into heights
	}{
		{[]int16{10, 20, 30}, 0, 0},
		{[]int16{10, 20, 30}, 10, 0},
		{[]int16{10, 20, 30}, 15, 1},
		{[]int16{10, 20, 30}, 20, 1},
		{[]int16{10, 20, 30}, 25, 2},
		{[]int16{10, 20, 30}, 100, 2},
		{[]int16{10, 20, 30}, -100, 0},
		{[]int16{10, 20, 30}, -15, 0},
		{[]int16{10, 20}, 0, 0},
		{[]int16{10, 20}, 10, 0},
		{[]int16{10, 20}, 15, 1},
		{[]int16{10, 20}, 20, 1},
		{[]int16{10, 20}, 25, 1},
		{[]int16{10, 20}, 100, 1},
		{[]int16{10, 20}, -100, 0},
		{[]int16{10, 20}, -15, 0},
		{[]int16{5, 15, 25}, 0, 0},
		{[]int16{5, 15, 25}, 10, 1},
		{[]int16{5, 15, 25}, 15, 1},
		{[]int16{5, 15, 25}, 20, 2},
		{[]int16{5, 15, 25}, 25, 2},
		{[]int16{5, 15, 25}, 100, 2},
		{[]int16{5, 15, 25}, -100, 0},
		{[]int16{5, 15, 25}, -15, 0},
		{[]int16{-20, -10, 0, 10, 20}, 0, 2},
		{[]int16{-20, -10, 0, 10, 20}, 10, 3},
		{[]int16{-20, -10, 0, 10, 20}, 15, 4},
		{[]int16{-20, -10, 0, 10, 20}, 20, 4},
		{[]int16{-20, -10, 0, 10, 20}, 25, 4},
		{[]int16{-20, -10, 0, 10, 20}, 100, 4},
		{[]int16{-20, -10, 0, 10, 20}, -100, 0},
		{[]int16{-20, -10, 0, 10, 20}, -15, 1},
	}

	for _, c := range cases {
		b := newTestMultilayer(t, c.heights)
		handle := b.Nearest(0, 0, c.worldZ)
		if got := b.Height(handle); got != c.heights[c.want] {
			t.Errorf("heights=%v worldZ=%d: Height(Nearest) = %d, want %d (index %d)",
				c.heights, c.worldZ, got, c.heights[c.want], c.want)
		}
		wantNSWE := NSWE((c.want % 15) + 1)
		if got := b.NSWE(handle); got != wantNSWE {
			t.Errorf("heights=%v worldZ=%d: NSWE(Nearest) = %v, want %v", c.heights, c.worldZ, got, wantNSWE)
		}
		if got := b.HeightNearest(0, 0, c.worldZ); got != c.heights[c.want] {
			t.Errorf("heights=%v worldZ=%d: HeightNearest = %d, want %d", c.heights, c.worldZ, got, c.heights[c.want])
		}
	}
}

// TestMultilayerAboveBelow checks Above/Below against vectors generated
// by running the reference implementation's exact top-down/bottom-up
// scan standalone.
func TestMultilayerAboveBelow(t *testing.T) {
	const noLayer = -1
	cases := []struct {
		heights              []int16
		worldZ               int32
		wantAbove, wantBelow int // index into heights, or noLayer
	}{
		{[]int16{10, 20, 30}, 0, 2, noLayer},
		{[]int16{10, 20, 30}, 10, 2, noLayer},
		{[]int16{10, 20, 30}, 15, 2, 0},
		{[]int16{10, 20, 30}, 20, 2, 0},
		{[]int16{10, 20, 30}, 25, 2, 0},
		{[]int16{10, 20, 30}, 100, noLayer, 0},
		{[]int16{10, 20, 30}, -100, 2, noLayer},
		{[]int16{10, 20, 30}, -15, 2, noLayer},
		{[]int16{10, 20}, 0, 1, noLayer},
		{[]int16{10, 20}, 10, 1, noLayer},
		{[]int16{10, 20}, 15, 1, 0},
		{[]int16{10, 20}, 20, noLayer, 0},
		{[]int16{10, 20}, 25, noLayer, 0},
		{[]int16{10, 20}, 100, noLayer, 0},
		{[]int16{10, 20}, -100, 1, noLayer},
		{[]int16{10, 20}, -15, 1, noLayer},
		{[]int16{5, 15, 25}, 0, 2, noLayer},
		{[]int16{5, 15, 25}, 10, 2, 0},
		{[]int16{5, 15, 25}, 15, 2, 0},
		{[]int16{5, 15, 25}, 20, 2, 0},
		{[]int16{5, 15, 25}, 25, noLayer, 0},
		{[]int16{5, 15, 25}, 100, noLayer, 0},
		{[]int16{5, 15, 25}, -100, 2, noLayer},
		{[]int16{5, 15, 25}, -15, 2, noLayer},
		{[]int16{-20, -10, 0, 10, 20}, 0, 4, 0},
		{[]int16{-20, -10, 0, 10, 20}, 10, 4, 0},
		{[]int16{-20, -10, 0, 10, 20}, 15, 4, 0},
		{[]int16{-20, -10, 0, 10, 20}, 20, noLayer, 0},
		{[]int16{-20, -10, 0, 10, 20}, 25, noLayer, 0},
		{[]int16{-20, -10, 0, 10, 20}, 100, noLayer, 0},
		{[]int16{-20, -10, 0, 10, 20}, -100, 4, noLayer},
		{[]int16{-20, -10, 0, 10, 20}, -15, 4, 0},
	}

	for _, c := range cases {
		b := newTestMultilayer(t, c.heights)

		above := b.Above(0, 0, c.worldZ)
		if c.wantAbove == noLayer {
			if above != -1 {
				t.Errorf("heights=%v worldZ=%d: Above = %d, want -1", c.heights, c.worldZ, above)
			}
		} else if got := b.Height(above); got != c.heights[c.wantAbove] {
			t.Errorf("heights=%v worldZ=%d: Height(Above) = %d, want %d", c.heights, c.worldZ, got, c.heights[c.wantAbove])
		}

		below := b.Below(0, 0, c.worldZ)
		if c.wantBelow == noLayer {
			if below != -1 {
				t.Errorf("heights=%v worldZ=%d: Below = %d, want -1", c.heights, c.worldZ, below)
			}
		} else if got := b.Height(below); got != c.heights[c.wantBelow] {
			t.Errorf("heights=%v worldZ=%d: Height(Below) = %d, want %d", c.heights, c.worldZ, got, c.heights[c.wantBelow])
		}
	}
}

func TestMultilayerBasics(t *testing.T) {
	b := newTestMultilayer(t, []int16{10, 20, 30})

	if got := b.Kind(); got != KindMultilayer {
		t.Errorf("Kind() = %v, want %v", got, KindMultilayer)
	}
	if !b.HasGeodata() {
		t.Errorf("HasGeodata() = false, want true")
	}
	if got := b.Layers(0, 0); got != 3 {
		t.Errorf("Layers(0,0) = %d, want 3", got)
	}
	if got := b.Layers(1, 1); got != 1 {
		t.Errorf("Layers(1,1) = %d, want 1", got)
	}

	// A different cell must resolve independently of cell (0,0)'s layers.
	if got := b.HeightNearest(1, 1, 999); got != 0 {
		t.Errorf("HeightNearest(1,1,999) = %d, want 0", got)
	}
}

func TestNewMultilayerRejectsInvalidLayerCounts(t *testing.T) {
	var zeroLayers [CellCount][]Cell
	for i := range zeroLayers {
		zeroLayers[i] = []Cell{{Height: 0, NSWE: AllDirections}}
	}
	zeroLayers[0] = nil // 0 layers: invalid.
	if _, err := NewMultilayer(zeroLayers); err == nil {
		t.Error("NewMultilayer with a 0-layer cell: got nil error, want error")
	}

	var tooMany [CellCount][]Cell
	for i := range tooMany {
		tooMany[i] = []Cell{{Height: 0, NSWE: AllDirections}}
	}
	over := make([]Cell, MaxLayers+1)
	tooMany[0] = over
	if _, err := NewMultilayer(tooMany); err == nil {
		t.Error("NewMultilayer with a cell over MaxLayers: got nil error, want error")
	}
}
