package block

import "testing"

func TestNSWEString(t *testing.T) {
	cases := []struct {
		mask NSWE
		want string
	}{
		{NoDirections, "none"},
		{AllDirections, "all"},
		{North, "N"},
		{South, "S"},
		{West, "W"},
		{East, "E"},
		{North | South, "NS"},
		{West | East, "WE"},
		{North | West | East, "NWE"},
	}
	for _, c := range cases {
		if got := c.mask.String(); got != c.want {
			t.Errorf("NSWE(%#x).String() = %q, want %q", uint8(c.mask), got, c.want)
		}
	}
}

func TestNSWEAllows(t *testing.T) {
	cases := []struct {
		mask, dirs NSWE
		want       bool
	}{
		{AllDirections, North, true},
		{AllDirections, North | South, true},
		{North, South, false},
		{North | South, North | South, true},
		{North | South, North | East, false},
		{NoDirections, NoDirections, true},
	}
	for _, c := range cases {
		if got := c.mask.Allows(c.dirs); got != c.want {
			t.Errorf("NSWE(%#x).Allows(%#x) = %v, want %v", uint8(c.mask), uint8(c.dirs), got, c.want)
		}
	}
}

// Direction bit values are an exact wire contract (the on-disk NSWE
// nibble): East=0x01, West=0x02, South=0x04, North=0x08, verified against
// GeoStructure.java's CELL_FLAG_* constants.
func TestNSWEBitValues(t *testing.T) {
	cases := []struct {
		name string
		mask NSWE
		want uint8
	}{
		{"East", East, 0x01},
		{"West", West, 0x02},
		{"South", South, 0x04},
		{"North", North, 0x08},
		{"AllDirections", AllDirections, 0x0F},
		{"NoDirections", NoDirections, 0x00},
	}
	for _, c := range cases {
		if got := uint8(c.mask); got != c.want {
			t.Errorf("%s = %#x, want %#x", c.name, got, c.want)
		}
	}
}

// TestDecodeCell checks the per-cell code decode formula against vectors
// generated by running the reference implementation's exact arithmetic
// (data & 0x000F for NSWE; (short)((short)(data & 0xFFF0) >> 1) for
// height) standalone, including sign-extension edge cases.
func TestDecodeCell(t *testing.T) {
	cases := []struct {
		code       uint16
		wantNSWE   NSWE
		wantHeight int16
	}{
		{0x000F, 0xF, 0},
		{0x0001, 0x1, 0},
		{0x00D5, 0x5, 104},
		{0xFFF0, 0x0, -8},
		{0x0000, 0x0, 0},
		{0x8000, 0x0, -16384},
		{0x7FF0, 0x0, 16376},
		{0xFFFF, 0xF, -8},
		{0x000A, 0xA, 0},
		{0x0FF8, 0x8, 2040},
	}
	for _, c := range cases {
		got := DecodeCell(c.code)
		if got.NSWE != c.wantNSWE || got.Height != c.wantHeight {
			t.Errorf("DecodeCell(%#04x) = {NSWE:%#x Height:%d}, want {NSWE:%#x Height:%d}",
				c.code, uint8(got.NSWE), got.Height, uint8(c.wantNSWE), c.wantHeight)
		}
	}
}
