package scriptfp

import (
	"bufio"
	"bytes"
	_ "embed" // apimap.txt, census.golden
	"fmt"
	"maps"
	"slices"
	"strings"
)

// Inline is the apimap.txt value of a reference call that has no Go call of
// its own, such as a getter the Go handle folds into the next call.
const Inline = "inline"

//go:embed apimap.txt
var committedAPIMap []byte

//go:embed census.golden
var committedCensus []byte

// APIMap returns the committed Go names of reference engine calls, keyed by
// census row.
func APIMap() (map[string]string, error) {
	return parseAPIMap(committedAPIMap)
}

func parseAPIMap(data []byte) (map[string]string, error) {
	out := map[string]string{}
	sc := bufio.NewScanner(bytes.NewReader(data))
	for n := 1; sc.Scan(); n++ {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) != 2 || !strings.Contains(fields[0], ".") {
			return nil, fmt.Errorf("scriptfp: apimap.txt line %d: want \"<Owner>.<method> <Go name>|%s\"", n, Inline)
		}
		if _, dup := out[fields[0]]; dup {
			return nil, fmt.Errorf("scriptfp: apimap.txt line %d: %s mapped twice", n, fields[0])
		}
		out[fields[0]] = fields[1]
	}
	return out, sc.Err()
}

const censusHeader = "# Engine call census of the reference script classes: generated by cmd/scriptfp, do not edit.\n" +
	"# Format: README.md in this directory.\n"

// Census renders the census of every engine call fps make, with the Go
// name apimap gives each row ("-" when it has none).
func Census(fps []Fingerprint, apimap map[string]string) []byte {
	type tally struct{ classes, sites int }
	rows := map[string]*tally{}
	total := 0
	for _, fp := range fps {
		for row, sites := range fp.Calls {
			t := rows[row]
			if t == nil {
				t = &tally{}
				rows[row] = t
			}
			t.classes++
			t.sites += sites
			total += sites
		}
	}
	var mapped, inline, unmapped, unresolved int
	var body bytes.Buffer
	for _, row := range slices.Sorted(maps.Keys(rows)) {
		goName, ok := apimap[row]
		switch {
		case !ok:
			goName = "-"
			unmapped++
		case goName == Inline:
			inline++
		default:
			mapped++
		}
		if strings.HasPrefix(row, "?.") {
			unresolved++
		}
		fmt.Fprintf(&body, "call %s classes %d sites %d go %s\n", row, rows[row].classes, rows[row].sites, goName)
	}
	var b bytes.Buffer
	b.WriteString(censusHeader)
	fmt.Fprintf(&b, "classes %d sites %d rows %d mapped %d inline %d unmapped %d unresolved %d\n\n",
		len(fps), total, len(rows), mapped, inline, unmapped, unresolved)
	b.Write(body.Bytes())
	return b.Bytes()
}
