package scriptfp

import (
	"bytes"
	"reflect"
	"strings"
	"testing"
)

// The fixture tree under testdata/java holds a stub engine (Quest, Npc,
// Player, Location) and three script classes covering every rule of the
// extractor.
const fixtureReference = `# Static fingerprints of the reference script classes: generated by cmd/scriptfp, do not edit.
# Format: README.md in this directory.
classes 3

class quest.Q900_Fixture extends Quest
  numbers 0.5 2 3 31 57 100 900 3000 30048
  string "30048-01.htm"
  string "Fixture \"quoted\"\n"
  char ";"
  call ?.missing 1
  call Creature.getPosition 1
  call Location.getX 1
  call Location.new 1
  call Npc.getNpcId 3
  call Npc.getObjectId 1
  call Player.getSummons 1
  call Quest.giveItems 1
  call Quest.playSound 1
  hook onAttacked direct same
  hook onCreated direct changed
  hook onDecayed helper same
  hook onTalk none

class script.ai.Base extends Quest
  string "ai"
  call Npc.getNpcId 1
  hook onCreated none

class script.ai.Child extends script.ai.Base
  hook onCreated direct same
`

func TestBuildFixtureTree(t *testing.T) {
	fps, err := Build("testdata/java")
	if err != nil {
		t.Fatalf("Build: %v", err)
	}
	got := string(Render(fps))
	if got != fixtureReference {
		t.Errorf("Render mismatch\n got:\n%s\nwant:\n%s", got, fixtureReference)
	}
	parsed, err := Parse([]byte(got))
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if !reflect.DeepEqual(parsed, fps) {
		t.Errorf("Parse(Render(fps)) differs from fps:\n%+v\n%+v", parsed, fps)
	}
}

func TestCensusFixture(t *testing.T) {
	fps, err := Build("testdata/java")
	if err != nil {
		t.Fatalf("Build: %v", err)
	}
	got := string(Census(fps, map[string]string{"Npc.getNpcId": "ID", "?.missing": Inline}))
	want := `# Engine call census of the reference script classes: generated by cmd/scriptfp, do not edit.
# Format: README.md in this directory.
classes 3 sites 12 rows 9 mapped 1 inline 1 unmapped 7 unresolved 1

call ?.missing classes 1 sites 1 go inline
call Creature.getPosition classes 1 sites 1 go -
call Location.getX classes 1 sites 1 go -
call Location.new classes 1 sites 1 go -
call Npc.getNpcId classes 2 sites 4 go ID
call Npc.getObjectId classes 1 sites 1 go -
call Player.getSummons classes 1 sites 1 go -
call Quest.giveItems classes 1 sites 1 go -
call Quest.playSound classes 1 sites 1 go -
`
	if got != want {
		t.Errorf("Census mismatch\n got:\n%s\nwant:\n%s", got, want)
	}
}

// fixtureAPIMap maps every engine call of the fixture quest, plus one Quest
// helper the quest never calls.
var fixtureAPIMap = map[string]string{
	"?.missing":            Inline,
	"Creature.getPosition": "Player.Position",
	"Location.getX":        "Location.X",
	"Location.new":         "script.NewLocation",
	"Npc.getNpcId":         "NPC.ID",
	"Npc.getObjectId":      "NPC.ObjectID",
	"Player.getSummons":    "Player.Summons",
	"Quest.giveItems":      "script.GiveItems",
	"Quest.playSound":      "script.PlaySound",
	"Quest.takeItems":      "script.TakeItems",
}

func fixtureCheck(t *testing.T, amap map[string]string, dir string, exempt ...string) []string {
	t.Helper()
	fps, err := Build("testdata/java")
	if err != nil {
		t.Fatalf("Build: %v", err)
	}
	problems, err := check(byClass(fps), amap, dir, []string{"quest.Q900_Fixture"}, exempt)
	if err != nil {
		t.Fatalf("check: %v", err)
	}
	return problems
}

func TestCheckFaithfulPortHasNoProblem(t *testing.T) {
	if problems := fixtureCheck(t, fixtureAPIMap, "testdata/go/q900"); len(problems) != 0 {
		t.Errorf("problems for a faithful port:\n%s", strings.Join(problems, "\n"))
	}
}

func TestCheckNamesEveryDifference(t *testing.T) {
	got := fixtureCheck(t, fixtureAPIMap, "testdata/go/q900bad")
	want := []string{
		`quest.Q900_Fixture: call Quest.playSound is in the reference but the Go package never calls script.PlaySound`,
		`quest.Q900_Fixture: call Quest.takeItems is not in the reference but the Go package calls script.TakeItems`,
		`quest.Q900_Fixture: char ";" is in the reference but not in the Go package`,
		`quest.Q900_Fixture: hook onAttacked direct changed is in the Go package but not in the reference`,
		`quest.Q900_Fixture: hook onAttacked direct same is in the reference but not in the Go package`,
		`quest.Q900_Fixture: hook onDecayed helper same is in the reference but not in the Go package`,
		`quest.Q900_Fixture: hook onSeeCreature none is in the Go package but not in the reference`,
		`quest.Q900_Fixture: number 57 is in the reference but not in the Go package`,
		`quest.Q900_Fixture: number 58 is in the Go package but not in the reference`,
		`quest.Q900_Fixture: string "extra" is in the Go package but not in the reference`,
	}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("problems:\n%s\nwant:\n%s", strings.Join(got, "\n"), strings.Join(want, "\n"))
	}
}

func TestCheckUnmappedCallAndExemptions(t *testing.T) {
	amap := map[string]string{}
	for k, v := range fixtureAPIMap {
		amap[k] = v
	}
	delete(amap, "Npc.getObjectId")
	got := fixtureCheck(t, amap, "testdata/go/q900", `char ";"`)
	want := []string{
		`quest.Q900_Fixture: call Npc.getObjectId has no Go name in apimap.txt`,
		`quest.Q900_Fixture: exemption "char \";\"" matches no difference`,
	}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("problems:\n%s\nwant:\n%s", strings.Join(got, "\n"), strings.Join(want, "\n"))
	}

	got = fixtureCheck(t, fixtureAPIMap, "testdata/go/q900bad",
		`number 57`, `number 58`, `string "extra"`, `char ";"`, `call Quest.playSound`, `call Quest.takeItems`,
		`hook onAttacked direct changed`, `hook onAttacked direct same`, `hook onDecayed helper same`,
		`hook onSeeCreature none`)
	if len(got) != 0 {
		t.Errorf("every difference exempted, still reported:\n%s", strings.Join(got, "\n"))
	}
}

func TestCheckRejectsUnknownClass(t *testing.T) {
	if _, err := check(map[string]Fingerprint{}, nil, "testdata/go/q900", []string{"quest.Missing"}, nil); err == nil {
		t.Error("check of an unknown class succeeded")
	}
}

// TestCommittedGoldensAreConsistent runs without the reference checkout:
// the committed fingerprints parse and render back byte for byte, the
// committed census is the census of those fingerprints with apimap.txt, and
// apimap.txt names only census rows.
func TestCommittedGoldensAreConsistent(t *testing.T) {
	fps, err := Parse(committedReference)
	if err != nil {
		t.Fatalf("Parse reference.golden: %v", err)
	}
	if !bytes.Equal(Render(fps), committedReference) {
		t.Fatal("reference.golden does not render back to itself")
	}
	amap, err := APIMap()
	if err != nil {
		t.Fatalf("APIMap: %v", err)
	}
	if !bytes.Equal(Census(fps, amap), committedCensus) {
		t.Fatal("census.golden is stale: regenerate it with go run ./cmd/scriptfp (see the package comment)")
	}
	rows := map[string]bool{}
	for _, fp := range fps {
		for row := range fp.Calls {
			rows[row] = true
		}
	}
	for row := range amap {
		if !rows[row] {
			t.Errorf("apimap.txt maps %s, which no reference class calls", row)
		}
	}
}

func TestParseAPIMapRejectsMalformedLines(t *testing.T) {
	for _, data := range []string{"Quest.giveItems\n", "giveItems GiveItems\n", "Quest.a A\nQuest.a B\n"} {
		if _, err := parseAPIMap([]byte(data)); err == nil {
			t.Errorf("parseAPIMap(%q) succeeded", data)
		}
	}
	got, err := parseAPIMap([]byte("# comment\n\nQuest.giveItems script.GiveItems\nPlayer.getStatus inline\n"))
	if err != nil {
		t.Fatalf("parseAPIMap: %v", err)
	}
	if want := map[string]string{"Quest.giveItems": "script.GiveItems", "Player.getStatus": Inline}; !reflect.DeepEqual(got, want) {
		t.Errorf("parseAPIMap = %v, want %v", got, want)
	}
}
