package crypt

import (
	"bytes"
	"testing"
)

// testPattern returns a deterministic byte sequence used as plaintext in the
// oracle vectors below, matching the generator used against the reference
// Java implementation: pattern[i] = byte(i*0x11 + 1).
func testPattern(n int) []byte {
	b := make([]byte, n)
	for i := range b {
		b[i] = byte(i*0x11 + 1)
	}
	return b
}

// Expected checksums were generated by running the reference Java
// NewCrypt.appendChecksum/verifyChecksum against each buffer.
func TestAppendAndVerifyChecksum(t *testing.T) {
	t.Run("24 byte buffer", func(t *testing.T) {
		buf := testPattern(24)
		AppendChecksum(buf)
		want := mustHex(t, "0112233445566778899aabbccddeef0011223344112233b4")
		if !bytes.Equal(buf, want) {
			t.Fatalf("AppendChecksum() = %x, want %x", buf, want)
		}
		if !VerifyChecksum(buf) {
			t.Fatal("VerifyChecksum() = false, want true")
		}
	})

	t.Run("20 byte buffer", func(t *testing.T) {
		buf := testPattern(20)
		AppendChecksum(buf)
		want := mustHex(t, "0112233445566778899aabbccddeef00000000f0")
		if !bytes.Equal(buf, want) {
			t.Fatalf("AppendChecksum() = %x, want %x", buf, want)
		}
	})

	t.Run("corrupted checksum fails verification", func(t *testing.T) {
		buf := testPattern(24)
		AppendChecksum(buf)
		buf[len(buf)-1] ^= 0xFF
		if VerifyChecksum(buf) {
			t.Fatal("VerifyChecksum() = true, want false")
		}
	})

	t.Run("length not a multiple of 4", func(t *testing.T) {
		if VerifyChecksum(testPattern(21)) {
			t.Fatal("VerifyChecksum() = true, want false")
		}
	})

	t.Run("length at or below 4", func(t *testing.T) {
		if VerifyChecksum(testPattern(4)) {
			t.Fatal("VerifyChecksum() = true, want false")
		}
	})
}

// PaddedSize must always add at least one byte of padding, even when size
// already sits on a Blowfish block boundary.
func TestPaddedSize(t *testing.T) {
	tests := []struct{ in, want int }{
		{0, 8}, {1, 8}, {7, 8},
		{8, 16}, {9, 16}, {15, 16},
		{16, 24},
	}
	for _, tt := range tests {
		if got := PaddedSize(tt.in); got != tt.want {
			t.Errorf("PaddedSize(%d) = %d, want %d", tt.in, got, tt.want)
		}
	}
}
