package crypt

import (
	"bytes"
	"encoding/hex"
	"testing"
)

func mustHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("bad hex %q: %v", s, err)
	}
	return b
}

// Expected ciphertexts were generated by running the reference Java
// BlowfishEngine against each (key, plaintext) pair.
func TestBlowfishCipherEncrypt(t *testing.T) {
	tests := []struct {
		name       string
		key        string
		plaintext  string
		ciphertext string
	}{
		{"zero key and block", "0000000000000000", "0000000000000000", "4597f94e78dd9861"},
		{"one byte key", "ab", "0011223344556677", "5e706d4e3aa1f21e"},
		{"eight byte key", "0123456789abcdef", "fedcba9876543210", "e3eff6364e301707"},
		{"ascii key", "4162436445664768", "0000000000000000", "e71255e793029d97"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			c, err := NewBlowfishCipher(mustHex(t, tt.key))
			if err != nil {
				t.Fatalf("NewBlowfishCipher: %v", err)
			}

			plaintext := mustHex(t, tt.plaintext)
			want := mustHex(t, tt.ciphertext)

			got := make([]byte, len(plaintext))
			c.Encrypt(got, plaintext)
			if !bytes.Equal(got, want) {
				t.Fatalf("Encrypt() = %x, want %x", got, want)
			}

			roundtrip := make([]byte, len(got))
			c.Decrypt(roundtrip, got)
			if !bytes.Equal(roundtrip, plaintext) {
				t.Fatalf("Decrypt(Encrypt(p)) = %x, want %x", roundtrip, plaintext)
			}
		})
	}
}

func TestBlowfishCipherMultiBlock(t *testing.T) {
	key := mustHex(t, "6b60cb5b82ce90b1c26732cb164e0eff")
	plaintext := mustHex(t, "00112233445566778899aabbccddeeff0011223344556677")
	want := mustHex(t, "a72503e23e3b4482fd003f5549880b71a72503e23e3b4482")

	c, err := NewBlowfishCipher(key)
	if err != nil {
		t.Fatalf("NewBlowfishCipher: %v", err)
	}

	got := make([]byte, len(plaintext))
	for off := 0; off < len(plaintext); off += BlockSize {
		c.Encrypt(got[off:off+BlockSize], plaintext[off:off+BlockSize])
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("Encrypt() = %x, want %x", got, want)
	}
}

func TestBlowfishCipherEncryptInPlace(t *testing.T) {
	c, err := NewBlowfishCipher(mustHex(t, "0123456789abcdef"))
	if err != nil {
		t.Fatalf("NewBlowfishCipher: %v", err)
	}

	buf := mustHex(t, "fedcba9876543210")
	c.Encrypt(buf, buf)
	if want := mustHex(t, "e3eff6364e301707"); !bytes.Equal(buf, want) {
		t.Fatalf("in-place Encrypt() = %x, want %x", buf, want)
	}

	c.Decrypt(buf, buf)
	if want := mustHex(t, "fedcba9876543210"); !bytes.Equal(buf, want) {
		t.Fatalf("in-place Decrypt() = %x, want %x", buf, want)
	}
}

func TestNewBlowfishCipherRejectsOversizedKey(t *testing.T) {
	if _, err := NewBlowfishCipher(make([]byte, 57)); err == nil {
		t.Fatal("expected error for 57-byte key, got nil")
	}
}
