package crypt

import (
	"bytes"
	"crypto/rand"
	"crypto/rsa"
	"encoding/hex"
	"math/big"
	"testing"
)

// ---- from blockcrypt_test.go ----
// testPattern returns a deterministic byte sequence used as plaintext in the
// oracle vectors below, matching the generator used against the reference
// Java implementation: pattern[i] = byte(i*0x11 + 1).
func testPattern(n int) []byte {
	b := make([]byte, n)
	for i := range b {
		b[i] = byte(i*0x11 + 1)
	}
	return b
}

// Expected checksums were generated by running the reference Java
// NewCrypt.appendChecksum/verifyChecksum against each buffer.
func TestAppendAndVerifyChecksum(t *testing.T) {
	t.Run("24 byte buffer", func(t *testing.T) {
		buf := testPattern(24)
		AppendChecksum(buf)
		want := mustHex(t, "0112233445566778899aabbccddeef0011223344112233b4")
		if !bytes.Equal(buf, want) {
			t.Fatalf("AppendChecksum() = %x, want %x", buf, want)
		}
		if !VerifyChecksum(buf) {
			t.Fatal("VerifyChecksum() = false, want true")
		}
	})

	t.Run("20 byte buffer", func(t *testing.T) {
		buf := testPattern(20)
		AppendChecksum(buf)
		want := mustHex(t, "0112233445566778899aabbccddeef00000000f0")
		if !bytes.Equal(buf, want) {
			t.Fatalf("AppendChecksum() = %x, want %x", buf, want)
		}
	})

	t.Run("corrupted checksum fails verification", func(t *testing.T) {
		buf := testPattern(24)
		AppendChecksum(buf)
		buf[len(buf)-1] ^= 0xFF
		if VerifyChecksum(buf) {
			t.Fatal("VerifyChecksum() = true, want false")
		}
	})

	t.Run("length not a multiple of 4", func(t *testing.T) {
		if VerifyChecksum(testPattern(21)) {
			t.Fatal("VerifyChecksum() = true, want false")
		}
	})

	t.Run("length at or below 4", func(t *testing.T) {
		if VerifyChecksum(testPattern(4)) {
			t.Fatal("VerifyChecksum() = true, want false")
		}
	})
}

// PaddedSize must always add at least one byte of padding, even when size
// already sits on a Blowfish block boundary.
func TestPaddedSize(t *testing.T) {
	tests := []struct{ in, want int }{
		{0, 8}, {1, 8}, {7, 8},
		{8, 16}, {9, 16}, {15, 16},
		{16, 24},
	}
	for _, tt := range tests {
		if got := PaddedSize(tt.in); got != tt.want {
			t.Errorf("PaddedSize(%d) = %d, want %d", tt.in, got, tt.want)
		}
	}
}

// ---- from blowfish_test.go ----
func mustHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("bad hex %q: %v", s, err)
	}
	return b
}

// Expected ciphertexts were generated by running the reference Java
// BlowfishEngine against each (key, plaintext) pair.
func TestBlowfishCipherEncrypt(t *testing.T) {
	tests := []struct {
		name       string
		key        string
		plaintext  string
		ciphertext string
	}{
		{"zero key and block", "0000000000000000", "0000000000000000", "4597f94e78dd9861"},
		{"one byte key", "ab", "0011223344556677", "5e706d4e3aa1f21e"},
		{"eight byte key", "0123456789abcdef", "fedcba9876543210", "e3eff6364e301707"},
		{"ascii key", "4162436445664768", "0000000000000000", "e71255e793029d97"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			c, err := NewBlowfishCipher(mustHex(t, tt.key))
			if err != nil {
				t.Fatalf("NewBlowfishCipher: %v", err)
			}

			plaintext := mustHex(t, tt.plaintext)
			want := mustHex(t, tt.ciphertext)

			got := make([]byte, len(plaintext))
			c.Encrypt(got, plaintext)
			if !bytes.Equal(got, want) {
				t.Fatalf("Encrypt() = %x, want %x", got, want)
			}

			roundtrip := make([]byte, len(got))
			c.Decrypt(roundtrip, got)
			if !bytes.Equal(roundtrip, plaintext) {
				t.Fatalf("Decrypt(Encrypt(p)) = %x, want %x", roundtrip, plaintext)
			}
		})
	}
}

func TestBlowfishCipherMultiBlock(t *testing.T) {
	key := mustHex(t, "6b60cb5b82ce90b1c26732cb164e0eff")
	plaintext := mustHex(t, "00112233445566778899aabbccddeeff0011223344556677")
	want := mustHex(t, "a72503e23e3b4482fd003f5549880b71a72503e23e3b4482")

	c, err := NewBlowfishCipher(key)
	if err != nil {
		t.Fatalf("NewBlowfishCipher: %v", err)
	}

	got := make([]byte, len(plaintext))
	for off := 0; off < len(plaintext); off += BlockSize {
		c.Encrypt(got[off:off+BlockSize], plaintext[off:off+BlockSize])
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("Encrypt() = %x, want %x", got, want)
	}
}

func TestBlowfishCipherEncryptInPlace(t *testing.T) {
	c, err := NewBlowfishCipher(mustHex(t, "0123456789abcdef"))
	if err != nil {
		t.Fatalf("NewBlowfishCipher: %v", err)
	}

	buf := mustHex(t, "fedcba9876543210")
	c.Encrypt(buf, buf)
	if want := mustHex(t, "e3eff6364e301707"); !bytes.Equal(buf, want) {
		t.Fatalf("in-place Encrypt() = %x, want %x", buf, want)
	}

	c.Decrypt(buf, buf)
	if want := mustHex(t, "fedcba9876543210"); !bytes.Equal(buf, want) {
		t.Fatalf("in-place Decrypt() = %x, want %x", buf, want)
	}
}

func TestNewBlowfishCipherRejectsOversizedKey(t *testing.T) {
	if _, err := NewBlowfishCipher(make([]byte, 57)); err == nil {
		t.Fatal("expected error for 57-byte key, got nil")
	}
}

// ---- from link_key_test.go ----
func TestDecryptDynamicKey(t *testing.T) {
	key, err := rsa.GenerateKey(rand.Reader, modulusSize*8)
	if err != nil {
		t.Fatalf("GenerateKey: %v", err)
	}

	tests := []struct {
		name      string
		plaintext []byte
		want      []byte // nil means same as plaintext
	}{
		{name: "16-byte key", plaintext: []byte{0x03, 0x0a, 0x11, 0x18, 0x1f, 0x26, 0x2d, 0x34, 0x3b, 0x42, 0x49, 0x50, 0x57, 0x5e, 0x65, 0x6c}},
		{name: "single byte key", plaintext: []byte{0x2a}},
		// A leading zero byte in the key itself is indistinguishable from the
		// RSA block's own zero padding and gets stripped along with it -
		// matching the reference implementation's identical loop over the
		// decrypted block.
		{name: "leading zero byte in key is stripped like padding", plaintext: []byte{0x00, 0x01, 0x02, 0x03}, want: []byte{0x01, 0x02, 0x03}},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			want := tt.want
			if want == nil {
				want = tt.plaintext
			}
			ciphertext := EncryptDynamicKey(&key.PublicKey, tt.plaintext)
			got := DecryptDynamicKey(key, ciphertext)
			if !bytes.Equal(got, want) {
				t.Fatalf("DecryptDynamicKey() = %x, want %x", got, want)
			}
		})
	}
}

func TestDecryptDynamicKeyEmptyPlaintext(t *testing.T) {
	key, err := rsa.GenerateKey(rand.Reader, modulusSize*8)
	if err != nil {
		t.Fatalf("GenerateKey: %v", err)
	}
	ciphertext := EncryptDynamicKey(&key.PublicKey, nil)
	got := DecryptDynamicKey(key, ciphertext)
	if len(got) != 0 {
		t.Fatalf("DecryptDynamicKey() = %x, want empty", got)
	}
}

func TestDecryptDynamicKeyIntoSetKey(t *testing.T) {
	key, err := rsa.GenerateKey(rand.Reader, modulusSize*8)
	if err != nil {
		t.Fatalf("GenerateKey: %v", err)
	}
	dynamicKey := mustHex(t, "030a11181f262d343b424950575e656c")
	ciphertext := EncryptDynamicKey(&key.PublicKey, dynamicKey)

	enc := NewLinkCrypt()
	if err := enc.SetKey(DecryptDynamicKey(key, ciphertext)); err != nil {
		t.Fatalf("SetKey: %v", err)
	}
	dec := NewLinkCrypt()
	if err := dec.SetKey(dynamicKey); err != nil {
		t.Fatalf("SetKey: %v", err)
	}

	payload := []byte("hello, gameserver link")
	got := enc.Encrypt(payload)
	if err := dec.Decrypt(got); err != nil {
		t.Fatalf("Decrypt: %v", err)
	}
	if !bytes.Equal(got[:len(payload)], payload) {
		t.Fatalf("round trip = %x, want prefix %x", got, payload)
	}
}

// ---- from link_test.go ----
// Vectors generated by running the reference Java NewCrypt/BlowfishEngine
// implementation against the link's static bootstrap key and an arbitrary
// dynamic key.
func TestLinkCrypt(t *testing.T) {
	tests := []struct {
		name          string
		dynamicKey    string // hex; empty means use the static bootstrap key
		payload       string // hex
		paddedChecked string // hex; payload padded to a block boundary with checksum appended
		encrypted     string // hex
	}{
		{
			name:          "static key short payload",
			payload:       "002a010200000102",
			paddedChecked: "002a01020000010200000000002a0000",
			encrypted:     "f25ce8b8add7223a160c8c70d90e5fe2",
		},
		{
			name:          "dynamic 16-byte key",
			dynamicKey:    "030a11181f262d343b424950575e656c",
			payload:       "68656c6c6f2c2067616d65736572766572206c696e6b",
			paddedChecked: "68656c6c6f2c2067616d65736572766572206c696e6b0000000000001f1d3374",
			encrypted:     "5bb1ad8e8666b39d8ea4daf92c1cc3ddbb905030d0cfd7f915d5066108f433a4",
		},
		{
			name:          "static key empty payload",
			payload:       "",
			paddedChecked: "0000000000000000",
			encrypted:     "a0e5510c42277db7",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			payload := mustDecodeHex(t, tt.payload)
			wantPadded := mustDecodeHex(t, tt.paddedChecked)
			wantEncrypted := mustDecodeHex(t, tt.encrypted)

			enc := NewLinkCrypt()
			dec := NewLinkCrypt()
			if tt.dynamicKey != "" {
				key := mustDecodeHex(t, tt.dynamicKey)
				if err := enc.SetKey(key); err != nil {
					t.Fatalf("SetKey(enc): %v", err)
				}
				if err := dec.SetKey(key); err != nil {
					t.Fatalf("SetKey(dec): %v", err)
				}
			}

			got := enc.Encrypt(payload)
			if hex.EncodeToString(got) != hex.EncodeToString(wantEncrypted) {
				t.Fatalf("Encrypt() = %x, want %x", got, wantEncrypted)
			}

			decrypted := append([]byte(nil), got...)
			if err := dec.Decrypt(decrypted); err != nil {
				t.Fatalf("Decrypt() error = %v", err)
			}
			if hex.EncodeToString(decrypted) != hex.EncodeToString(wantPadded) {
				t.Fatalf("Decrypt() = %x, want %x", decrypted, wantPadded)
			}
		})
	}
}

func TestLinkCryptDecryptRejectsBadLength(t *testing.T) {
	c := NewLinkCrypt()
	for _, size := range []int{0, 3, 7, 9} {
		if err := c.Decrypt(make([]byte, size)); err == nil {
			t.Errorf("Decrypt(len=%d) expected error, got nil", size)
		}
	}
}

func TestLinkCryptDecryptRejectsBadChecksum(t *testing.T) {
	enc := NewLinkCrypt()
	payload := enc.Encrypt([]byte("tamper me"))
	payload[0] ^= 0xff

	dec := NewLinkCrypt()
	if err := dec.Decrypt(payload); err == nil {
		t.Error("Decrypt() with tampered ciphertext expected error, got nil")
	}
}

func mustDecodeHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("decode hex %q: %v", s, err)
	}
	return b
}

// ---- from rsakey_test.go ----
// Expected scrambled moduli were generated by running the reference Java
// ScrambledKeyPair.scrambleModulus against each modulus value.
func TestScrambleModulus(t *testing.T) {
	tests := []struct {
		name      string
		modulus   string // hex, as produced by Java's BigInteger.toByteArray() (may carry a leading sign byte)
		scrambled string
	}{
		{
			name:      "128-byte modulus",
			modulus:   "59170fbb183477a35a94c9bf390b770209d32a595d4a987d41f4b3e592471abe05194bb55dcab3910016175aa147e1f3e98ee81edf7fae40bfe793d9fced52b202e34d15e5c4caaf166fc2edcea4fb1b65e240a4e944b31d0705e6c8b71cf8bdfc97c696693058b22edd1479f1953297e1c82141a6a46d99364cf461b317c99f",
			scrambled: "a6185670fdf0bd0c4cfb0b52f72bbbce6b316afdb40e2b6046f1552d255be203f98e8d2334faeb232ecb032350d2d3640846c95f79dbc3d989ab67b84ffa9b2da4fb1b65183477a35a94c9bf3972acc1d0d32a595d4a987d41f4b3e592471abe05194bb55dcab3910016175aa147e1f3e98ee81edf7fae40bfe793d9fced52b2",
		},
		{
			// This modulus's high bit is set, so Java's BigInteger.toByteArray()
			// carries a leading 0x00 sign byte (129 bytes total). Go's
			// big.Int.Bytes() never adds that byte, so scrambleModulus needs no
			// special case to reach the same 128-byte result Java produces
			// after its own strip.
			name:      "leading sign byte from Java BigInteger",
			modulus:   "00ee614cc5a74b029f8f814e38d93995b694aa2150847891d75da8ddddc46434afeb50781ae04364f9b3a3f3707eab79470ba3c885b66c499800da641a22a420ee9989ec985901e416c9c38fbf7ae22a00a4174c64b5144dc69831c2d5e9f8c7dcb1c3a276da03c5c5347dd8728b234273149eb6e9bb0ff5f4111a021c9a0168a9",
			scrambled: "7ba3ec3cfe4ae6894642c187a3da97463dbd6d34316cdc11c5991f082d9cf3735a93da6c3a40a13c87de2b02f5883b341f3d7e6c0d63bc6c11c06606b8a54847e22a00a4a74b029f8f814e38d934f60af8aa2150847891d75da8ddddc46434afeb50781ae04364f9b3a3f3707eab79470ba3c885b66c499800da641a22a420ee",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			modulus := mustHex(t, tt.modulus)
			mod := new(big.Int).SetBytes(modulus)

			got, err := scrambleModulus(mod)
			if err != nil {
				t.Fatalf("scrambleModulus: %v", err)
			}
			want := mustHex(t, tt.scrambled)
			if !bytes.Equal(got, want) {
				t.Fatalf("scrambleModulus() = %x, want %x", got, want)
			}
		})
	}
}

func TestScrambleModulusRejectsWrongSize(t *testing.T) {
	if _, err := scrambleModulus(big.NewInt(12345)); err == nil {
		t.Fatal("expected error for non-1024-bit modulus, got nil")
	}
}

func TestModulusBytes(t *testing.T) {
	tests := []struct {
		name string
		n    string // hex modulus
		want string // hex expected wire bytes
	}{
		{name: "top bit clear needs no padding", n: "7f00ff", want: "7f00ff"},
		{name: "top bit set gets a leading zero", n: "ff00ff", want: "00ff00ff"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			n := new(big.Int).SetBytes(mustHex(t, tt.n))
			got := ModulusBytes(&rsa.PublicKey{N: n})
			want := mustHex(t, tt.want)
			if !bytes.Equal(got, want) {
				t.Fatalf("ModulusBytes() = %x, want %x", got, want)
			}
		})
	}
}

func TestNewLoginKeyPair(t *testing.T) {
	kp, err := NewLoginKeyPair()
	if err != nil {
		t.Fatalf("NewLoginKeyPair: %v", err)
	}
	if kp.Private == nil {
		t.Fatal("Private is nil")
	}
	if got := kp.Private.N.BitLen(); got != modulusSize*8 {
		t.Fatalf("modulus bit length = %d, want %d", got, modulusSize*8)
	}
	if len(kp.ScrambledModulus) != modulusSize {
		t.Fatalf("len(ScrambledModulus) = %d, want %d", len(kp.ScrambledModulus), modulusSize)
	}
}
