package task

import (
	"fmt"
	"sync"
	"testing"
	"time"
)

// Expected values in the tables below were generated by a probe running the
// reference Java implementation's game-time arithmetic
// (GameTimeTaskManager.java, openjdk 21).

func TestGameClockConversions(t *testing.T) {
	tests := []struct {
		minutes   int
		timeOfDay int
		hour      int
		minute    int
		day       int
		night     bool
		formatted string
	}{
		{0, 0, 0, 0, 0, true, "00:00"},
		{1, 1, 0, 1, 0, true, "00:01"},
		{59, 59, 0, 59, 0, true, "00:59"},
		{60, 60, 1, 0, 0, true, "01:00"},
		{61, 61, 1, 1, 0, true, "01:01"},
		{359, 359, 5, 59, 0, true, "05:59"},
		{360, 360, 6, 0, 0, false, "06:00"},
		{361, 361, 6, 1, 0, false, "06:01"},
		{719, 719, 11, 59, 0, false, "11:59"},
		{720, 720, 12, 0, 0, false, "12:00"},
		{1379, 1379, 22, 59, 0, false, "22:59"},
		{1439, 1439, 23, 59, 0, false, "23:59"},
		{1440, 0, 0, 0, 1, true, "00:00"},
		{1441, 1, 0, 1, 1, true, "00:01"},
		{1799, 359, 5, 59, 1, true, "05:59"},
		{1800, 360, 6, 0, 1, false, "06:00"},
		{2879, 1439, 23, 59, 1, false, "23:59"},
		{2880, 0, 0, 0, 2, true, "00:00"},
		{4319, 1439, 23, 59, 2, false, "23:59"},
		{4320, 0, 0, 0, 3, true, "00:00"},
		{100000, 640, 10, 40, 69, false, "10:40"},
	}
	for _, tc := range tests {
		t.Run(fmt.Sprint(tc.minutes), func(t *testing.T) {
			c := &GameClock{minutes: tc.minutes}
			if got := c.TimeOfDay(); got != tc.timeOfDay {
				t.Errorf("TimeOfDay() = %d, want %d", got, tc.timeOfDay)
			}
			if got := c.Hour(); got != tc.hour {
				t.Errorf("Hour() = %d, want %d", got, tc.hour)
			}
			if got := c.Minute(); got != tc.minute {
				t.Errorf("Minute() = %d, want %d", got, tc.minute)
			}
			if got := c.Day(); got != tc.day {
				t.Errorf("Day() = %d, want %d", got, tc.day)
			}
			if got := c.IsNight(); got != tc.night {
				t.Errorf("IsNight() = %v, want %v", got, tc.night)
			}
			if got := c.String(); got != tc.formatted {
				t.Errorf("String() = %q, want %q", got, tc.formatted)
			}
		})
	}
}

func TestGameClockBootAlignment(t *testing.T) {
	midnight := time.Date(2026, 7, 10, 0, 0, 0, 0, time.UTC)
	tests := []struct {
		offset  time.Duration // wall-clock time past midnight at boot
		minutes int
		night   bool
	}{
		{0, 0, true},
		{time.Millisecond, 0, true},
		{9999 * time.Millisecond, 0, true},
		{10000 * time.Millisecond, 1, true},
		{10001 * time.Millisecond, 1, true},
		{19999 * time.Millisecond, 1, true},
		{3599999 * time.Millisecond, 359, true},
		{3600000 * time.Millisecond, 360, false},
		{3600001 * time.Millisecond, 360, false},
		{21599999 * time.Millisecond, 2159, false},
		{21600000 * time.Millisecond, 2160, false},
		{43200000 * time.Millisecond, 4320, true},
		{86399999 * time.Millisecond, 8639, false},
	}
	for _, tc := range tests {
		t.Run(tc.offset.String(), func(t *testing.T) {
			boot := midnight.Add(tc.offset)
			c := NewGameClock(func() time.Time { return boot })
			if c.minutes != tc.minutes {
				t.Errorf("minutes = %d, want %d", c.minutes, tc.minutes)
			}
			if got := c.IsNight(); got != tc.night {
				t.Errorf("IsNight() = %v, want %v", got, tc.night)
			}
			if c.night != tc.night {
				t.Errorf("stored night = %v, want %v", c.night, tc.night)
			}
		})
	}
}

func TestGameClockBootAlignmentUsesLocalMidnight(t *testing.T) {
	zone := time.FixedZone("UTC+3", 3*3600)
	boot := time.Date(2026, 7, 10, 1, 0, 0, 0, zone)
	c := NewGameClock(func() time.Time { return boot })
	if c.minutes != 360 {
		t.Errorf("minutes = %d, want 360 (one real hour past the zone's midnight)", c.minutes)
	}
}

func TestGameClockTickDayNightTransitions(t *testing.T) {
	tests := []struct {
		name      string
		minutes   int
		wantNight bool
		wantTime  int // TimeOfDay a listener must observe when fired
	}{
		{"day breaks at 06:00", 359, false, 360},
		{"night falls at midnight", 1439, true, 0},
		{"day breaks on the second day", 1799, false, 360},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			c := &GameClock{
				minutes: tc.minutes,
				night:   tc.minutes%minutesPerDay < nightEndMinute,
			}
			var fired []bool
			c.OnDayNight(func(night bool) {
				fired = append(fired, night)
				// The clock must be readable from a listener and already
				// show the post-crossing minute.
				if got := c.TimeOfDay(); got != tc.wantTime {
					t.Errorf("TimeOfDay() inside listener = %d, want %d", got, tc.wantTime)
				}
			})

			c.Tick()
			if len(fired) != 1 || fired[0] != tc.wantNight {
				t.Fatalf("after boundary tick fired = %v, want [%v]", fired, tc.wantNight)
			}

			c.Tick()
			if len(fired) != 1 {
				t.Fatalf("non-boundary tick fired listeners: %v", fired)
			}
		})
	}
}

func TestGameClockTickTransitionSequence(t *testing.T) {
	midnight := time.Date(2026, 7, 10, 0, 0, 0, 0, time.UTC)
	c := NewGameClock(func() time.Time { return midnight })
	var fired []bool
	c.OnDayNight(func(night bool) { fired = append(fired, night) })

	// Three in-game half-day boundaries fall within 1800 ticks from
	// midnight: day at 06:00, night at the next midnight, day again.
	for i := 0; i < 1800; i++ {
		c.Tick()
	}
	want := []bool{false, true, false}
	if len(fired) != len(want) {
		t.Fatalf("fired %v, want %v", fired, want)
	}
	for i := range want {
		if fired[i] != want[i] {
			t.Fatalf("fired %v, want %v", fired, want)
		}
	}
	if got := c.Day(); got != 1 {
		t.Errorf("Day() = %d, want 1", got)
	}
}

func TestGameClockUptime(t *testing.T) {
	base := time.Date(2026, 7, 10, 12, 0, 0, 0, time.UTC)
	cur := base
	c := NewGameClock(func() time.Time { return cur })

	cur = base.Add(95 * time.Second)
	if got := c.Uptime(); got != 95*time.Second {
		t.Errorf("Uptime() = %v, want %v", got, 95*time.Second)
	}
}

func TestGameClockConcurrentAccess(t *testing.T) {
	c := NewGameClock(nil)
	var wg sync.WaitGroup
	wg.Add(2)
	go func() {
		defer wg.Done()
		for i := 0; i < 500; i++ {
			c.Tick()
		}
	}()
	go func() {
		defer wg.Done()
		for i := 0; i < 500; i++ {
			_ = c.TimeOfDay()
			_ = c.Hour()
			_ = c.Minute()
			_ = c.Day()
			_ = c.IsNight()
			_ = c.String()
			_ = c.Uptime()
			c.OnDayNight(func(bool) {})
		}
	}()
	wg.Wait()
}
