import java.io.File;
import java.io.PrintWriter;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HexFormat;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Writer of one engine-contract golden file (format: README.md, "Contract golden format").
 * Packet lines are rendered from the wire bytes by {@link #packet}, with every object id
 * of the scenario replaced by its role name, so the golden does not depend on the ids the
 * probe happened to allocate.
 */
final class ContractGolden
{
	private final String _file;
	private final String _title;
	private final String _revision;
	private final List<String> _lines = new ArrayList<>();
	private int _rows;

	ContractGolden(String file, String title, String revision)
	{
		_file = file;
		_title = title;
		_revision = revision;
	}

	/** Starts a table; each source is "path from-to symbol" (path below aCis_gameserver/). */
	void table(String name, String[] sources, String... notes)
	{
		_lines.add("");
		_lines.add("table " + name);
		for (String s : sources)
			_lines.add("source " + s);
		_lines.add("provenance probe " + _revision);
		for (String n : notes)
			_lines.add("note " + n);
	}

	/** Adds a row; kv alternates keys and values. */
	void row(String id, Object... kv)
	{
		final StringBuilder sb = new StringBuilder("row ").append(id);
		for (int i = 0; i + 1 < kv.length; i += 2)
			sb.append(' ').append(kv[i]).append('=').append(value(String.valueOf(kv[i + 1])));
		_lines.add(sb.toString());
		_rows++;
	}

	/** Adds an output line to the last row. */
	void line(String l)
	{
		_lines.add("  " + l);
	}

	void lines(List<String> ls)
	{
		for (String l : ls)
			line(l);
	}

	void write(File dir) throws Exception
	{
		if (_rows == 0)
			throw new IllegalStateException(_file + " has no rows");
		try (PrintWriter w = new PrintWriter(new File(dir, _file), StandardCharsets.UTF_8))
		{
			w.println("# Engine-contract golden produced by the reference probe: generated by run.sh, do not edit.");
			w.println("# " + _title);
			w.println("# Format: internal/gameserver/script/testdata/oracle/README.md, \"Contract golden format\".");
			for (String l : _lines)
				w.println(l);
		}
	}

	/** A field value: bare when it has no space, quote or control character, else quoted. */
	static String value(String v)
	{
		if (!v.isEmpty() && v.chars().allMatch(c -> c > 0x20 && c < 0x7f && c != '"' && c != '\\' && c != '='))
			return v;
		return quote(v);
	}

	/** Double-quoted with backslash escapes for backslash, quote, \n, \r, \t and \\u00XX for other control characters. */
	static String quote(String s)
	{
		final StringBuilder sb = new StringBuilder("\"");
		for (char c : s.toCharArray())
		{
			switch (c)
			{
				case '\\' -> sb.append("\\\\");
				case '"' -> sb.append("\\\"");
				case '\n' -> sb.append("\\n");
				case '\r' -> sb.append("\\r");
				case '\t' -> sb.append("\\t");
				default ->
				{
					if (c < 0x20 || c == 0x7f)
						sb.append(String.format("\\u%04x", (int) c));
					else
						sb.append(c);
				}
			}
		}
		return sb.append('"').toString();
	}

	/**
	 * Renders one captured server packet ("Class hexbody", as the probe wire reports it).
	 * NpcHtmlMessage, SystemMessage, PlaySound, ExShowQuestMark, QuestList and ActionFailed
	 * are decoded; any other packet keeps its class name and hex body.
	 */
	static String packet(String captured, Map<Integer, String> roles)
	{
		final int sp = captured.indexOf(' ');
		final String cls = captured.substring(0, sp);
		final byte[] body = HexFormat.of().parseHex(captured.substring(sp + 1));
		final ByteBuffer b = ByteBuffer.wrap(body).order(ByteOrder.LITTLE_ENDIAN);
		b.get(); // opcode
		switch (cls)
		{
			case "ActionFailed":
				return "S ActionFailed";
			case "NpcHtmlMessage":
			{
				final String obj = role(b.getInt(), roles);
				String html = str(b);
				for (Map.Entry<Integer, String> e : roles.entrySet())
					html = html.replace(String.valueOf(e.getKey()), "{" + e.getValue() + "}");
				return "S NpcHtmlMessage obj=" + obj + " item=" + b.getInt() + " html=" + quote(html);
			}
			case "SystemMessage":
			{
				final StringBuilder sb = new StringBuilder("S SystemMessage id=").append(b.getInt());
				final int n = b.getInt();
				for (int i = 0; i < n; i++)
				{
					final int type = b.getInt();
					sb.append(' ').append(type).append(':');
					switch (type)
					{
						case 0 -> sb.append(quote(str(b)));
						case 4 -> sb.append(b.getInt()).append(',').append(b.getInt());
						case 7 -> sb.append(b.getInt()).append(',').append(b.getInt()).append(',').append(b.getInt());
						default -> sb.append(b.getInt());
					}
				}
				return sb.toString();
			}
			case "PlaySound":
			{
				final int type = b.getInt();
				final String file = str(b);
				return "S PlaySound type=" + type + " file=" + value(file) + " bind=" + b.getInt() + " obj=" + role(b.getInt(), roles) + " loc=" + b.getInt() + "," + b.getInt() + "," + b.getInt() + " delay=" + b.getInt();
			}
			case "ExShowQuestMark":
				b.getShort();
				return "S ExShowQuestMark quest=" + b.getInt();
			case "QuestList":
			{
				final StringBuilder sb = new StringBuilder("S QuestList");
				final int n = b.getShort();
				for (int i = 0; i < n; i++)
					sb.append(' ').append(b.getInt()).append(':').append(String.format("0x%08x", b.getInt()));
				return sb.toString();
			}
			default:
				return "S " + captured;
		}
	}

	/** Renders one captured statement ("sql | p1 | p2"), with role ids replaced. */
	static String sql(String captured, Map<Integer, String> roles)
	{
		final String[] parts = captured.split(" \\| ", -1);
		final StringBuilder sb = new StringBuilder("Q ").append(parts[0]);
		for (int i = 1; i < parts.length; i++)
		{
			String p = parts[i];
			for (Map.Entry<Integer, String> e : roles.entrySet())
				if (p.equals(String.valueOf(e.getKey())))
					p = "{" + e.getValue() + "}";
			sb.append(" | ").append(p);
		}
		return sb.toString();
	}

	private static String role(int id, Map<Integer, String> roles)
	{
		final String r = roles.get(id);
		return r == null ? String.valueOf(id) : r;
	}

	private static String str(ByteBuffer b)
	{
		final StringBuilder sb = new StringBuilder();
		for (char c; (c = b.getChar()) != 0;)
			sb.append(c);
		return sb.toString();
	}

	/** An ordered role map: object id to role name. */
	static Map<Integer, String> roles(Object... kv)
	{
		final Map<Integer, String> m = new LinkedHashMap<>();
		for (int i = 0; i + 1 < kv.length; i += 2)
			m.put((Integer) kv[i], (String) kv[i + 1]);
		return m;
	}
}
