package world

import (
	"bytes"
	"testing"

	"github.com/fatal10110/acis_golang/internal/gameserver/network/serverpackets"
)

// clientStub is an observer that encodes a despawn packet for every object
// it forgets, capturing the payload bytes a connected client would be sent.
type clientStub struct {
	trackedStub
	sent [][]byte
}

func (c *clientStub) Discover(obj Tracked) {}

func (c *clientStub) Forget(obj Tracked) {
	frame := serverpackets.FrameDeleteObject(obj.ObjectID(), false)
	defer frame.Release()
	raw := frame.Bytes()
	payload := make([]byte, len(raw)-2)
	copy(payload, raw[2:])
	c.sent = append(c.sent, payload)
}

func TestDespawnEmitsDeleteObjectPayload(t *testing.T) {
	s := New()

	c := &clientStub{trackedStub: trackedStub{id: 1}}
	s.Spawn(c, 0, 0, 0, 0)

	obj := &trackedStub{id: 268476516}
	s.Spawn(obj, 100, 0, 0, 0)
	s.Despawn(obj)

	// Payload generated by the reference Java implementation's despawn
	// packet for object id 268476516, not seated.
	want := []byte{0x12, 0x64, 0xa0, 0x00, 0x10, 0x01, 0x00, 0x00, 0x00}
	if len(c.sent) != 1 || !bytes.Equal(c.sent[0], want) {
		t.Fatalf("client received %x, want [%x]", c.sent, want)
	}
}
