package formulas

import (
	"math"
	"testing"

	"github.com/fatal10110/acis_golang/internal/gameserver/skill/statbonus"
)

// Expected values in this file were generated by running the reference
// formulas' exact arithmetic (Creature/Skill lookups replaced by plain
// parameters, everything else copied verbatim) under a JVM (OpenJDK 21),
// not hand-derived.

func almostEqual(a, b float64) bool { return math.Abs(a-b) < 1e-9 }

func TestHitRate(t *testing.T) {
	tests := []struct {
		name                     string
		accuracy, evasion, diffZ int
		night, behind, inFront   bool
		want                     int
	}{
		{"even, front", 40, 40, 0, false, false, true, 900},
		{"even, front, high ground", 40, 40, 60, false, false, true, 960},
		{"disadvantaged, low ground, night, behind", 20, 40, -60, true, true, false, 440},
		{"disadvantaged, side", 20, 40, 0, false, false, false, 600},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := HitRate(tt.accuracy, tt.evasion, tt.diffZ, tt.night, tt.behind, tt.inFront)
			if got != tt.want {
				t.Errorf("HitRate() = %d, want %d", got, tt.want)
			}
		})
	}
}

func TestHitRateClamps(t *testing.T) {
	if got := HitRate(500, 0, 0, false, false, true); got != 980 {
		t.Errorf("HitRate() huge advantage = %d, want clamped 980", got)
	}
	if got := HitRate(0, 500, 0, false, false, true); got != 300 {
		t.Errorf("HitRate() huge disadvantage = %d, want clamped 300", got)
	}
}

func TestMissed(t *testing.T) {
	if !Missed(500, 600) {
		t.Error("roll above rate should miss")
	}
	if Missed(500, 400) {
		t.Error("roll below rate should not miss")
	}
}

func TestPosMul(t *testing.T) {
	tests := []struct {
		behind, inFront, crit bool
		want                  float64
	}{
		{true, false, false, 1.2},
		{true, false, true, 1.1},
		{false, false, false, 1.05},
		{false, false, true, 1.025},
		{false, true, false, 1.0},
	}
	for _, tt := range tests {
		if got := PosMul(tt.behind, tt.inFront, tt.crit); got != tt.want {
			t.Errorf("PosMul(%v,%v,%v) = %v, want %v", tt.behind, tt.inFront, tt.crit, got, tt.want)
		}
	}
}

func TestCritSucceedsAndMCritSucceeds(t *testing.T) {
	if !CritSucceeds(500, 400) {
		t.Error("rate above roll should succeed")
	}
	if CritSucceeds(500, 600) {
		t.Error("rate below roll should not succeed")
	}
	if !MCritSucceeds(500, 400) {
		t.Error("mRate above roll should succeed")
	}
}

func TestMagicSuccessRate(t *testing.T) {
	tests := []struct {
		name                                      string
		targetLevel, casterLevel, magicLevel, dep int
		gradePenalty                              bool
		want                                      float64
	}{
		{"equal level", 40, 40, 0, 0, false, 100.0},
		{"target 10 above", 50, 40, 0, 0, false, 464.49977100954766},
		{"target 20 above", 60, 40, 0, 0, false, 2157.600372679222},
		{"target 10 above, weapon grade penalty", 50, 40, 0, 0, true, 6464.499771009548},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := MagicSuccessRate(tt.targetLevel, tt.casterLevel, tt.magicLevel, tt.dep, tt.gradePenalty)
			if !almostEqual(got, tt.want) {
				t.Errorf("MagicSuccessRate() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestMagicSuccessRateCapsAt9900(t *testing.T) {
	got := MagicSuccessRate(200, 1, 0, 0, true)
	if got != 9900 {
		t.Errorf("MagicSuccessRate() = %v, want capped 9900", got)
	}
}

func TestMagicSucceeds(t *testing.T) {
	if !MagicSucceeds(500, 600) {
		t.Error("roll above rate should succeed (not resisted)")
	}
	if MagicSucceeds(500, 400) {
		t.Error("roll below rate should not succeed (resisted)")
	}
}

func TestTimeBetweenAttacks(t *testing.T) {
	if got := TimeBetweenAttacks(300); got != 1666 {
		t.Errorf("TimeBetweenAttacks(300) = %d, want 1666", got)
	}
	if got := TimeBetweenAttacks(6000); got != 100 {
		t.Errorf("TimeBetweenAttacks(6000) = %d, want 100 (floor)", got)
	}
}

func TestAtkSpd(t *testing.T) {
	if got := AtkSpd(false, 0, 300, 433); got != 480 {
		t.Errorf("AtkSpd(physical) = %d, want 480", got)
	}
	if got := AtkSpd(true, 300, 0, 1166); got != 1294 {
		t.Errorf("AtkSpd(magic) = %d, want 1294", got)
	}
}

func TestPhysicalAttackDamage(t *testing.T) {
	nonCrit := PhysicalAttackInput{
		AttackPower: 100, Defence: 50,
		PosMul: 1, ElementalMul: 1, RandomMul: 1, RaceMul: 1, WeaponVulnMul: 1, PvPMul: 1,
	}
	if got := PhysicalAttackDamage(nonCrit); !almostEqual(got, 154.0) {
		t.Errorf("non-crit: PhysicalAttackDamage() = %v, want 154", got)
	}

	nonCritSS := PhysicalAttackInput{
		AttackPower: 100, Defence: 50,
		SoulShot: true,
		PosMul:   1.2, ElementalMul: 1, RandomMul: 1.05, RaceMul: 1, WeaponVulnMul: 1, PvPMul: 1,
	}
	if got := PhysicalAttackDamage(nonCritSS); !almostEqual(got, 388.08) {
		t.Errorf("non-crit+ss: PhysicalAttackDamage() = %v, want 388.08", got)
	}

	crit := PhysicalAttackInput{
		AttackPower: 100, Defence: 50,
		Crit:   true,
		PosMul: 1, ElementalMul: 1, RandomMul: 1, RaceMul: 1, WeaponVulnMul: 1, PvPMul: 1,
		CritDamageMul: 2.0, CritDamagePosMul: 1, CritVulnMul: 1, CritDamageAddBase: 10,
	}
	if got := PhysicalAttackDamage(crit); !almostEqual(got, 639.716) {
		t.Errorf("crit: PhysicalAttackDamage() = %v, want 639.716", got)
	}
}

func TestPhysicalAttackDamageFloor(t *testing.T) {
	tiny := PhysicalAttackInput{
		AttackPower: 0.001, Defence: 1000,
		PosMul: 1, ElementalMul: 1, RandomMul: 1, RaceMul: 1, WeaponVulnMul: 1, PvPMul: 1,
	}
	if got := PhysicalAttackDamage(tiny); got != 1 {
		t.Errorf("PhysicalAttackDamage() below 1 = %v, want floored to 1", got)
	}
}

func TestPhysicalSkillDamage(t *testing.T) {
	noCrit := PhysicalSkillInput{
		AttackPower: 100, SkillPower: 50, Defence: 60,
		RandomMul: 1, RaceMul: 1, WeaponVulnMul: 1, PvPMul: 1, ElementalMul: 1,
	}
	if got := PhysicalSkillDamage(noCrit); !almostEqual(got, 192.5) {
		t.Errorf("no-crit: PhysicalSkillDamage() = %v, want 192.5", got)
	}

	critSS := PhysicalSkillInput{
		AttackPower: 100, SkillPower: 50, Defence: 60,
		Crit: true, SoulShot: true,
		RandomMul: 1, RaceMul: 1, WeaponVulnMul: 1, PvPMul: 1, ElementalMul: 1,
	}
	if got := PhysicalSkillDamage(critSS); !almostEqual(got, 651.9333333333333) {
		t.Errorf("crit+ss: PhysicalSkillDamage() = %v, want 651.9333333333333", got)
	}
}

func TestBlowDamage(t *testing.T) {
	pve := BlowInput{
		AttackPower: 100, SkillPower: 50, Defence: 40,
		RandomMul: 1, PosMul: 1.2,
		CritDamageMul: 1.5, CritDamagePosMul: 1, CritVulnMul: 1, DaggerVulnMul: 1, CritDamageAddBase: 5,
	}
	if got := BlowDamage(pve); !almostEqual(got, 577.5) {
		t.Errorf("pve: BlowDamage() = %v, want 577.5", got)
	}

	pvpSS := BlowInput{
		AttackPower: 100, SkillPower: 50, Defence: 40,
		SoulShot: true, IsPvP: true,
		RandomMul: 1, PosMul: 1.2, PvPMul: 0.9,
		CritDamageMul: 1.5, CritDamagePosMul: 1, CritVulnMul: 1, DaggerVulnMul: 1, CritDamageAddBase: 5,
	}
	if got := BlowDamage(pvpSS); !almostEqual(got, 761.25) {
		t.Errorf("pvp+ss: BlowDamage() = %v, want 761.25", got)
	}
}

func TestMagicDamage(t *testing.T) {
	plain := MagicDamageInput{
		MAtk: 400, MDef: 50, SkillPower: 20,
		PvPMul: 1, ElementalMul: 1,
	}
	if got := MagicDamage(plain); !almostEqual(got, 728.0) {
		t.Errorf("plain: MagicDamage() = %v, want 728", got)
	}

	bssMCrit := MagicDamageInput{
		MAtk: 400, MDef: 50, SkillPower: 20,
		BlessedSoulShot: true, MagicCrit: true,
		PvPMul: 1, ElementalMul: 1,
	}
	if got := MagicDamage(bssMCrit); !almostEqual(got, 5824.0) {
		t.Errorf("bss+mcrit: MagicDamage() = %v, want 5824", got)
	}
}

func TestManaDamage(t *testing.T) {
	in := ManaDamageInput{
		MAtk: 400, MDef: 50, SkillPower: 20, TargetMaxMp: 970,
		VulnMul: 1,
	}
	if got := ManaDamage(in); !almostEqual(got, 80.0) {
		t.Errorf("ManaDamage() = %v, want 80", got)
	}
}

func TestShieldUse(t *testing.T) {
	const dex = 40
	dexMul := statbonus.DEXBonus[dex] // oracle-verified in the statbonus package

	baseRate := 20.0
	rate := baseRate * dexMul // plain rate, no bow/crit multiplier

	if got := ShieldUse(baseRate, dex, false, false, 0, int(rate)-1); got != ShieldSuccess {
		t.Errorf("roll just below rate = %v, want ShieldSuccess", got)
	}
	if got := ShieldUse(baseRate, dex, false, false, 0, int(rate)+1); got != ShieldFailed {
		t.Errorf("roll just above rate = %v, want ShieldFailed", got)
	}
	if got := ShieldUse(0, dex, false, false, 0, 0); got != ShieldFailed {
		t.Errorf("zero base rate = %v, want ShieldFailed", got)
	}
	if got := ShieldUse(baseRate, dex, false, false, 50, 10); got != ShieldPerfect {
		t.Errorf("roll under perfect-block rate = %v, want ShieldPerfect", got)
	}

	// Bow and crit each triple the rate; both together give x9.
	tripled := ShieldUse(baseRate, dex, true, false, 0, int(rate*3)-1)
	if tripled != ShieldSuccess {
		t.Errorf("bow: roll just under tripled rate = %v, want ShieldSuccess", tripled)
	}
}
