package formulas

import (
	"math"
	"testing"

	"github.com/fatal10110/acis_golang/internal/gameserver/skill/statbonus"
)

// ---- from cast_test.go ----
func TestCastBreakRateAndRoll(t *testing.T) {
	rate := CastBreakRate(100, 30, nil)
	const want = 16.055512754639892
	if math.Abs(rate-want) > 0.000000000001 {
		t.Fatalf("CastBreakRate() = %.15f, want %.15f", rate, want)
	}

	doubled := CastBreakRate(100, 30, func(base float64) float64 { return base * 2 })
	if math.Abs(doubled-want*2) > 0.000000000001 {
		t.Fatalf("CastBreakRate() with attack-cancel stat = %.15f, want %.15f", doubled, want*2)
	}

	if !CastBreaks(1, 0) {
		t.Fatal("CastBreaks(1, 0) = false, want true")
	}
	if CastBreaks(99, 99) {
		t.Fatal("CastBreaks(99, 99) = true, want false")
	}
	if !CastBreaks(1000, 98) {
		t.Fatal("CastBreaks clamps high rates to 99 and should beat roll 98")
	}
}

// ---- from formulas_test.go ----
// Expected values in this file were generated by running the reference
// formulas' exact arithmetic (Creature/Skill lookups replaced by plain
// parameters, everything else copied verbatim) under a JVM (OpenJDK 21),
// not hand-derived.

func almostEqual(a, b float64) bool { return math.Abs(a-b) < 1e-9 }

func TestHitRate(t *testing.T) {
	tests := []struct {
		name                     string
		accuracy, evasion, diffZ int
		night, behind, inFront   bool
		want                     int
	}{
		{"even, front", 40, 40, 0, false, false, true, 900},
		{"even, front, high ground", 40, 40, 60, false, false, true, 960},
		{"disadvantaged, low ground, night, behind", 20, 40, -60, true, true, false, 440},
		{"disadvantaged, side", 20, 40, 0, false, false, false, 600},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := HitRate(tt.accuracy, tt.evasion, tt.diffZ, tt.night, tt.behind, tt.inFront)
			if got != tt.want {
				t.Errorf("HitRate() = %d, want %d", got, tt.want)
			}
		})
	}
}

func TestHitRateClamps(t *testing.T) {
	if got := HitRate(500, 0, 0, false, false, true); got != 980 {
		t.Errorf("HitRate() huge advantage = %d, want clamped 980", got)
	}
	if got := HitRate(0, 500, 0, false, false, true); got != 300 {
		t.Errorf("HitRate() huge disadvantage = %d, want clamped 300", got)
	}
}

func TestMissed(t *testing.T) {
	if !Missed(500, 600) {
		t.Error("roll above rate should miss")
	}
	if Missed(500, 400) {
		t.Error("roll below rate should not miss")
	}
}

func TestPosMul(t *testing.T) {
	tests := []struct {
		behind, inFront, crit bool
		want                  float64
	}{
		{true, false, false, 1.2},
		{true, false, true, 1.1},
		{false, false, false, 1.05},
		{false, false, true, 1.025},
		{false, true, false, 1.0},
	}
	for _, tt := range tests {
		if got := PosMul(tt.behind, tt.inFront, tt.crit); got != tt.want {
			t.Errorf("PosMul(%v,%v,%v) = %v, want %v", tt.behind, tt.inFront, tt.crit, got, tt.want)
		}
	}
}

func TestCritSucceedsAndMCritSucceeds(t *testing.T) {
	if !CritSucceeds(500, 400) {
		t.Error("rate above roll should succeed")
	}
	if CritSucceeds(500, 600) {
		t.Error("rate below roll should not succeed")
	}
	if !MCritSucceeds(500, 400) {
		t.Error("mRate above roll should succeed")
	}
}

func TestMagicSuccessRate(t *testing.T) {
	tests := []struct {
		name                                      string
		targetLevel, casterLevel, magicLevel, dep int
		gradePenalty                              bool
		want                                      float64
	}{
		{"equal level", 40, 40, 0, 0, false, 100.0},
		{"target 10 above", 50, 40, 0, 0, false, 464.49977100954766},
		{"target 20 above", 60, 40, 0, 0, false, 2157.600372679222},
		{"target 10 above, weapon grade penalty", 50, 40, 0, 0, true, 6464.499771009548},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := MagicSuccessRate(tt.targetLevel, tt.casterLevel, tt.magicLevel, tt.dep, tt.gradePenalty)
			if !almostEqual(got, tt.want) {
				t.Errorf("MagicSuccessRate() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestMagicSuccessRateCapsAt9900(t *testing.T) {
	got := MagicSuccessRate(200, 1, 0, 0, true)
	if got != 9900 {
		t.Errorf("MagicSuccessRate() = %v, want capped 9900", got)
	}
}

func TestMagicSucceeds(t *testing.T) {
	if !MagicSucceeds(500, 600) {
		t.Error("roll above rate should succeed (not resisted)")
	}
	if MagicSucceeds(500, 400) {
		t.Error("roll below rate should not succeed (resisted)")
	}
}

func TestTimeBetweenAttacks(t *testing.T) {
	if got := TimeBetweenAttacks(300); got != 1666 {
		t.Errorf("TimeBetweenAttacks(300) = %d, want 1666", got)
	}
	if got := TimeBetweenAttacks(6000); got != 100 {
		t.Errorf("TimeBetweenAttacks(6000) = %d, want 100 (floor)", got)
	}
}

func TestAtkSpd(t *testing.T) {
	if got := AtkSpd(false, 0, 300, 433); got != 480 {
		t.Errorf("AtkSpd(physical) = %d, want 480", got)
	}
	if got := AtkSpd(true, 300, 0, 1166); got != 1294 {
		t.Errorf("AtkSpd(magic) = %d, want 1294", got)
	}
}

func TestPhysicalAttackDamage(t *testing.T) {
	nonCrit := PhysicalAttackInput{
		AttackPower: 100, Defence: 50,
		PosMul: 1, ElementalMul: 1, RandomMul: 1, RaceMul: 1, WeaponVulnMul: 1, PvPMul: 1,
	}
	if got := PhysicalAttackDamage(nonCrit); !almostEqual(got, 154.0) {
		t.Errorf("non-crit: PhysicalAttackDamage() = %v, want 154", got)
	}

	nonCritSS := PhysicalAttackInput{
		AttackPower: 100, Defence: 50,
		SoulShot: true,
		PosMul:   1.2, ElementalMul: 1, RandomMul: 1.05, RaceMul: 1, WeaponVulnMul: 1, PvPMul: 1,
	}
	if got := PhysicalAttackDamage(nonCritSS); !almostEqual(got, 388.08) {
		t.Errorf("non-crit+ss: PhysicalAttackDamage() = %v, want 388.08", got)
	}

	crit := PhysicalAttackInput{
		AttackPower: 100, Defence: 50,
		Crit:   true,
		PosMul: 1, ElementalMul: 1, RandomMul: 1, RaceMul: 1, WeaponVulnMul: 1, PvPMul: 1,
		CritDamageMul: 2.0, CritDamagePosMul: 1, CritVulnMul: 1, CritDamageAddBase: 10,
	}
	if got := PhysicalAttackDamage(crit); !almostEqual(got, 639.716) {
		t.Errorf("crit: PhysicalAttackDamage() = %v, want 639.716", got)
	}
}

func TestPhysicalAttackDamageFloor(t *testing.T) {
	tiny := PhysicalAttackInput{
		AttackPower: 0.001, Defence: 1000,
		PosMul: 1, ElementalMul: 1, RandomMul: 1, RaceMul: 1, WeaponVulnMul: 1, PvPMul: 1,
	}
	if got := PhysicalAttackDamage(tiny); got != 1 {
		t.Errorf("PhysicalAttackDamage() below 1 = %v, want floored to 1", got)
	}
}

func TestPhysicalSkillDamage(t *testing.T) {
	noCrit := PhysicalSkillInput{
		AttackPower: 100, SkillPower: 50, Defence: 60,
		RandomMul: 1, RaceMul: 1, WeaponVulnMul: 1, PvPMul: 1, ElementalMul: 1,
	}
	if got := PhysicalSkillDamage(noCrit); !almostEqual(got, 192.5) {
		t.Errorf("no-crit: PhysicalSkillDamage() = %v, want 192.5", got)
	}

	critSS := PhysicalSkillInput{
		AttackPower: 100, SkillPower: 50, Defence: 60,
		Crit: true, SoulShot: true,
		RandomMul: 1, RaceMul: 1, WeaponVulnMul: 1, PvPMul: 1, ElementalMul: 1,
	}
	if got := PhysicalSkillDamage(critSS); !almostEqual(got, 651.9333333333333) {
		t.Errorf("crit+ss: PhysicalSkillDamage() = %v, want 651.9333333333333", got)
	}

	perfectBlock := noCrit
	perfectBlock.Shield = ShieldPerfect
	if got := PhysicalSkillDamage(perfectBlock); got != 1 {
		t.Errorf("perfect-block: PhysicalSkillDamage() = %v, want 1", got)
	}
}

func TestBlowDamage(t *testing.T) {
	pve := BlowInput{
		AttackPower: 100, SkillPower: 50, Defence: 40,
		RandomMul: 1, PosMul: 1.2,
		CritDamageMul: 1.5, CritDamagePosMul: 1, CritVulnMul: 1, DaggerVulnMul: 1, CritDamageAddBase: 5,
	}
	if got := BlowDamage(pve); !almostEqual(got, 577.5) {
		t.Errorf("pve: BlowDamage() = %v, want 577.5", got)
	}

	pvpSS := BlowInput{
		AttackPower: 100, SkillPower: 50, Defence: 40,
		SoulShot: true, IsPvP: true,
		RandomMul: 1, PosMul: 1.2, PvPMul: 0.9,
		CritDamageMul: 1.5, CritDamagePosMul: 1, CritVulnMul: 1, DaggerVulnMul: 1, CritDamageAddBase: 5,
	}
	if got := BlowDamage(pvpSS); !almostEqual(got, 761.25) {
		t.Errorf("pvp+ss: BlowDamage() = %v, want 761.25", got)
	}
}

func TestBlowSucceeds(t *testing.T) {
	tests := []struct {
		name string
		in   BlowRateInput
		roll int
		want bool
	}{
		{
			name: "ordinary blow uses dex stat and side multipliers",
			in:   BlowRateInput{BaseRate: 100, DexMul: 1.1, BlowMul: 1.2},
			roll: 263,
			want: true,
		},
		{
			name: "ordinary blow caps at eight hundred",
			in:   BlowRateInput{BaseRate: 1000, DexMul: 2, BlowMul: 2, Behind: true},
			roll: 800,
			want: false,
		},
		{
			name: "backstab from the front uses its fixed thirty per mille chance",
			in:   BlowRateInput{BaseRate: 1000, Backstab: true, Front: true},
			roll: 30,
			want: false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := BlowSucceeds(tt.in, tt.roll); got != tt.want {
				t.Fatalf("BlowSucceeds() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestMagicAffected(t *testing.T) {
	if !MagicAffected(MagicAffectedInput{MAtk: 100, MDef: 100, VulnMul: 1, Defended: true}, 0.1) {
		t.Fatal("MagicAffected() = false, want true above the zero threshold")
	}
	if MagicAffected(MagicAffectedInput{MAtk: 100, MDef: 200, VulnMul: 1, Defended: true}, 0) {
		t.Fatal("MagicAffected() = true, want false at the strict zero threshold")
	}
	if !MagicAffected(MagicAffectedInput{MAtk: 100, VulnMul: 1}, 0.1) {
		t.Fatal("MagicAffected() = false, want true for an undefended skill")
	}
}

func TestLethalRate(t *testing.T) {
	tests := []struct {
		name string
		in   LethalInput
		want float64
	}{
		{
			name: "no magic level uses attacker target level ratio",
			in:   LethalInput{Chance1: 10, AttackerLevel: 40, TargetLevel: 40, LethalMul: 1},
			want: 100,
		},
		{
			name: "magic level within three levels uses attacker target level ratio",
			in:   LethalInput{Chance1: 15, MagicLevel: 40, AttackerLevel: 40, TargetLevel: 40, LethalMul: 1},
			want: 150,
		},
		{
			name: "magic level four to nine below uses divided penalty",
			in:   LethalInput{Chance1: 30, MagicLevel: 40, AttackerLevel: 40, TargetLevel: 45, LethalMul: 1},
			want: 150,
		},
		{
			name: "magic level ten or more below uses fifteenth penalty",
			in:   LethalInput{Chance1: 30, MagicLevel: 40, AttackerLevel: 40, TargetLevel: 60, LethalMul: 1},
			want: 20,
		},
		{
			name: "lethal stat multiplier scales final per mille rate",
			in:   LethalInput{Chance1: 10, AttackerLevel: 40, TargetLevel: 40, LethalMul: 1.5},
			want: 150,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := LethalRate(tt.in, tt.in.Chance1); !almostEqual(got, tt.want) {
				t.Fatalf("LethalRate() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestLethalHitRollsSecondTierBeforeFirst(t *testing.T) {
	in := LethalInput{
		Chance1:       10,
		Chance2:       1,
		MagicLevel:    0,
		AttackerLevel: 40,
		TargetLevel:   40,
		LethalMul:     1,
	}
	rolls := []int{10, 99}
	calls := 0
	outcome := LethalHit(in, func(n int) int {
		if n != 1000 {
			t.Fatalf("roll bound = %d, want 1000", n)
		}
		roll := rolls[calls]
		calls++
		return roll
	})
	if outcome != LethalHalf {
		t.Fatalf("LethalHit() = %v, want LethalHalf", outcome)
	}
	if calls != 2 {
		t.Fatalf("roll calls = %d, want 2", calls)
	}

	in.Chance2 = 100
	outcome = LethalHit(in, func(int) int { return 999 })
	if outcome != LethalFull {
		t.Fatalf("LethalHit() with guaranteed second tier = %v, want LethalFull", outcome)
	}
}

func TestMagicDamage(t *testing.T) {
	plain := MagicDamageInput{
		MAtk: 400, MDef: 50, SkillPower: 20,
		PvPMul: 1, ElementalMul: 1,
	}
	if got := MagicDamage(plain); !almostEqual(got, 728.0) {
		t.Errorf("plain: MagicDamage() = %v, want 728", got)
	}

	bssMCrit := MagicDamageInput{
		MAtk: 400, MDef: 50, SkillPower: 20,
		BlessedSoulShot: true, MagicCrit: true,
		PvPMul: 1, ElementalMul: 1,
	}
	if got := MagicDamage(bssMCrit); !almostEqual(got, 5824.0) {
		t.Errorf("bss+mcrit: MagicDamage() = %v, want 5824", got)
	}
}

func TestManaDamage(t *testing.T) {
	in := ManaDamageInput{
		MAtk: 400, MDef: 50, SkillPower: 20, TargetMaxMp: 970,
		VulnMul: 1,
	}
	if got := ManaDamage(in); !almostEqual(got, 80.0) {
		t.Errorf("ManaDamage() = %v, want 80", got)
	}
}

func TestShieldUse(t *testing.T) {
	const dex = 40
	dexMul := statbonus.DEXBonus[dex] // oracle-verified in the statbonus package

	baseRate := 20.0
	rate := baseRate * dexMul // plain rate, no bow/crit multiplier

	if got := ShieldUse(baseRate, dex, false, false, 0, int(rate)-1); got != ShieldSuccess {
		t.Errorf("roll just below rate = %v, want ShieldSuccess", got)
	}
	if got := ShieldUse(baseRate, dex, false, false, 0, int(rate)+1); got != ShieldFailed {
		t.Errorf("roll just above rate = %v, want ShieldFailed", got)
	}
	if got := ShieldUse(0, dex, false, false, 0, 0); got != ShieldFailed {
		t.Errorf("zero base rate = %v, want ShieldFailed", got)
	}
	if got := ShieldUse(baseRate, dex, false, false, 50, 10); got != ShieldPerfect {
		t.Errorf("roll under perfect-block rate = %v, want ShieldPerfect", got)
	}

	// Bow and crit each triple the rate; both together give x9.
	tripled := ShieldUse(baseRate, dex, true, false, 0, int(rate*3)-1)
	if tripled != ShieldSuccess {
		t.Errorf("bow: roll just under tripled rate = %v, want ShieldSuccess", tripled)
	}
}

// ---- from manor_test.go ----
func TestHarvestSuccessRate(t *testing.T) {
	tests := []struct {
		name      string
		levelDiff int
		want      int
	}{
		{"no gap", 0, 100},
		{"gap at threshold", 5, 100},
		{"one past threshold", 6, 95},
		{"floored at 1", 25, 1},
		{"negative diff treated as absolute", -6, 95},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := HarvestSuccessRate(tt.levelDiff); got != tt.want {
				t.Errorf("HarvestSuccessRate(%d) = %d, want %d", tt.levelDiff, got, tt.want)
			}
		})
	}
}

func TestSowSuccessRate(t *testing.T) {
	tests := []struct {
		name                                string
		seedLevel, targetLevel, playerLevel int
		alternative                         bool
		want                                int
	}{
		{"in range, normal seed", 40, 40, 40, false, 90},
		{"in range, alternative seed", 40, 40, 40, true, 20},
		{"target above seed range", 40, 50, 50, false, 65},
		{"target below seed range", 40, 25, 25, false, 40},
		{"player-target level gap", 40, 40, 60, false, 15},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := SowSuccessRate(tt.seedLevel, tt.targetLevel, tt.playerLevel, tt.alternative)
			if got != tt.want {
				t.Errorf("SowSuccessRate() = %d, want %d", got, tt.want)
			}
		})
	}
}

// ---- from skillsuccess_test.go ----
// Expected values below are the reference formula's exact arithmetic
// (Rnd.get(...) replaced by an explicit roll parameter) evaluated by hand
// on inputs chosen to make each branch and clamp boundary unambiguous.

func TestSkillSuccessRate(t *testing.T) {
	tests := []struct {
		name string
		in   SkillSuccessInput
		want float64
	}{
		{"identity modifiers", SkillSuccessInput{BaseChance: 50, StatModifier: 1, VulnModifier: 1, MAtkModifier: 1, LevelModifier: 1}, 50},
		{"clamped low", SkillSuccessInput{BaseChance: 1, StatModifier: 0.001, VulnModifier: 1, MAtkModifier: 1, LevelModifier: 1}, 1},
		{"clamped high", SkillSuccessInput{BaseChance: 500, StatModifier: 1, VulnModifier: 1, MAtkModifier: 1, LevelModifier: 1}, 99},
		{"ignores resists, uncapped", SkillSuccessInput{BaseChance: 150, IgnoreResists: true}, 150},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := SkillSuccessRate(tt.in); got != tt.want {
				t.Errorf("SkillSuccessRate() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestSkillSucceeds(t *testing.T) {
	if !SkillSucceeds(50, 49) {
		t.Error("SkillSucceeds(50, 49) = false, want true")
	}
	if SkillSucceeds(50, 50) {
		t.Error("SkillSucceeds(50, 50) = true, want false")
	}
}

func TestSkillReflects(t *testing.T) {
	tests := []struct {
		name string
		in   SkillReflectInput
		roll int
		want bool
	}{
		{"magic lands", SkillReflectInput{CanBeReflected: true, Magic: true, ReflectChance: 30}, 29, true},
		{"magic misses", SkillReflectInput{CanBeReflected: true, Magic: true, ReflectChance: 30}, 30, false},
		{"melee within range lands", SkillReflectInput{CanBeReflected: true, Magic: false, CastRange: 40, ReflectChance: 10}, 9, true},
		{"melee beyond range never reflects", SkillReflectInput{CanBeReflected: true, Magic: false, CastRange: 41, ReflectChance: 100}, 0, false},
		{"melee with no cast range never reflects", SkillReflectInput{CanBeReflected: true, Magic: false, CastRange: -1, ReflectChance: 100}, 0, false},
		{"ignores resists never reflects", SkillReflectInput{IgnoreResists: true, CanBeReflected: true, Magic: true, ReflectChance: 100}, 0, false},
		{"cannot be reflected", SkillReflectInput{CanBeReflected: false, Magic: true, ReflectChance: 100}, 0, false},
		{"excluded type BUFF never reflects", SkillReflectInput{CanBeReflected: true, Magic: true, SkillType: "BUFF", ReflectChance: 100}, 0, false},
		{"excluded type HOT never reflects", SkillReflectInput{CanBeReflected: true, Magic: true, SkillType: "HOT", ReflectChance: 100}, 0, false},
		{"non-excluded type still reflects", SkillReflectInput{CanBeReflected: true, Magic: true, SkillType: "DEBUFF", ReflectChance: 100}, 0, true},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := SkillReflects(tt.in, tt.roll); got != tt.want {
				t.Errorf("SkillReflects() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestRevivePower(t *testing.T) {
	tests := []struct {
		name            string
		witBonus, power float64
		want            float64
	}{
		{"zero power passes through", 2.0, 0, 0},
		{"full power passes through", 0.1, 100, 100},
		{"neutral bonus", 1.0, 50, 50},
		{"bonus adds 20 once past threshold", 2.0, 50, 90},
		{"malus floored at base", 0.5, 50, 50},
		{"hard cap at 90", 1.5, 80, 90},
		{"below threshold no bonus added", 1.3, 50, 65},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := RevivePower(tt.witBonus, tt.power); got != tt.want {
				t.Errorf("RevivePower() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestCancelSuccessRate(t *testing.T) {
	tests := []struct {
		name                    string
		effectPeriod, diffLevel int
		baseRate, vuln          float64
		minRate, maxRate        int
		want                    float64
	}{
		{"mid range", 240, 5, 50, 1, 25, 75, 62},
		{"clamped to min", 240, -100, 50, 1, 25, 75, 25},
		{"clamped to max", 240, 100, 50, 1, 25, 75, 75},
		{"integer division floors", 239, 0, 0, 1, 0, 100, 1},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := CancelSuccessRate(tt.effectPeriod, tt.diffLevel, tt.baseRate, tt.vuln, tt.minRate, tt.maxRate)
			if got != tt.want {
				t.Errorf("CancelSuccessRate() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestCancelSucceeds(t *testing.T) {
	if !CancelSucceeds(62, 61) {
		t.Error("CancelSucceeds(62, 61) = false, want true")
	}
	if CancelSucceeds(62, 62) {
		t.Error("CancelSucceeds(62, 62) = true, want false")
	}
}

// TestEffectCancelDebuffSuccessRate's expected values were generated by
// running the reference formula's exact arithmetic (int-truncated
// vulnerability multiplied through the whole additive rate, remaining
// seconds divided by 1200, then clamped to [25, 75]) standalone rather
// than derived by hand, since the truncate-then-multiply order is easy to
// get backwards.
func TestEffectCancelDebuffSuccessRate(t *testing.T) {
	tests := []struct {
		name                string
		casterMagicLevel    int
		candidateMagicLevel int
		remainingSeconds    int
		vuln                float64
		want                int
	}{
		{"floor clamp when vuln truncates to zero", 1, 1, 0, 0.0, 25},
		{"unclamped, vuln truncates to one", 20, 1, 0, 1.0, 38},
		{"seconds term floors below 1200", 20, 1, 1199, 1.0, 38},
		{"seconds term steps at exactly 1200", 20, 1, 1200, 1.0, 39},
		{"near-2.0 vuln still truncates to one, not two", 1, 1, 36000, 1.99, 30},
		{"vuln of 2.0 doubles the whole rate", 1, 1, 36000, 2.0, 60},
		{"ceiling clamp with vuln truncated to two", 76, 1, 36000, 2.0, 75},
		{"negative diff clamps to floor", 1, 80, 0, 1.0, 25},
		{"equal levels, short remaining, clamps to floor", 40, 40, 1200, 1.0, 25},
		{"negative vuln truncates toward zero, not down", 1, 1, 0, -0.5, 25},
		{"unclamped mid-range", 35, 20, 0, 1.0, 30},
		{"unclamped mid-range with seconds term", 40, 20, 1200, 1.0, 41},
		{"unclamped mid-range, higher", 45, 20, 2400, 1.0, 52},
		{"vuln of two pushes an unclamped case into the ceiling", 45, 20, 2400, 2.0, 75},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := EffectCancelDebuffSuccessRate(tt.casterMagicLevel, tt.candidateMagicLevel, tt.remainingSeconds, tt.vuln)
			if got != tt.want {
				t.Errorf("EffectCancelDebuffSuccessRate() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestEffectCancelSuccessRate(t *testing.T) {
	tests := []struct {
		name                string
		casterMagicLevel    int
		candidateMagicLevel int
		period              int
		power, vuln         float64
		want                int
	}{
		{"mid range", 50, 40, 240, 10, 1, 32},
		{"clamped to min", 10, 50, 0, 0, 1, 25},
		{"clamped to max", 100, 0, 0, 0, 1, 75},
		{"power*vuln truncates toward zero, not rounds", 13, 0, 0, 2.9, 1, 28},
		{"period term floors, not rounds", 13, 0, 239, 0, 1, 27},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := EffectCancelSuccessRate(tt.casterMagicLevel, tt.candidateMagicLevel, tt.period, tt.power, tt.vuln)
			if got != tt.want {
				t.Errorf("EffectCancelSuccessRate() = %v, want %v", got, tt.want)
			}
		})
	}
}

// ---- from unlock_test.go ----
func TestDoorUnlockSpecialSucceeds(t *testing.T) {
	if !DoorUnlockSpecialSucceeds(50, 49) {
		t.Error("DoorUnlockSpecialSucceeds(50, 49) = false, want true")
	}
	if DoorUnlockSpecialSucceeds(50, 50) {
		t.Error("DoorUnlockSpecialSucceeds(50, 50) = true, want false")
	}
}

func TestDoorUnlockRate(t *testing.T) {
	tests := []struct {
		level int
		want  int
	}{
		{0, 0}, {1, 30}, {2, 50}, {3, 75}, {4, 100}, {100, 100},
	}
	for _, tt := range tests {
		if got := DoorUnlockRate(tt.level); got != tt.want {
			t.Errorf("DoorUnlockRate(%d) = %d, want %d", tt.level, got, tt.want)
		}
	}
}

func TestDoorUnlockSucceeds(t *testing.T) {
	if !DoorUnlockSucceeds(2, 49) {
		t.Error("DoorUnlockSucceeds(2, 49) = false, want true")
	}
	if DoorUnlockSucceeds(2, 50) {
		t.Error("DoorUnlockSucceeds(2, 50) = true, want false")
	}
	if DoorUnlockSucceeds(0, 0) {
		t.Error("DoorUnlockSucceeds(0, 0) = true, want false")
	}
}

func TestChestUnlockDeluxeKeyRate(t *testing.T) {
	tests := []struct {
		name              string
		level, skillLevel int
		regularKey        bool
		want              int
	}{
		{"deluxe key, exact match", 100, 10, false, 100},
		{"regular key, exact match", 100, 10, true, 60},
		{"mismatch goes negative uncapped", 125, 8, false, -60},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := ChestUnlockDeluxeKeyRate(tt.level, tt.skillLevel, tt.regularKey)
			if got != tt.want {
				t.Errorf("ChestUnlockDeluxeKeyRate() = %d, want %d", got, tt.want)
			}
		})
	}
}

func TestChestUnlockRate(t *testing.T) {
	tests := []struct {
		name              string
		level, skillLevel int
		wantChance        int
		wantDefinite      bool
		wantSucceeds      bool
	}{
		{"above 60, too low", 70, 9, 0, true, false},
		{"above 60, at threshold", 70, 10, 30, false, false},
		{"above 60, exactly at cap", 70, 14, 50, false, false},
		{"above 60, capped", 70, 20, 50, false, false},
		{"above 40, too low", 50, 5, 0, true, false},
		{"above 40, at threshold", 50, 6, 10, false, false},
		{"above 30, too low", 35, 2, 0, true, false},
		{"above 30, definite success", 35, 13, 0, true, true},
		{"above 30, capped", 35, 12, 50, false, false},
		{"base bracket, definite success", 20, 11, 0, true, true},
		{"base bracket, capped", 20, 10, 50, false, false},
		{"base bracket, uncapped", 20, 0, 35, false, false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			chance, definite, succeeds := ChestUnlockRate(tt.level, tt.skillLevel)
			if chance != tt.wantChance || definite != tt.wantDefinite || succeeds != tt.wantSucceeds {
				t.Errorf("ChestUnlockRate(%d, %d) = (%d, %v, %v), want (%d, %v, %v)",
					tt.level, tt.skillLevel, chance, definite, succeeds, tt.wantChance, tt.wantDefinite, tt.wantSucceeds)
			}
		})
	}
}
