package crypt

import (
	"encoding/hex"
	"testing"
)

// Vectors generated by running the reference Java NewCrypt/BlowfishEngine
// implementation against the link's static bootstrap key and an arbitrary
// dynamic key.
func TestLinkCrypt(t *testing.T) {
	tests := []struct {
		name          string
		dynamicKey    string // hex; empty means use the static bootstrap key
		payload       string // hex
		paddedChecked string // hex; payload padded to a block boundary with checksum appended
		encrypted     string // hex
	}{
		{
			name:          "static key short payload",
			payload:       "002a010200000102",
			paddedChecked: "002a01020000010200000000002a0000",
			encrypted:     "f25ce8b8add7223a160c8c70d90e5fe2",
		},
		{
			name:          "dynamic 16-byte key",
			dynamicKey:    "030a11181f262d343b424950575e656c",
			payload:       "68656c6c6f2c2067616d65736572766572206c696e6b",
			paddedChecked: "68656c6c6f2c2067616d65736572766572206c696e6b0000000000001f1d3374",
			encrypted:     "5bb1ad8e8666b39d8ea4daf92c1cc3ddbb905030d0cfd7f915d5066108f433a4",
		},
		{
			name:          "static key empty payload",
			payload:       "",
			paddedChecked: "0000000000000000",
			encrypted:     "a0e5510c42277db7",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			payload := mustDecodeHex(t, tt.payload)
			wantPadded := mustDecodeHex(t, tt.paddedChecked)
			wantEncrypted := mustDecodeHex(t, tt.encrypted)

			enc := NewLinkCrypt()
			dec := NewLinkCrypt()
			if tt.dynamicKey != "" {
				key := mustDecodeHex(t, tt.dynamicKey)
				if err := enc.SetKey(key); err != nil {
					t.Fatalf("SetKey(enc): %v", err)
				}
				if err := dec.SetKey(key); err != nil {
					t.Fatalf("SetKey(dec): %v", err)
				}
			}

			got := enc.Encrypt(payload)
			if hex.EncodeToString(got) != hex.EncodeToString(wantEncrypted) {
				t.Fatalf("Encrypt() = %x, want %x", got, wantEncrypted)
			}

			decrypted := append([]byte(nil), got...)
			if err := dec.Decrypt(decrypted); err != nil {
				t.Fatalf("Decrypt() error = %v", err)
			}
			if hex.EncodeToString(decrypted) != hex.EncodeToString(wantPadded) {
				t.Fatalf("Decrypt() = %x, want %x", decrypted, wantPadded)
			}
		})
	}
}

func TestLinkCryptDecryptRejectsBadLength(t *testing.T) {
	c := NewLinkCrypt()
	for _, size := range []int{0, 3, 7, 9} {
		if err := c.Decrypt(make([]byte, size)); err == nil {
			t.Errorf("Decrypt(len=%d) expected error, got nil", size)
		}
	}
}

func TestLinkCryptDecryptRejectsBadChecksum(t *testing.T) {
	enc := NewLinkCrypt()
	payload := enc.Encrypt([]byte("tamper me"))
	payload[0] ^= 0xff

	dec := NewLinkCrypt()
	if err := dec.Decrypt(payload); err == nil {
		t.Error("Decrypt() with tampered ciphertext expected error, got nil")
	}
}

func mustDecodeHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("decode hex %q: %v", s, err)
	}
	return b
}
