package crypt

import (
	"bytes"
	"testing"
)

// testPattern returns a deterministic byte sequence used as plaintext in the
// oracle vectors below, matching the generator used against the reference
// Java implementation: pattern[i] = byte(i*0x11 + 1).
func testPattern(n int) []byte {
	b := make([]byte, n)
	for i := range b {
		b[i] = byte(i*0x11 + 1)
	}
	return b
}

// Expected checksums were generated by running the reference Java
// NewCrypt.appendChecksum/verifyChecksum against each buffer.
func TestAppendAndVerifyChecksum(t *testing.T) {
	t.Run("24 byte buffer", func(t *testing.T) {
		buf := testPattern(24)
		appendChecksum(buf)
		want := mustHex(t, "0112233445566778899aabbccddeef0011223344112233b4")
		if !bytes.Equal(buf, want) {
			t.Fatalf("appendChecksum() = %x, want %x", buf, want)
		}
		if !verifyChecksum(buf) {
			t.Fatal("verifyChecksum() = false, want true")
		}
	})

	t.Run("20 byte buffer", func(t *testing.T) {
		buf := testPattern(20)
		appendChecksum(buf)
		want := mustHex(t, "0112233445566778899aabbccddeef00000000f0")
		if !bytes.Equal(buf, want) {
			t.Fatalf("appendChecksum() = %x, want %x", buf, want)
		}
	})

	t.Run("corrupted checksum fails verification", func(t *testing.T) {
		buf := testPattern(24)
		appendChecksum(buf)
		buf[len(buf)-1] ^= 0xFF
		if verifyChecksum(buf) {
			t.Fatal("verifyChecksum() = true, want false")
		}
	})

	t.Run("length not a multiple of 4", func(t *testing.T) {
		if verifyChecksum(testPattern(21)) {
			t.Fatal("verifyChecksum() = true, want false")
		}
	})

	t.Run("length at or below 4", func(t *testing.T) {
		if verifyChecksum(testPattern(4)) {
			t.Fatal("verifyChecksum() = true, want false")
		}
	})
}

// Expected outputs were generated by running the reference Java
// NewCrypt.encXORPass against each (buffer, key) pair, called directly with
// an explicit key so the result doesn't depend on Java's PRNG.
func TestXorPass(t *testing.T) {
	t.Run("pattern buffer", func(t *testing.T) {
		buf := testPattern(24)
		xorPass(buf, 0x12345678)
		want := mustHex(t, "01122334f8fafcf2cfddecfbdef8d8481326374855667788")
		if !bytes.Equal(buf, want) {
			t.Fatalf("xorPass() = %x, want %x", buf, want)
		}
	})

	t.Run("zero buffer zero key", func(t *testing.T) {
		buf := make([]byte, 24)
		xorPass(buf, 0)
		want := make([]byte, 24)
		if !bytes.Equal(buf, want) {
			t.Fatalf("xorPass() = %x, want %x", buf, want)
		}
	})
}

// paddedSize must always add at least one byte of padding, even when size
// already sits on a Blowfish block boundary (matches
// LoginCrypt.encrypt's `size += 8 - size % 8`).
func TestPaddedSize(t *testing.T) {
	tests := []struct{ in, want int }{
		{0, 8}, {1, 8}, {7, 8},
		{8, 16}, {9, 16}, {15, 16},
		{16, 24},
	}
	for _, tt := range tests {
		if got := paddedSize(tt.in); got != tt.want {
			t.Errorf("paddedSize(%d) = %d, want %d", tt.in, got, tt.want)
		}
	}
}

// Expected ciphertext was generated by running the reference Java
// LoginCrypt.encrypt's static-key branch (sizing, encXORPass, then
// Blowfish-encrypt with the static bootstrap key), with an explicit XOR key
// standing in for Java's Rnd.nextInt() so the vector is reproducible.
func TestLoginCryptFirstPacketPipeline(t *testing.T) {
	static, err := NewBlowfishCipher(staticBootstrapKey)
	if err != nil {
		t.Fatalf("NewBlowfishCipher: %v", err)
	}

	payload := testPattern(11)
	buf := make([]byte, paddedSize(len(payload)+4+4))
	copy(buf, payload)
	xorPass(buf, 0x11223344)
	encryptBlocks(static, buf)

	want := mustHex(t, "2b616d63095728b3715e30881ce77aed12795fb6b681c889")
	if !bytes.Equal(buf, want) {
		t.Fatalf("first packet pipeline = %x, want %x", buf, want)
	}
}

// Expected ciphertext/plaintext were generated by running the reference Java
// LoginCrypt.encrypt/decrypt's dynamic-key branch, which has no PRNG
// dependency, so LoginCrypt.Encrypt/Decrypt can be compared directly.
func TestLoginCryptDynamicPacketMatchesOracle(t *testing.T) {
	dynamic, err := NewBlowfishCipher(mustHex(t, "0011223344556677"))
	if err != nil {
		t.Fatalf("NewBlowfishCipher: %v", err)
	}
	lc := &LoginCrypt{dynamic: dynamic, first: false}

	payload := testPattern(10)
	got := lc.Encrypt(payload)
	want := mustHex(t, "f6ea8950b2a2ced3df90ad1c1ac4d312")
	if !bytes.Equal(got, want) {
		t.Fatalf("Encrypt() = %x, want %x", got, want)
	}

	decrypted := append([]byte(nil), got...)
	if err := lc.Decrypt(decrypted); err != nil {
		t.Fatalf("Decrypt() error: %v", err)
	}
	wantDecrypted := mustHex(t, "0112233445566778899a0000cdde444c")
	if !bytes.Equal(decrypted, wantDecrypted) {
		t.Fatalf("Decrypt() = %x, want %x", decrypted, wantDecrypted)
	}
}

func TestLoginCryptDecryptRejectsBadChecksum(t *testing.T) {
	dynamic, err := NewBlowfishCipher(mustHex(t, "0011223344556677"))
	if err != nil {
		t.Fatalf("NewBlowfishCipher: %v", err)
	}
	lc := &LoginCrypt{dynamic: dynamic, first: false}

	buf := lc.Encrypt(testPattern(10))
	buf[0] ^= 0xFF
	if err := lc.Decrypt(buf); err == nil {
		t.Fatal("Decrypt() error = nil, want checksum error")
	}
}

func TestLoginCryptDecryptRejectsBadLength(t *testing.T) {
	dynamic, err := NewBlowfishCipher(mustHex(t, "0011223344556677"))
	if err != nil {
		t.Fatalf("NewBlowfishCipher: %v", err)
	}
	lc := &LoginCrypt{dynamic: dynamic, first: false}

	if err := lc.Decrypt(make([]byte, 5)); err == nil {
		t.Fatal("Decrypt() error = nil, want length error")
	}
	if err := lc.Decrypt(nil); err == nil {
		t.Fatal("Decrypt() error = nil, want length error")
	}
}

func TestLoginCryptRoundTrip(t *testing.T) {
	lc, err := NewLoginCrypt(mustHex(t, "00112233445566778899aabbccddeeff"))
	if err != nil {
		t.Fatalf("NewLoginCrypt: %v", err)
	}

	// First call uses the static key/XOR pass; only later calls round-trip
	// through Decrypt, which always uses the dynamic key (matching the
	// reference behavior where the client, not this type, decodes Init).
	_ = lc.Encrypt(testPattern(6))

	for _, n := range []int{0, 1, 7, 8, 37} {
		payload := testPattern(n)
		enc := lc.Encrypt(payload)
		buf := append([]byte(nil), enc...)
		if err := lc.Decrypt(buf); err != nil {
			t.Fatalf("Decrypt() error for len %d: %v", n, err)
		}
		if !bytes.Equal(buf[:n], payload) {
			t.Fatalf("round trip for len %d = %x, want %x", n, buf[:n], payload)
		}
	}
}

func TestNewLoginCryptRejectsOversizedKey(t *testing.T) {
	if _, err := NewLoginCrypt(make([]byte, 57)); err == nil {
		t.Fatal("expected error for 57-byte key, got nil")
	}
}
