package crypt

import (
	"bytes"
	"math/big"
	"testing"
)

// Expected scrambled moduli were generated by running the reference Java
// ScrambledKeyPair.scrambleModulus against each modulus value.
func TestScrambleModulus(t *testing.T) {
	tests := []struct {
		name      string
		modulus   string // hex, as produced by Java's BigInteger.toByteArray() (may carry a leading sign byte)
		scrambled string
	}{
		{
			name:      "128-byte modulus",
			modulus:   "59170fbb183477a35a94c9bf390b770209d32a595d4a987d41f4b3e592471abe05194bb55dcab3910016175aa147e1f3e98ee81edf7fae40bfe793d9fced52b202e34d15e5c4caaf166fc2edcea4fb1b65e240a4e944b31d0705e6c8b71cf8bdfc97c696693058b22edd1479f1953297e1c82141a6a46d99364cf461b317c99f",
			scrambled: "a6185670fdf0bd0c4cfb0b52f72bbbce6b316afdb40e2b6046f1552d255be203f98e8d2334faeb232ecb032350d2d3640846c95f79dbc3d989ab67b84ffa9b2da4fb1b65183477a35a94c9bf3972acc1d0d32a595d4a987d41f4b3e592471abe05194bb55dcab3910016175aa147e1f3e98ee81edf7fae40bfe793d9fced52b2",
		},
		{
			// This modulus's high bit is set, so Java's BigInteger.toByteArray()
			// carries a leading 0x00 sign byte (129 bytes total). Go's
			// big.Int.Bytes() never adds that byte, so scrambleModulus needs no
			// special case to reach the same 128-byte result Java produces
			// after its own strip.
			name:      "leading sign byte from Java BigInteger",
			modulus:   "00ee614cc5a74b029f8f814e38d93995b694aa2150847891d75da8ddddc46434afeb50781ae04364f9b3a3f3707eab79470ba3c885b66c499800da641a22a420ee9989ec985901e416c9c38fbf7ae22a00a4174c64b5144dc69831c2d5e9f8c7dcb1c3a276da03c5c5347dd8728b234273149eb6e9bb0ff5f4111a021c9a0168a9",
			scrambled: "7ba3ec3cfe4ae6894642c187a3da97463dbd6d34316cdc11c5991f082d9cf3735a93da6c3a40a13c87de2b02f5883b341f3d7e6c0d63bc6c11c06606b8a54847e22a00a4a74b029f8f814e38d934f60af8aa2150847891d75da8ddddc46434afeb50781ae04364f9b3a3f3707eab79470ba3c885b66c499800da641a22a420ee",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			modulus := mustHex(t, tt.modulus)
			mod := new(big.Int).SetBytes(modulus)

			got, err := scrambleModulus(mod)
			if err != nil {
				t.Fatalf("scrambleModulus: %v", err)
			}
			want := mustHex(t, tt.scrambled)
			if !bytes.Equal(got, want) {
				t.Fatalf("scrambleModulus() = %x, want %x", got, want)
			}
		})
	}
}

func TestScrambleModulusRejectsWrongSize(t *testing.T) {
	if _, err := scrambleModulus(big.NewInt(12345)); err == nil {
		t.Fatal("expected error for non-1024-bit modulus, got nil")
	}
}

func TestNewLoginKeyPair(t *testing.T) {
	kp, err := NewLoginKeyPair()
	if err != nil {
		t.Fatalf("NewLoginKeyPair: %v", err)
	}
	if kp.Private == nil {
		t.Fatal("Private is nil")
	}
	if got := kp.Private.N.BitLen(); got != modulusSize*8 {
		t.Fatalf("modulus bit length = %d, want %d", got, modulusSize*8)
	}
	if len(kp.ScrambledModulus) != modulusSize {
		t.Fatalf("len(ScrambledModulus) = %d, want %d", len(kp.ScrambledModulus), modulusSize)
	}
}
