package statbonus

import "testing"

// Expected values were generated by running the reference static
// initializer's exact arithmetic (Math.floor(Math.pow(base, i-offset)*100
// + .5) / 100, and Math.sqrt(i)*6) under a JVM (OpenJDK 21), not
// hand-derived from the formula.
func TestBonusTables(t *testing.T) {
	tests := []struct {
		i                             int
		str, con, dex, intv, wit, men float64
		evasAcc                       float64
	}{
		{0, 0.29, 0.44, 0.84, 0.54, 0.38, 1.0, 0.0},
		{1, 0.3, 0.46, 0.85, 0.55, 0.4, 1.01, 6.0},
		{4, 0.34, 0.5, 0.87, 0.58, 0.46, 1.04, 12.0},
		{10, 0.42, 0.59, 0.92, 0.65, 0.61, 1.11, 18.973665961010276},
		{20, 0.59, 0.8, 1.01, 0.8, 1.0, 1.22, 26.832815729997478},
		{30, 0.84, 1.07, 1.1, 0.97, 1.63, 1.35, 32.863353450309965},
		{40, 1.2, 1.44, 1.2, 1.19, 2.65, 1.49, 37.94733192202055},
		{50, 1.71, 1.94, 1.32, 1.45, 4.32, 1.65, 42.42640687119285},
		{60, 2.43, 2.6, 1.44, 1.76, 7.04, 1.82, 46.47580015448901},
		{70, 3.47, 3.5, 1.57, 2.15, 11.47, 2.01, 50.19960159204453},
		{80, 4.94, 4.7, 1.72, 2.62, 18.68, 2.22, 53.665631459994955},
		{90, 7.03, 6.32, 1.88, 3.19, 30.43, 2.45, 56.92099788303083},
		{99, 9.67, 8.24, 2.04, 3.82, 47.2, 2.68, 59.69924622639719},
	}

	for _, tt := range tests {
		if got := STRBonus[tt.i]; got != tt.str {
			t.Errorf("STRBonus[%d] = %v, want %v", tt.i, got, tt.str)
		}
		if got := CONBonus[tt.i]; got != tt.con {
			t.Errorf("CONBonus[%d] = %v, want %v", tt.i, got, tt.con)
		}
		if got := DEXBonus[tt.i]; got != tt.dex {
			t.Errorf("DEXBonus[%d] = %v, want %v", tt.i, got, tt.dex)
		}
		if got := INTBonus[tt.i]; got != tt.intv {
			t.Errorf("INTBonus[%d] = %v, want %v", tt.i, got, tt.intv)
		}
		if got := WITBonus[tt.i]; got != tt.wit {
			t.Errorf("WITBonus[%d] = %v, want %v", tt.i, got, tt.wit)
		}
		if got := MENBonus[tt.i]; got != tt.men {
			t.Errorf("MENBonus[%d] = %v, want %v", tt.i, got, tt.men)
		}
		if got := BaseEvasionAccuracy[tt.i]; got != tt.evasAcc {
			t.Errorf("BaseEvasionAccuracy[%d] = %v, want %v", tt.i, got, tt.evasAcc)
		}
	}
}
