package network

import (
	"bytes"
	"encoding/hex"
	"testing"
)

// key is the fixed 16-byte seed (0x10..0x1f) used for every oracle vector
// below, generated by running the reference cipher logic directly.
var key = mustHex("101112131415161718191a1b1c1d1e1f")

func mustHex(s string) []byte {
	b, err := hex.DecodeString(s)
	if err != nil {
		panic(err)
	}
	return b
}

func TestNewCipherRejectsWrongKeySize(t *testing.T) {
	if _, err := NewCipher(key[:15]); err == nil {
		t.Fatal("expected error for 15-byte key, got nil")
	}
	if _, err := NewCipher(append(key, 0)); err == nil {
		t.Fatal("expected error for 17-byte key, got nil")
	}
}

func TestCipherFirstEncryptArmsWithoutTransforming(t *testing.T) {
	c, err := NewCipher(key)
	if err != nil {
		t.Fatal(err)
	}
	plaintext := []byte("INIT_PACKET_BODY")
	buf := append([]byte(nil), plaintext...)

	c.Encrypt(buf)

	if !bytes.Equal(buf, plaintext) {
		t.Errorf("first Encrypt call must leave buf untouched: got %x, want %x", buf, plaintext)
	}
}

func TestCipherDecryptBeforeArmIsNoop(t *testing.T) {
	c, err := NewCipher(key)
	if err != nil {
		t.Fatal(err)
	}
	plaintext := []byte("not yet armed!!!")
	buf := append([]byte(nil), plaintext...)

	c.Decrypt(buf)

	if !bytes.Equal(buf, plaintext) {
		t.Errorf("Decrypt before the cipher is armed must leave buf untouched: got %x, want %x", buf, plaintext)
	}
}

// TestCipherEncryptSequenceMatchesOracle proves the key roll across
// successive packets against vectors generated by the reference cipher.
func TestCipherEncryptSequenceMatchesOracle(t *testing.T) {
	tests := []struct {
		plaintext, cipher string
	}{
		{"48656c6c6f2c20776f726c6421212121", "582c522d566f59394e25532c112d122c"},
		{"7365636f6e64207061636b657420626f647921", "6317661a601127400973027c1429552551390a"},
		{"33726421", "23403604"},
	}

	c, err := NewCipher(key)
	if err != nil {
		t.Fatal(err)
	}
	c.Encrypt(make([]byte, 16)) // arm, mirroring the cleartext first packet

	for i, tt := range tests {
		buf := mustHex(tt.plaintext)
		c.Encrypt(buf)
		want := mustHex(tt.cipher)
		if !bytes.Equal(buf, want) {
			t.Errorf("packet %d: got %x, want %x", i, buf, want)
		}
	}
}

// TestCipherRoundTrip proves decrypt(encrypt(x)) == x across successive
// packets once both sides are armed, against reference round-trip vectors.
func TestCipherRoundTrip(t *testing.T) {
	plaintexts := []string{
		"48656c6c6f2c20776f726c6421212121",
		"7365636f6e64207061636b657420626f647921",
		"33726421",
	}

	server, err := NewCipher(key)
	if err != nil {
		t.Fatal(err)
	}
	client, err := NewCipher(key)
	if err != nil {
		t.Fatal(err)
	}
	server.enabled = true
	client.enabled = true

	for i, pt := range plaintexts {
		want := mustHex(pt)
		buf := append([]byte(nil), want...)

		server.Encrypt(buf)
		client.Decrypt(buf)

		if !bytes.Equal(buf, want) {
			t.Errorf("packet %d: round trip got %x, want %x", i, buf, want)
		}
	}
}
